#!/bin/bash
# Self-test for lib/json.sh and lib/image.sh, on EVERY backend this machine has.
#
# Run it on both platforms: `bash scripts/lib/lib.test.sh`.
#
# The point is not that the happy path works — it is that each fallback works,
# because the fallback is the path nobody exercises until they are on a fresh
# Ubuntu box at 2am. So where a second backend exists, the suite runs the whole
# thing again with the first one hidden from PATH.

set -u
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=./json.sh
. "$LIB_DIR/json.sh"
# shellcheck source=./image.sh
. "$LIB_DIR/image.sh"

# Hiding a binary by editing PATH also hides coreutils (`dirname`, `cat`,
# `mktemp` live in the same /usr/bin), which breaks the harness rather than the
# library under test. Every backend probe in these libs goes through `have`, so
# that is the seam: override it and one specific binary disappears while the
# rest of the machine stays intact.
HIDE_BIN=""
have() {
  [ -n "$HIDE_BIN" ] && [ "$1" = "$HIDE_BIN" ] && return 1
  command -v "$1" >/dev/null 2>&1
}

pass=0; fail=0
ok()   { pass=$((pass+1)); echo "  ✔ $1"; }
bad()  { fail=$((fail+1)); echo "  ✘ $1"; [ -n "${2:-}" ] && echo "      $2"; }
is()   { if [ "$2" = "$3" ]; then ok "$1"; else bad "$1" "expected '$3', got '$2'"; fi; }

JSON='{"tool_name":"Read","tool_input":{"file_path":"/tmp/a b.png","n":3},"permissions":{"allow":["Bash","Read"]},"nested":{"deep":{"v":"yes"}},"quote":"he said \"hi\""}'

test_json() {
  local label="$1"
  echo "── json.sh ($label) ──"

  is "reads a top-level string"      "$(json_get '.tool_name' "$JSON")" "Read"
  is "reads a nested string"         "$(json_get '.tool_input.file_path' "$JSON")" "/tmp/a b.png"
  is "reads a deeply nested string"  "$(json_get '.nested.deep.v' "$JSON")" "yes"
  is "reads a number as text"        "$(json_get '.tool_input.n' "$JSON")" "3"
  is "an absent path is empty"       "$(json_get '.nope' "$JSON")" ""
  is "an absent nested path is empty" "$(json_get '.nope.deeper' "$JSON")" ""
  # Objects come back as compact JSON so a caller can embed them verbatim.
  case "$(json_get '.tool_input' "$JSON")" in
    *'"file_path"'*) ok "an object comes back as JSON" ;;
    *) bad "an object comes back as JSON" "got: $(json_get '.tool_input' "$JSON")" ;;
  esac
  is "reads from stdin too"          "$(printf '%s' "$JSON" | json_get '.tool_name')" "Read"

  # Garbage must be empty, not a crash and not a partial match.
  is "invalid JSON yields empty"     "$(json_get '.tool_name' 'not json at all')" ""

  json_array_has '.permissions.allow' 'Bash' "$JSON" && ok "array membership: present" || bad "array membership: present"
  json_array_has '.permissions.allow' 'Write' "$JSON" && bad "array membership: absent" || ok "array membership: absent"
  json_array_has '.nope' 'Bash' "$JSON" && bad "array membership: missing path" || ok "array membership: missing path"

  is "quotes a plain string"         "$(json_quote 'hi')" '"hi"'
  # The escaping case that would produce invalid JSON if hand-rolled.
  is "escapes embedded quotes"       "$(json_quote 'he said "hi"')" '"he said \"hi\""'

  local merged
  merged=$(json_merge '{"state":"running","ts":7}' '{"state":"idle","session_id":"s1"}')
  is "merge keeps untouched fields"  "$(json_get '.session_id' "$merged")" "s1"
  is "merge overwrites"              "$(json_get '.state' "$merged")" "running"
  is "merge adds"                    "$(json_get '.ts' "$merged")" "7"

  # A round trip through quote → merge → get must survive a quote character
  # (e.g. a session id or path embedding one).
  local rt
  rt=$(json_merge "{\"session_id\":$(json_quote 'a"b')}" '{}')
  is "quote survives a merge round trip" "$(json_get '.session_id' "$rt")" 'a"b'
}

test_image() {
  local label="$1"
  echo "── image.sh ($label) ──"
  unset _HERMIT_IMAGE_BACKEND   # the backend is memoised; re-probe it
  echo "  backend: $(image_backend)"
  [ "$(image_backend)" = "none" ] && { bad "a backend is available"; return; }

  local tmp; tmp=$(mktemp -d)
  # A 120x40 PNG, generated by whichever backend is active so the fixture never
  # needs to be committed as a binary.
  case "$(image_backend)" in
    sips)
      # sips cannot create an image from nothing; use a system one.
      cp /System/Library/CoreServices/DefaultDesktop.heic "$tmp/src.heic" 2>/dev/null \
        || cp /System/Library/Desktop\ Pictures/*.heic "$tmp/src.heic" 2>/dev/null
      if [ ! -f "$tmp/src.heic" ]; then echo "  (no system image to test with; skipping)"; rm -rf "$tmp"; return; fi
      SRC="$tmp/src.heic"
      ;;
    magick)
      "$(_magick)" -size 120x40 xc:red "$tmp/src.png" 2>/dev/null; SRC="$tmp/src.png" ;;
    pil)
      python3 -c '
from PIL import Image
Image.new("RGB", (120, 40), "red").save("'"$tmp"'/src.png")'; SRC="$tmp/src.png" ;;
  esac

  local dims w h
  if dims=$(image_dims "$SRC"); then
    w=${dims% *}; h=${dims#* }
    case "$w$h" in
      *[!0-9]*|"") bad "dims are numeric" "got '$dims'" ;;
      *) ok "dims are numeric ($dims)" ;;
    esac
  else
    bad "image_dims reads a real file"
  fi

  local fmt; fmt=$(image_format "$SRC")
  [ -n "$fmt" ] && ok "image_format reports something ($fmt)" || bad "image_format reports something"

  # Nonexistent and non-image files must FAIL, not return junk — the hook turns
  # this failure into "block the Read".
  image_dims "$tmp/nope.png" >/dev/null 2>&1 && bad "a missing file fails" || ok "a missing file fails"
  printf 'not an image' > "$tmp/bad.png"
  image_dims "$tmp/bad.png" >/dev/null 2>&1 && bad "a corrupt file fails" || ok "a corrupt file fails"

  # Convert with a cap, and check the long edge really came down.
  if image_to_png "$SRC" "$tmp/out.png" 40; then
    ok "image_to_png writes a file"
    local od ow oh long
    if od=$(image_dims "$tmp/out.png"); then
      ow=${od% *}; oh=${od#* }
      long=$(( ow > oh ? ow : oh ))
      [ "$long" -le 40 ] && ok "the long edge was capped ($od)" || bad "the long edge was capped" "got $od"
    fi
    # PNG magic bytes: the 2026-05-14 incident was a .png holding TIFF bytes.
    if head -c 8 "$tmp/out.png" | od -An -tx1 | tr -d ' \n' | grep -qi '^89504e470d0a1a0a'; then
      ok "the output really is PNG"
    else
      bad "the output really is PNG" "magic: $(head -c 8 "$tmp/out.png" | od -An -tx1)"
    fi
  else
    bad "image_to_png writes a file"
  fi
  rm -rf "$tmp"
}

echo "lib self-test — $(uname -s)"
test_json "native: $(command -v jq >/dev/null && echo jq || echo node)"
test_image "native"

# ── run everything again on the fallback path ────────────────────────────────
# The fallback is the branch nobody exercises until they are on a fresh Ubuntu
# box at 2am, so it gets the same suite rather than a smoke test.

if command -v jq >/dev/null 2>&1 && command -v node >/dev/null 2>&1; then
  HIDE_BIN=jq
  test_json "node fallback, jq hidden"
  HIDE_BIN=""
fi

if command -v sips >/dev/null 2>&1 && command -v identify >/dev/null 2>&1 \
   && { command -v magick >/dev/null 2>&1 || command -v convert >/dev/null 2>&1; }; then
  HIDE_BIN=sips
  test_image "ImageMagick fallback, sips hidden"
  HIDE_BIN=""
fi

if python3 -c 'import PIL' >/dev/null 2>&1; then
  # Hide whichever backend would otherwise win, so PIL is what runs.
  if command -v sips >/dev/null 2>&1; then HIDE_BIN=sips
  else HIDE_BIN=identify
  fi
  # image_backend checks identify AND magick; hiding identify is enough to drop
  # the ImageMagick branch, and on macOS sips has to go first.
  if [ "$HIDE_BIN" = sips ] && command -v identify >/dev/null 2>&1; then
    echo "── image.sh (PIL) ── SKIPPED: cannot hide both sips and ImageMagick with one override"
  else
    test_image "PIL fallback"
  fi
  HIDE_BIN=""
fi

echo
echo "$pass passed, $fail failed"
[ "$fail" -eq 0 ]
