// dsh backend: DeepSeek Harness driven one subprocess per turn.
//
// Codex's shape, not pi's: there is no long-lived child to keep alive. Each
// turn spawns `dsh --profile headless --patch <generated overlay>`, which
// swaps dsh's stock one-shot runner for hermit's (dsh/hermit-runner.mjs) —
// that runner resumes the session HERMIT_DSH_RESUME names, submits the task,
// streams the session's events back as JSONL on fd 3, and exits. The
// conversation lives in dsh's own store (~/.dsh/sessions/**, jsonl), so "the
// session" here is a dsh session id plus what we remember about the last turn,
// and the id rides the DB's claudeSessionId column — exactly what
// RuntimeSession.externalSessionId is for, same as a codex thread id.
//
// Auth is the DeepSeek platform key: the gateway reads DEEPSEEK_API_KEY from
// the machine's encrypted secret store per spawn and injects it, which is the
// env dsh's own llm-deepseek adapter documents. Model defaults come from dsh's
// profile config (deepseek-v4-flash as shipped); a session's runtimeModel pins
// one per turn through the runner.
//
// See docs/dsh-runtime-design.md.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawn, type ChildProcess } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import type {
  AgentRuntime, RuntimeHandle, RuntimeImage, RuntimeSession, RuntimeUsage, SyncItem,
} from './types';
import { DshEventTranslator, parseRunnerLine, type DshTotals, type DshUsage } from './dsh-events';
import { readLfLines } from './lf-lines';
import { readSecret } from './pi-credentials';
import { getCredential, type ModelCredential } from '../pi-config';
import { modelLimitsFor } from '../pi-model-limits';
import { api } from '../api';

type DshHandle = RuntimeHandle & {
  /** The dsh session id as the DB knows it; learned from the first turn's hello. */
  stampedSessionId: string | null;
  emit: (item: SyncItem) => void;
  /**
   * Where and what to spawn — refreshed on every ensure(), which chat-runner
   * calls just before each submit, so a model pin changed from the dashboard
   * lands on the very next turn with nothing to rebuild.
   */
  agentDirectory: string;
  provider: string | null;
  modelPin: string | null;
  /** Set for the duration of a turn; the message queue's gate. */
  working: boolean;
  /** The in-flight turn's child. Null between turns. */
  child: ChildProcess | null;
  /** True once interrupt() fired for the current turn. */
  interrupted: boolean;
  /** Ids survive across turns — see the callId note in dsh-events.ts. */
  translator: DshEventTranslator | null;
  /** Cumulative usage as the runner last reported it. */
  totals: DshTotals | null;
  /** Which Settings → Models credential this backend was composed with. */
  credentialId: string | null;
};

const live = new Map<string, DshHandle>();

function handleOf(h: RuntimeHandle): DshHandle | null {
  return live.get(h.sessionId) ?? null;
}

function systemItem(sessionId: string, externalId: string, text: string): SyncItem {
  return { sessionId, role: 'system', content: [{ type: 'text', text }], externalId, claudeSessionId: null };
}

/** The runner plugin shipped beside this file (apps/gateway/dsh/). */
const DSH_ASSETS = fileURLToPath(new URL('../../dsh', import.meta.url));

/**
 * The patch overlay that swaps dsh's stock one-shot runner for hermit's.
 *
 * Generated per turn rather than checked in, because the loader reads `name`
 * raw — a `!!js process.env…` expression there arrives as an object and dies
 * with "name.startsWith is not a function" (measured), unlike in config
 * values. So the runner's absolute path is baked into the file instead.
 * Everything else in the headless composition (tools, sandbox, compaction,
 * session persistence) is kept as dsh ships it.
 */
export function hermitPatchYaml(runnerPath: string, providerRows: string[] = []): string {
  return [
    '# generated by hermit-ui (dsh-exec.ts) — do not edit',
    '- id: headless-startup',
    '  disabled: true',
    '- id: headless-runner',
    '  disabled: true',
    ...providerRows,
    '- insert:',
    '    - id: hermit-runner',
    `      name: '${yamlQuote(runnerPath)}'`,
    '',
  ].join('\n');
}

/** Single-quoted YAML scalar; the values are one-line by piEndpointRoute's guard. */
function yamlQuote(v: string): string {
  return v.replace(/'/g, "''");
}

/**
 * The wire protocols dsh's llm-pi-ai can serve. Everything else must SKIP the
 * route rather than emit it: an invalid `api` fails resolveProfiles at dsh
 * boot, which would kill every dsh turn on this machine — deepseek ones
 * included — over a field that only the pi endpoint uses.
 */
const DSH_APIS = new Set(['anthropic-messages', 'openai-completions', 'openai-responses']);

/** One-line config value; a control character would poison the generated YAML. */
function cleanValue(v: string | null | undefined): string | null {
  const t = v?.trim();
  // eslint-disable-next-line no-control-regex
  return t && !/[\x00-\x1f\x7f]/.test(t) ? t : null;
}

/**
 * The machine's pi endpoint, re-declared as a dsh llm-pi-ai route.
 *
 * This is what lets a dsh session run the same relay-served models the pi
 * backend uses (hyqubit's claude catalog, on this fleet): dsh's llm-pi-ai
 * wraps the SAME @earendil-works/pi-ai the pi engine runs on, so the provider
 * profile hermit-pi-extension registers for pi maps field-for-field onto a
 * "hand-declared route" here. One Settings → Pi Runtime page then serves both
 * backends. Verified end-to-end against litellm.hyqubit.com, 2026-08-15.
 *
 * Returns the YAML rows for hermitPatchYaml plus the facts submit() needs
 * (secret name for the env, model list for pin inference), or null when the
 * machine has no usable endpoint — no provider/baseUrl/models, an api dsh
 * cannot speak, or cc-subscription mode, whose Keychain OAuth path is
 * pi-specific (llm-pi-ai authenticates routes by API key only).
 */
export function piEndpointRoute(cfg: ModelCredential | null): {
  rows: string[];
  provider: string;
  models: string[];
  defaultModel: string;
  secretKey: string;
} | null {
  if (!cfg) return null;
  const provider = cleanValue(cfg.provider);
  const baseUrl = cleanValue(cfg.baseUrl);
  const secretKey = cleanValue(cfg.secretKey);
  const models = (cfg.models ?? []).map((m) => cleanValue(m)).filter((m): m is string => !!m);
  if (!provider || !baseUrl || !secretKey || models.length === 0) return null;
  // The secret's name doubles as the env var llm-pi-ai resolves (apiKeyEnv), so
  // it has to BE a valid env var name.
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(secretKey)) return null;

  // The dashboard's legacy dropdown briefly offered the invalid value 'openai';
  // map it the way the pi path's fix did rather than dropping the route.
  const rawApi = cleanValue(cfg.api) || 'anthropic-messages';
  const api = rawApi === 'openai' ? 'openai-completions' : rawApi;
  if (!DSH_APIS.has(api)) {
    console.warn(`[dsh] pi endpoint api "${rawApi}" is not one dsh's llm-pi-ai speaks — not bridging it`);
    return null;
  }

  const rows: string[] = [
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
    `      ${yamlQuote(provider)}:`,
    `        displayName: '${yamlQuote(provider)} (pi endpoint)'`,
    `        apiKeyEnv: '${yamlQuote(secretKey)}'`,
    `        api: '${yamlQuote(api)}'`,
    `        baseURL: '${yamlQuote(baseUrl)}'`,
    '        models:',
  ];
  for (const id of models) {
    rows.push(`          - id: '${yamlQuote(id)}'`);
    // Real limits where the family is known (claude-opus-5 is 1M/128k — the
    // llm-pi-ai declared-route defaults of 256k/32k would silently shrink it);
    // an unknown model omits the fields and keeps those defaults.
    const limits = modelLimitsFor(id, cfg.modelLimits);
    if (limits.contextWindow) rows.push(`            contextWindow: ${limits.contextWindow}`);
    if (limits.maxTokens) rows.push(`            maxTokens: ${limits.maxTokens}`);
  }
  return {
    rows,
    provider,
    models,
    defaultModel: cleanValue(cfg.defaultModel) || models[0],
    secretKey,
  };
}

/**
 * Fill in the half of a provider/model pin the session left implicit.
 *
 * A model pin that names one of the pi endpoint's models implies that route —
 * from the dashboard's side "claude-opus-5" IS the choice, and making the user
 * also spell the relay's provider id would be a second field carrying no new
 * information. A provider pin without a model lands on the endpoint's default
 * model rather than on dsh's own (deepseek-v4-flash), which that route does
 * not serve and would fail. Explicit pins pass through untouched, and a model
 * the endpoint does not list (deepseek-v4-pro) changes nothing.
 */
export function inferDshSelection(
  route: { provider: string; models: string[]; defaultModel: string } | null,
  provider: string | null,
  modelPin: string | null,
): { provider: string | null; model: string | null } {
  if (!route) return { provider, model: modelPin };
  if (!provider && modelPin && route.models.includes(modelPin)) {
    return { provider: route.provider, model: modelPin };
  }
  if (provider === route.provider && !modelPin) {
    return { provider, model: route.defaultModel };
  }
  return { provider, model: modelPin };
}

/**
 * How to start dsh on this machine.
 *
 * There is no reliable global `dsh` binary: the CLI lives inside the dsh
 * profiles install (`~/.dsh/profiles/node_modules`), which `dsh plugin` manages
 * with pnpm. So the default is to run that file with node directly; a machine
 * that installed dsh elsewhere points HERMIT_DSH_BIN at its bin.js (run with
 * node when it is a .js path, as itself otherwise), and a machine with dsh on
 * PATH just sets HERMIT_DSH_BIN=dsh.
 */
export function resolveDshCommand(env: NodeJS.ProcessEnv = process.env): { cmd: string; args: string[] } | null {
  const override = env.HERMIT_DSH_BIN?.trim();
  if (override) {
    return override.endsWith('.js') || override.endsWith('.mjs')
      ? { cmd: process.execPath, args: [override] }
      : { cmd: override, args: [] };
  }
  const installed = path.join(
    os.homedir(), '.dsh', 'profiles', 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js',
  );
  if (fs.existsSync(installed)) return { cmd: process.execPath, args: [installed] };
  return null;
}

/** The turn's cumulative session total, on the same basis as codex's. */
export function totalTokens(t: DshTotals | null): number {
  if (!t) return 0;
  // dsh's counts are DISJOINT (uncached input, cache reads and cache writes
  // are separate), so billed input is the sum of the three.
  return t.inputTokens + t.cacheReadTokens + t.cacheWriteTokens + t.outputTokens;
}

/** The latest model call's window occupancy — what the context bar wants. */
export function lastCallUsage(t: DshTotals | null): { contextTokens: number; outputTokens: number } | null {
  const u: DshUsage | null = t?.last ?? null;
  if (!u) return null;
  return {
    contextTokens: (u.inputTokens ?? 0) + (u.cacheReadTokens ?? 0) + (u.cacheWriteTokens ?? 0),
    outputTokens: u.outputTokens ?? 0,
  };
}

/** Secrets, cached briefly per name — this sits on the message-delivery path. */
const secretCache = new Map<string, { at: number; value: string | null }>();
async function cachedSecret(name: string): Promise<string | null> {
  const hit = secretCache.get(name);
  if (hit && Date.now() - hit.at < 60_000) return hit.value;
  const value = await readSecret(name);
  secretCache.set(name, { at: Date.now(), value });
  return value;
}

function deepseekKey(): Promise<string | null> {
  return cachedSecret('DEEPSEEK_API_KEY');
}

/** Test seam. */
export function resetDeepseekKeyCache(): void {
  secretCache.clear();
}

/**
 * A turn that produces no runner output for this long is wedged — the model
 * call inside dsh has its own retry/timeout machinery, so silence this length
 * means the process is stuck, not thinking.
 */
const TURN_SILENCE_TIMEOUT_MS = 15 * 60 * 1000;

export class DshExecRuntime implements AgentRuntime {
  readonly kind = 'dsh-exec' as const;

  async ensure(session: RuntimeSession, emit: (item: SyncItem) => void): Promise<RuntimeHandle> {
    const existing = live.get(session.id);
    if (existing) {
      // The spawn env is derived from the handle per turn, so a change here is
      // live on the next submit — unlike codex there is nothing to rebuild.
      existing.emit = emit;
      existing.agentDirectory = session.agentDirectory;
      existing.provider = session.provider?.trim() || null;
      existing.modelPin = session.model?.trim() || null;
      existing.credentialId = session.credentialId ?? null;
      return existing;
    }

    // `externalSessionId` (the DB's `claudeSessionId`) is ONE slot shared by
    // every backend. The switch path clears it on a real backend change, but a
    // row that dodged that (a crash between writes, a hand-edited DB) would
    // hand dsh a claude uuid — and agents.resume() on an id that has no
    // session on disk fails the same way every retry, bricking the chat. dsh
    // ids are self-describing (`session-<uuid>`), so anything else starts a
    // fresh session instead, the same self-healing codex does via its rollout
    // lookup.
    const recorded = session.externalSessionId?.trim() || null;
    const dshId = recorded && /^session-[0-9a-f][0-9a-f-]{20,}$/i.test(recorded) ? recorded : null;
    if (recorded && !dshId) {
      console.warn(
        `[dsh] session=${session.id.slice(0, 8)}: recorded id ${recorded.slice(0, 12)}… is not a dsh session — starting fresh`,
      );
    }
    const handle: DshHandle = {
      sessionId: session.id,
      externalSessionId: dshId ?? '',
      stampedSessionId: dshId,
      emit,
      agentDirectory: session.agentDirectory,
      provider: session.provider?.trim() || null,
      modelPin: session.model?.trim() || null,
      working: false,
      child: null,
      interrupted: false,
      translator: dshId ? new DshEventTranslator(dshId) : null,
      totals: null,
      credentialId: session.credentialId ?? null,
    };
    live.set(session.id, handle);
    return handle;
  }

  /**
   * `session` is re-read at submit time by chat-runner's ensure() call just
   * before this, so model/provider pins are current without a handle rebuild.
   */
  async submit(handle: RuntimeHandle, text: string, images: RuntimeImage[]): Promise<boolean> {
    void images; // chat-runner folds images into `text` for child backends
    const h = handleOf(handle);
    if (!h) return false;
    if (h.working) return false; // a racing tick must not double-submit

    const command = resolveDshCommand();
    if (!command) {
      h.emit(systemItem(
        h.sessionId,
        `dsh:missing:${Date.now().toString(36)}`,
        '[dsh is not installed on this machine]\nInstall DeepSeek Harness (npx @deepseek-ai/dsh web) or set HERMIT_DSH_BIN.',
      ));
      return false;
    }

    const key = await deepseekKey();

    // The machine's pi endpoint, bridged in as an extra route. A failure here
    // must not take the deepseek default down with it — the bridge is optional
    // capability, not a precondition.
    let bridge: { route: NonNullable<ReturnType<typeof piEndpointRoute>>; key: string | null } | null = null;
    try {
      const route = piEndpointRoute(await getCredential(h.credentialId));
      // The route rows go in even when the secret is absent from the store:
      // a claude-pinned turn then fails with llm-pi-ai's own MISSING_CREDENTIAL
      // naming the secret to set, which beats "unknown provider" confusion.
      if (route) bridge = { route, key: await cachedSecret(route.secretKey) };
    } catch (e) {
      console.warn('[dsh] pi endpoint bridge skipped:', e instanceof Error ? e.message : String(e));
    }

    // The backend's credential IS the model source. One that names an endpoint
    // routes unpinned turns there; one with a blank baseUrl (which is how the
    // catalog spells "this harness supplies its own") leaves dsh on its own
    // deepseek catalog. Expressed as a provider default so inferDshSelection
    // fills the model in, exactly as if the session had pinned it by hand.
    // Pinned sessions are unaffected either way.
    const sourceProvider = bridge && !h.provider && !h.modelPin ? bridge.route.provider : null;

    return this.spawnTurn(h, command, text, key, bridge, sourceProvider);
  }

  private spawnTurn(
    h: DshHandle,
    command: { cmd: string; args: string[] },
    text: string,
    key: string | null,
    bridge: { route: NonNullable<ReturnType<typeof piEndpointRoute>>; key: string | null } | null,
    sourceProvider: string | null = null,
  ): boolean {
    // The task travels by file: argv is visible in `ps` and env is sized for
    // configuration, while a chat message can be a pasted document.
    const turnTag = randomUUID();
    const taskFile = path.join(os.tmpdir(), `hermit-dsh-task-${turnTag}.txt`);
    const patchFile = path.join(os.tmpdir(), `hermit-dsh-patch-${turnTag}.yml`);
    try {
      fs.writeFileSync(taskFile, text, { mode: 0o600 });
      fs.writeFileSync(
        patchFile,
        hermitPatchYaml(path.join(DSH_ASSETS, 'hermit-runner.mjs'), bridge?.route.rows ?? []),
        { mode: 0o600 },
      );
    } catch (e) {
      fs.rmSync(taskFile, { force: true });
      this.report(h, e);
      return false;
    }

    const pin = inferDshSelection(bridge?.route ?? null, h.provider ?? sourceProvider, h.modelPin);

    const profile = process.env.HERMIT_DSH_PROFILE?.trim() || 'headless';
    const child = spawn(
      command.cmd,
      [...command.args, '--profile', profile, '--patch', patchFile],
      {
        cwd: h.agentDirectory,
        // fd 3 is the reporting channel — see hermit-runner.mjs. stdout/stderr
        // are captured only to diagnose a turn that dies before reporting.
        stdio: ['ignore', 'pipe', 'pipe', 'pipe'],
        env: {
          ...process.env,
          ...(key ? { DEEPSEEK_API_KEY: key } : {}),
          // The bridged route's credential, under the env name its apiKeyEnv
          // declares (the secret's own name, same convention as pi).
          ...(bridge?.key ? { [bridge.route.secretKey]: bridge.key } : {}),
          HERMIT_DSH_TASK_FILE: taskFile,
          HERMIT_DSH_EVENTS_FD: '3',
          ...(h.stampedSessionId ? { HERMIT_DSH_RESUME: h.stampedSessionId } : {}),
          ...(pin.provider ? { HERMIT_DSH_PROVIDER: pin.provider } : {}),
          ...(pin.model ? { HERMIT_DSH_MODEL: pin.model } : {}),
          // No TTY: anything that could prompt would hang the turn. Same
          // posture as the claude path's --dangerously-skip-permissions and
          // codex's danger-full-access; overridable per machine.
          DSH_PERMISSION_MODE: process.env.HERMIT_DSH_PERMISSION_MODE?.trim() || 'danger-full-access',
        },
      },
    );

    h.child = child;
    h.working = true;
    h.interrupted = false;

    let sawDone = false;
    let stderrTail = '';
    child.stderr?.on('data', (chunk: Buffer) => {
      stderrTail = (stderrTail + chunk.toString('utf8')).slice(-4000);
    });
    // Stray stdout (a dsh plugin logging) is drained so the child never blocks.
    child.stdout?.resume();

    const silence = () => setTimeout(() => {
      console.warn(`[dsh] session=${h.sessionId.slice(0, 8)}: no runner output for ${TURN_SILENCE_TIMEOUT_MS / 60000}min — killing the turn`);
      child.kill('SIGKILL');
    }, TURN_SILENCE_TIMEOUT_MS);
    let watchdog = silence();

    const events = child.stdio[3];
    if (events && 'on' in events) {
      readLfLines(events as NodeJS.ReadableStream, (line) => {
        clearTimeout(watchdog);
        watchdog = silence();
        const msg = parseRunnerLine(line);
        if (!msg) return;

        if (msg.hermit === 'hello') {
          h.totals = msg.totals ?? h.totals;
          if (msg.sessionId && msg.sessionId !== h.stampedSessionId) {
            // Stamp the dsh session id onto the row so a gateway restart (and
            // the next turn) can resume it — the sync route only writes when
            // it differs, so this is idempotent.
            h.stampedSessionId = msg.sessionId;
            h.translator = new DshEventTranslator(msg.sessionId);
            h.emit({
              sessionId: h.sessionId,
              role: 'system',
              content: [{ type: 'text', text: `[dsh session ${msg.sessionId.replace(/^session-/, '').slice(0, 8)}]` }],
              externalId: `dsh:${msg.sessionId}:hello`,
              claudeSessionId: msg.sessionId,
            });
          }
          return;
        }

        if (msg.hermit === 'event') {
          if (msg.type === 'assistant/message') {
            // The runner's done-totals also carry this, but updating per call
            // keeps the context bar live during a long tool-heavy turn.
            const usage = (msg.data as { usage?: DshUsage } | null)?.usage;
            if (usage && h.totals) {
              h.totals = {
                inputTokens: h.totals.inputTokens + (usage.inputTokens ?? 0),
                outputTokens: h.totals.outputTokens + (usage.outputTokens ?? 0),
                cacheReadTokens: h.totals.cacheReadTokens + (usage.cacheReadTokens ?? 0),
                cacheWriteTokens: h.totals.cacheWriteTokens + (usage.cacheWriteTokens ?? 0),
                last: usage,
              };
            }
          }
          const translator = h.translator ?? (h.translator = new DshEventTranslator(h.stampedSessionId ?? ''));
          for (const item of translator.translate(msg.seq, msg.type, msg.data)) {
            h.emit({ ...item, sessionId: h.sessionId, claudeSessionId: null });
          }
          return;
        }

        // done
        sawDone = true;
        h.totals = msg.totals ?? h.totals;
      });
    }

    child.on('error', (e) => {
      clearTimeout(watchdog);
      h.working = false;
      h.child = null;
      fs.rmSync(taskFile, { force: true });
      fs.rmSync(patchFile, { force: true });
      this.report(h, e);
    });

    child.on('exit', (code, signal) => {
      clearTimeout(watchdog);
      // Give the line reader a beat to flush its last lines before judging.
      setImmediate(() => {
        h.working = false;
        h.child = null;
        fs.rmSync(taskFile, { force: true });
        fs.rmSync(patchFile, { force: true });
        if (h.interrupted) {
          h.emit(systemItem(h.sessionId, `dsh:${Date.now().toString(36)}:interrupted`, '[turn interrupted]'));
        } else if (!sawDone) {
          // Died before the runner reported — dsh missing its deps, the key
          // rejected at boot, a crash. The turn's rows never arrived, so say so.
          this.report(
            h,
            new Error(`dsh exited ${signal ?? code} before completing the turn\n${stderrTail.trim().slice(-800)}`),
          );
        }
      });
    });

    return true;
  }

  /** Put a failure in the chat. Silence here reads as the agent ignoring you. */
  private report(h: DshHandle, e: unknown): void {
    const message = e instanceof Error ? e.message : String(e);
    console.error(`[dsh] session=${h.sessionId.slice(0, 8)} turn failed:`, message);
    h.emit(systemItem(
      h.sessionId,
      `dsh:${Date.now().toString(36)}:error`,
      `[dsh could not run this turn]\n${message.slice(0, 1000)}`,
    ));
  }

  async isWorking(handle: RuntimeHandle): Promise<boolean> {
    return handleOf(handle)?.working ?? false;
  }

  /** A live child for this session — true before any totals exist, unlike usage(). */
  async isLive(handle: RuntimeHandle): Promise<boolean> {
    return handleOf(handle) !== null;
  }

  async interrupt(handle: RuntimeHandle): Promise<void> {
    const h = handleOf(handle);
    if (!h?.child) return;
    h.interrupted = true;
    // dsh's launcher turns SIGINT into an orderly tree disposal, which flushes
    // the session log; only a process that ignores that gets the hard kill.
    const child = h.child;
    child.kill('SIGINT');
    setTimeout(() => {
      if (h.child === child) child.kill('SIGKILL');
    }, 5_000).unref();
  }

  async compact(handle: RuntimeHandle, instructions?: string): Promise<void> {
    void instructions;
    const h = handleOf(handle);
    if (!h) return;
    // dsh compacts its own sessions (dsh-compaction-basic) and its /compact is
    // an interactive command the headless runner has no way to invoke. Saying
    // so beats a silent no-op, which is indistinguishable from a wedged session.
    h.emit(systemItem(
      h.sessionId,
      `dsh:${Date.now().toString(36)}:compact`,
      '[dsh manages its own context window — there is nothing to compact by hand]',
    ));
  }

  async usage(handle: RuntimeHandle): Promise<RuntimeUsage | null> {
    const h = handleOf(handle);
    if (!h?.totals) return null;
    const last = lastCallUsage(h.totals);
    return {
      contextTokens: last?.contextTokens ?? null,
      outputTokens: last?.outputTokens ?? null,
      totalTokens: totalTokens(h.totals),
      // DeepSeek bills per token, but the price belongs to their account page;
      // computing one here would put a number in the cost column that drifts
      // from the invoice the moment they change pricing.
      costUsd: null,
    };
  }

  async stop(handle: RuntimeHandle, mode: 'hibernate' | 'kill'): Promise<void> {
    const h = live.get(handle.sessionId);
    if (!h) return;
    live.delete(handle.sessionId);
    if (h.child) {
      h.interrupted = true;
      h.child.kill('SIGINT');
    }
    // Both modes keep the session: the conversation lives in dsh's own store
    // and the id is on the session row, so the next message resumes it. `kill`
    // is chat-runner's restart button — "unwedge this", not "forget this".
    void mode;
  }
}
