// omp backend: one `omp --mode rpc` child process per chat session.
//
// omp (oh-my-pi) is a fork of pi with a much larger built-in tool surface —
// ast_edit, lsp, debug, browser, computer, github, memory — where pi keeps four
// tools and expects you to add the rest. Both are offered rather than one
// replacing the other: pi is small and predictable, omp is capable and moves
// fast, and which is right depends on the work.
//
// The wire is JsonlTransport (see there for why omp's own client cannot be used).
// Session events are the SAME vocabulary as pi's — `message_end` with
// `{text,thinking,toolCall}` parts, `tool_execution_end` with
// `{toolCallId,toolName,result,isError}` — verified against a live child, so
// translatePiEvent is reused unchanged rather than forked.
//
// See docs/pi-modes-design.md and docs/omp-runtime-design.md.

import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs';
import type {
  AgentRuntime, RuntimeHandle, RuntimeImage, RuntimeSession, RuntimeUsage, SyncItem,
} from './types';
import { translatePiEvent } from './pi-events';
import { singleFlight } from './pi-rpc';
import { resolveMode, buildModeArgs } from './pi-modes';
import { CHAT_ONLY_OMP_TOOLS } from './chat-only';
import {
  providerEnv, visionEnv, readSecret, machineProviderEnv,
  fingerprintAuthEnv, currentAuthFingerprint,
} from './pi-credentials';
import { readPiSession, rememberPiSession, resumablePiSession } from './pi-sessions';
import { getCredential, credentialDefaultModel } from '../pi-config';
import { modelLimitsFor, type ModelLimits } from '../pi-model-limits';
import { JsonlTransport, type RpcEvent } from './jsonl-transport';
import { DASHBOARD_URL, ASST_KEY } from '../config';

/** The hermit tools extension, loaded into every omp child with --extension. */
function hermitExtensionPath(): string {
  return new URL('./hermit-pi-extension.ts', import.meta.url).pathname;
}

/**
 * Where omp lives. Installed with `bun install -g`, so it is not resolvable
 * from this package's node_modules — and deliberately not a dependency, since
 * pulling omp's 36MB (and its Bun requirement) into the gateway's install for a
 * backend most machines will not use is not a trade worth making.
 */
function resolveOmpCli(): string {
  const explicit = process.env.HERMIT_OMP_CLI?.trim();
  const candidates = [
    ...(explicit ? [explicit] : []),
    path.join(os.homedir(), '.bun', 'install', 'global', 'node_modules',
      '@oh-my-pi', 'pi-coding-agent', 'dist', 'cli.js'),
  ];
  const hit = candidates.find((p) => fs.existsSync(p));
  if (!hit) {
    throw new Error(
      'omp is not installed on this machine. Install it with '
      + '`bun install -g @oh-my-pi/pi-coding-agent` (needs Bun >= 1.3.14), '
      + 'or set HERMIT_OMP_CLI to its cli.js.',
    );
  }
  return hit;
}

/** Marker line proving a models.yml is ours to rewrite. */
const GENERATED_MARKER = '# generated by hermit gateway — edits below are overwritten';
/**
 * Keep omp's provider config in step with Settings → Pi Runtime.
 *
 * omp resolves providers from `~/.omp/agent/models.yml`, so without this a
 * machine that has omp installed still cannot reach the endpoint the dashboard
 * says it uses — the failure being a 401 at first turn, long after the point
 * where it could be understood. Generating it from piConfig keeps one source of
 * truth instead of two that drift.
 *
 * `apiKey` is written as the NAME of an environment variable, which is what omp
 * expects and what lets the value stay out of the file; boot() injects it.
 *
 * A file without our marker was written by a human and is left alone.
 *
 * Each model carries its context window and output cap — see pi-model-limits.
 * omp has not been caught truncating the way pi has, but it resolves models
 * through the same provider-keyed catalog, so it is one unlucky model id away
 * from the same 128k guess.
 */
export function ensureOmpModelsYaml(
  cfg: {
    provider?: string; baseUrl?: string; api?: string; models?: string[]; secretKey?: string | null;
    modelLimits?: Record<string, ModelLimits> | null;
  },
  dir = path.join(os.homedir(), '.omp', 'agent'),
): void {
  const provider = cfg.provider?.trim();
  const baseUrl = cfg.baseUrl?.trim();
  if (!provider || !baseUrl) return;

  const file = path.join(dir, 'models.yml');
  if (fs.existsSync(file)) {
    const existing = fs.readFileSync(file, 'utf8');
    if (!existing.includes(GENERATED_MARKER)) return; // hand-written; not ours
  }

  const q = (s: string) => JSON.stringify(s); // YAML accepts JSON double-quoting
  const models = (cfg.models ?? []).filter(Boolean);
  const lines = [
    GENERATED_MARKER,
    '# Source: the dashboard\'s Settings -> Pi Runtime page (Machine.piConfig).',
    '# apiKey names an environment variable; the gateway injects the value per session.',
    'providers:',
    `  ${provider}:`,
    `    baseUrl: ${q(baseUrl)}`,
    `    api: ${q(cfg.api?.trim() || 'anthropic-messages')}`,
    '    apiKey: HERMIT_PI_API_KEY',
    // LiteLLM-style proxies reject Anthropic's `strict` tool field outright.
    '    disableStrictTools: true',
    ...(models.length
      ? ['    models:', ...models.flatMap((m) => {
          const limits = modelLimitsFor(m, cfg.modelLimits);
          return [
            `      - id: ${q(m)}`,
            `        name: ${q(m)}`,
            ...(limits.contextWindow ? [`        contextWindow: ${limits.contextWindow}`] : []),
            ...(limits.maxTokens ? [`        maxTokens: ${limits.maxTokens}`] : []),
          ];
        })]
      : []),
    '',
  ];

  const next = lines.join('\n');
  const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (prev === next) return;
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, next);
  console.log(`[omp] wrote ${file} for provider "${provider}"`);
}

type OmpHandle = RuntimeHandle & {
  transport: JsonlTransport;
  seen: Set<string>;
  ordinal: number;
  bootId: string;
  /** Mode this child was spawned with; a change means a new child. */
  mode: string | null;
  /** Credential it booted against; a change is a different endpoint entirely. */
  credentialId: string | null;
  /**
   * Fingerprint of the credentials this child was booted with.
   *
   * omp reads its auth from the environment once, at startup, and an env is
   * fixed for the life of a process — so a child outlives its own credential.
   * A rotated key is not hypothetical: every turn on a child older than the
   * rotation comes back 401 until someone restarts it (observed on sway003 and
   * macmini003, 2026-08-07, both wedged ~9h in, then under the Claude
   * subscription path that no longer exists). Comparing this against the
   * current fingerprint is what turns that into a recycle nobody sees.
   */
  authFingerprint: string | null;
  emit: (item: SyncItem) => void;
  lastTurn: { contextTokens: number; outputTokens: number } | null;
};

const live = new Map<string, OmpHandle>();
const starting = new Map<string, Promise<OmpHandle>>();
const bootFailedUntil = new Map<string, { until: number; error: Error }>();
const BOOT_BACKOFF_MS = 15_000;

function systemItem(sessionId: string, externalId: string, text: string): SyncItem {
  return { sessionId, role: 'system', content: [{ type: 'text', text }], externalId, claudeSessionId: null };
}

function handleOf(h: RuntimeHandle): OmpHandle | null {
  return live.get(h.sessionId) ?? null;
}

/** Same basis as the claude path's contextTokens: what was sent for this turn. */
function contextTokensFrom(u: Record<string, number> | undefined): number | null {
  if (!u) return null;
  const n = (v: unknown) => (typeof v === 'number' ? v : 0);
  const total = n(u.input) + n(u.cacheRead) + n(u.cacheWrite);
  return total > 0 ? total : null;
}

/** Tell the chat a child is gone, and whether its conversation survived it. */
function announceExit(h: OmpHandle, sessionId: string, reason: string): void {
  console.warn(`[omp] evicted session=${sessionId.slice(0, 8)}: ${reason}`);
  // What the user is told depends on whether the thread survives the child,
  // which is now the ordinary case: omp appends to its session file as the
  // conversation goes, and the next boot reattaches with --resume.
  const next = resumablePiSession(sessionId, undefined, { engine: 'omp' })
    ? 'The next message restarts omp on this conversation and carries on.'
    : "The next message starts a fresh omp session, which will not carry this conversation's context.";
  h.emit(systemItem(sessionId, `${sessionId}:${h.bootId}-exit`, `[omp session ended — ${reason}]\n${next}`));
}

/** Drop a child that is already dead, or that we are giving up on. */
function evict(sessionId: string, reason: string): void {
  const h = live.get(sessionId);
  if (!h) return;
  live.delete(sessionId);
  h.transport.kill();
  announceExit(h, sessionId, reason);
}

/** How long a retiring child gets to drain before it is killed outright. */
const DRAIN_TIMEOUT_MS = 5_000;

/**
 * Close stdin and wait for the child to actually be gone.
 *
 * Awaiting matters because every caller boots a replacement straight after,
 * pointed at the same session file with `--resume`. omp writes that file on
 * stdin close rather than continuously, so returning early would leave two
 * children holding one file and the new one resuming a conversation whose last
 * turn had not landed yet. The deadline bounds it: a child that will not drain
 * is still gone in 5s.
 */
async function drain(transport: JsonlTransport, label: string): Promise<void> {
  transport.end();
  const deadline = Date.now() + DRAIN_TIMEOUT_MS;
  while (transport.isAlive && Date.now() < deadline) {
    await new Promise((r) => { setTimeout(r, 50); });
  }
  if (transport.isAlive) {
    console.warn(`[omp] ${label} did not drain in ${DRAIN_TIMEOUT_MS}ms; killing`);
    transport.kill();
  }
}

/**
 * Retire a child that is still healthy, and wait for it to be gone.
 *
 * Not `evict`, because a SIGKILLed omp writes no session file — killing a
 * healthy child would take the conversation with it, the very thing --resume
 * was added to keep.
 */
async function retire(sessionId: string, reason: string): Promise<void> {
  const h = live.get(sessionId);
  if (!h) return;
  live.delete(sessionId);
  await drain(h.transport, `session=${sessionId.slice(0, 8)}`);
  announceExit(h, sessionId, reason);
}

/**
 * Has the machine's credential moved since this child booted?
 *
 * False when either side is unknown: a machine with no configured credential
 * (children inherit whatever the gateway's own env carries) must not be told
 * its sessions rotate every minute.
 */
async function staleAuth(h: OmpHandle): Promise<boolean> {
  if (!h.authFingerprint) return false;
  const now = await currentAuthFingerprint(h.credentialId);
  return now !== null && now !== h.authFingerprint;
}

export class OmpRpcRuntime implements AgentRuntime {
  readonly kind = 'omp-rpc' as const;

  async ensure(session: RuntimeSession, emit: (item: SyncItem) => void): Promise<RuntimeHandle> {
    const existing = live.get(session.id);
    if (existing) {
      if (!existing.transport.isAlive) {
        evict(session.id, 'child is gone');
      } else {
        const wanted = resolveMode(session.mode)?.name ?? null;
        if (wanted !== existing.mode) {
          evict(session.id, `mode changed ${existing.mode ?? 'none'} → ${wanted ?? 'none'}`);
        } else if ((session.credentialId ?? null) !== existing.credentialId) {
          // A different credential is a different endpoint and model catalog,
          // both baked into the child at spawn. New child, not a push.
          await retire(session.id, 'credential changed');
        } else if (await staleAuth(existing)) {
          // Retired while idle only. Evicting mid-turn would abandon a reply
          // that is still streaming, and this is never urgent: the credential
          // the running turn already sent with is the one it will finish on,
          // and the next tick catches the child once it is quiet.
          if (await this.isWorking(existing)) return existing;
          await retire(session.id, 'auth credential rotated');
        } else {
          return existing;
        }
      }
    }

    const cooling = bootFailedUntil.get(session.id);
    if (cooling && Date.now() < cooling.until) throw cooling.error;

    return singleFlight(starting, session.id, () =>
      this.boot(session, emit)
        .then((handle) => {
          live.set(session.id, handle);
          bootFailedUntil.delete(session.id);
          return handle;
        })
        .catch((e: unknown) => {
          const error = e instanceof Error ? e : new Error(String(e));
          if (!cooling) {
            console.error(`[omp] boot failed for session=${session.id.slice(0, 8)}:`, error.message);
            emit(systemItem(
              session.id,
              `${session.id}:boot-failed-${Date.now()}`,
              `[omp could not start]\n${error.message.slice(0, 800)}`,
            ));
          }
          bootFailedUntil.set(session.id, { until: Date.now() + BOOT_BACKOFF_MS, error });
          throw error;
        }),
    );
  }

  private async boot(session: RuntimeSession, emit: (item: SyncItem) => void): Promise<OmpHandle> {
    const mode = resolveMode(session.mode);
    // The credential this backend was composed with — one entry of Settings →
    // Models, already chosen by the dashboard. omp resolves providers from
    // ~/.omp/agent/models.yml rather than from an extension registration, so
    // that file is generated from whichever credential the session names.
    const credential = await getCredential(session.credentialId);
    if (credential) ensureOmpModelsYaml(credential);

    const model = session.model ?? mode?.model ?? credentialDefaultModel(credential);
    const provider = session.provider ?? credential?.provider;

    // omp resolves a provider from ~/.omp/agent/models.yml rather than from a
    // registerProvider call in an extension — the hack pi needed because it had
    // no way to name a base URL. So `--model provider/id` is the whole wiring,
    // and the hermit extension carries only hermit's tools here.
    const modelArg = model && provider && !model.includes('/') ? `${provider}/${model}` : model;

    // The key for that models.yml entry, which names an env var rather than
    // holding a value. Resolved per boot and handed to the child only.
    const keyEnv: Record<string, string> = {};
    const secretName = credential?.secretKey?.trim();
    if (secretName) {
      const value = await readSecret(secretName);
      if (value) keyEnv.HERMIT_PI_API_KEY = value;
    }

    // The conversation this session was already having, if it had one. Same
    // shape as the pi path: `pointer` without `resume` means we had a thread
    // and lost the file, which is the one case worth telling the user about.
    // omp takes its own session id here rather than a path — verified against a
    // live child (rpc get_state reports both; --resume <id> reattached and the
    // reply carried context planted before the restart).
    const pointer = readPiSession(session.id);
    // The hermit tools and the machine key that authenticates them travel
    // together: a child given one without the other has tools that 401 rather
    // than tools that are absent. `hermitTools: false` — an ordinary cron fire,
    // whose session id has no ChatSession row for these tools to act on — drops
    // both. See RuntimeSession.hermitTools.
    const hermitTools = session.hermitTools !== false;
    const resume = resumablePiSession(session.id, undefined, { engine: 'omp' });

    const args = [
      ...(hermitTools ? ['--extension', hermitExtensionPath()] : []),
      ...buildModeArgs(mode, { agentDirectory: session.agentDirectory, chatOnly: session.chatOnly }),
      // Pure chat: a read-only subset of omp's 31 built-ins. NOT unioned with
      // hermit's tool names — omp's --tools covers built-ins only and hard-errors
      // on any other name, while leaving extension tools available regardless.
      ...(session.chatOnly ? ['--tools', CHAT_ONLY_OMP_TOOLS.join(',')] : []),
      ...(modelArg ? ['--model', modelArg] : []),
      ...(resume ? ['--resume', resume.piSessionId] : []),
    ];

    // Shared with pi: the HERMIT_PI_* endpoint values for this credential.
    // Resolved into a local first so the child's credential and the fingerprint
    // recorded for it come from one read — two reads could straddle a rotation
    // and record a fingerprint the child never had, which reads as "already
    // stale" on the very next tick.
    const machineEnv = await machineProviderEnv(session.credentialId);

    const transport = new JsonlTransport({
      cliPath: resolveOmpCli(),
      baseArgs: ['--mode', 'rpc'],
      label: 'omp',
      readyType: 'ready',
      cwd: session.agentDirectory,
      args,
      env: {
        ...process.env,
        ...(await providerEnv(session.provider)),
        ...machineEnv,
        ...keyEnv,
        ...(await visionEnv()),
        ...(hermitTools ? {
          HERMIT_DASHBOARD_URL: DASHBOARD_URL,
          HERMIT_KEY: ASST_KEY,
          HERMIT_SESSION_ID: session.id,
        } : {}),
        // Tells the shared hermit extension which backend it is inside. It uses
        // this to skip pi's registerProvider call, which would otherwise
        // override omp's models.yml with a credential omp cannot expand.
        HERMIT_RUNTIME: 'omp-rpc',
      } as Record<string, string>,
      onEvent: (ev) => this.onEvent(session.id, ev),
      onExit: ({ code, signal }) => {
        // Only report a death that we did not ask for. stop() removes the
        // handle first, so a hibernate lands here with nothing to evict.
        if (live.has(session.id)) {
          evict(session.id, `child exited (code=${code ?? 'null'} signal=${signal ?? 'null'})`);
        }
      },
    });

    await transport.start();

    const state = await transport
      .send<{ sessionId?: string; sessionFile?: string }>({ type: 'get_state' })
      .catch(() => null);

    // Loud, because the alternative is a session that quietly answers with none
    // of its own history: we asked to reattach and did not land on it.
    if (resume && state?.sessionId && state.sessionId !== resume.piSessionId) {
      console.warn(
        `[omp] session=${session.id.slice(0, 8)} asked to resume ${resume.piSessionId}`
        + ` but landed on ${state.sessionId}`,
      );
    }

    // Write the pointer down before the first turn, not after: a child that
    // dies mid-answer has still created the session, and the file it left is
    // exactly what the next boot should pick back up.
    if (state?.sessionId) {
      rememberPiSession(session.id, {
        file: state.sessionFile ?? resume?.file ?? '',
        piSessionId: state.sessionId,
        cwd: session.agentDirectory,
        engine: 'omp',
      });
    } else if (pointer) {
      console.warn(`[omp] session=${session.id.slice(0, 8)} booted without a session id; pointer left as-is`);
    }

    const handle: OmpHandle = {
      sessionId: session.id,
      externalSessionId: state?.sessionId ?? session.externalSessionId ?? '',
      transport,
      seen: new Set<string>(),
      ordinal: 0,
      bootId: `${state?.sessionId ?? 'omp'}-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`,
      mode: mode?.name ?? null,
      credentialId: session.credentialId ?? null,
      authFingerprint: fingerprintAuthEnv(machineEnv),
      emit,
      lastTurn: null,
    };
    live.set(session.id, handle);
    return handle;
  }

  /** Translate one child frame into chat rows. */
  private onEvent(sessionId: string, ev: RpcEvent): void {
    const h = live.get(sessionId);
    if (!h) return;
    const raw = ev as { type?: string; message?: { role?: string; usage?: Record<string, number> } };

    if (raw.type === 'message_end' && raw.message?.role === 'assistant' && raw.message.usage) {
      const u = raw.message.usage;
      h.lastTurn = {
        contextTokens: contextTokensFrom(u) ?? 0,
        outputTokens: Number(u.output ?? 0),
      };
    }

    // An extension that throws is reported into the chat rather than swallowed:
    // hermit's own tools live in one, and a silently dead `ask` looks to the
    // user like the agent simply ignoring a question.
    if (raw.type === 'extension_error') {
      const e = ev as { extensionPath?: string; error?: string };
      h.emit(systemItem(
        sessionId,
        `${sessionId}:${h.bootId}-extension-error-${h.ordinal++}`,
        `[omp extension error]\n${String(e.extensionPath ?? '')}: ${String(e.error ?? '')}`.slice(0, 800),
      ));
      return;
    }

    // omp's events carry no durable entry id either, so the same per-boot
    // ordinal scheme as the pi path (see PiHandle.bootId for what an unscoped
    // counter did to session history).
    const externalId = `${sessionId}:${h.bootId}-ord-${h.ordinal}`;
    const items = translatePiEvent(ev, externalId);
    if (items.length === 0) return;
    h.ordinal += 1;
    if (h.seen.has(externalId)) return;
    h.seen.add(externalId);
    for (const item of items) {
      h.emit({ ...item, sessionId, claudeSessionId: null });
    }
  }

  async submit(handle: RuntimeHandle, text: string, images: RuntimeImage[]): Promise<boolean> {
    const h = handleOf(handle);
    if (!h) return false;
    // omp takes images as content parts; the gateway already relays uploads to
    // local paths and injects recognised text, so nothing is passed here yet.
    void images;
    const working = await this.isWorking(handle);
    try {
      await h.transport.send({ type: working ? 'steer' : 'prompt', message: text });
    } catch (e) {
      if (!h.transport.isAlive) {
        evict(h.sessionId, 'child died while submitting');
        return false; // leaves the row un-acked; the next tick respawns and redelivers
      }
      throw e;
    }
    return true;
  }

  async isWorking(handle: RuntimeHandle): Promise<boolean> {
    const h = handleOf(handle);
    if (!h) return false;
    try {
      const st = await h.transport.send<{ isStreaming?: boolean; isCompacting?: boolean }>({ type: 'get_state' });
      return Boolean(st?.isStreaming) || Boolean(st?.isCompacting);
    } catch {
      // Not idle: gone. The transport's exit hook has already evicted.
      return false;
    }
  }

  /** A live RPC child for this session, turn or no turn. */
  async isLive(handle: RuntimeHandle): Promise<boolean> {
    return handleOf(handle) !== null;
  }

  async interrupt(handle: RuntimeHandle): Promise<void> {
    await handleOf(handle)?.transport.send({ type: 'abort' }).catch(() => undefined);
  }

  async compact(handle: RuntimeHandle, instructions?: string): Promise<void> {
    await handleOf(handle)?.transport
      .send({ type: 'compact', ...(instructions ? { customInstructions: instructions } : {}) })
      .catch(() => undefined);
  }

  async usage(handle: RuntimeHandle): Promise<RuntimeUsage | null> {
    const h = handleOf(handle);
    if (!h) return null;
    const stats = await h.transport
      .send<{ tokens?: { input?: number; output?: number; total?: number }; cost?: number }>({ type: 'get_session_stats' })
      .catch(() => null);
    if (!stats?.tokens) return null;
    const input = Number(stats.tokens.input ?? 0);
    const output = Number(stats.tokens.output ?? 0);
    return {
      contextTokens: h.lastTurn?.contextTokens ?? null,
      outputTokens: h.lastTurn?.outputTokens ?? null,
      totalTokens: Number(stats.tokens.total ?? input + output),
      costUsd: typeof stats.cost === 'number' ? stats.cost : null,
    };
  }

  async stop(handle: RuntimeHandle, mode: 'hibernate' | 'kill'): Promise<void> {
    const h = live.get(handle.sessionId);
    if (!h) return;
    // Remove first so the exit hook does not report this as an unexpected death.
    live.delete(handle.sessionId);
    // Closing stdin lets omp drain and write its session file; SIGKILL does not.
    // Both modes take that path, and the pointer is kept for both on purpose:
    // `kill` here is chat-runner's restart button, not "throw the conversation
    // away", and now that boot reattaches with --resume, a restart that killed
    // the file would be a worse tool than the wedged session it was reached for.
    void mode;
    await drain(h.transport, `session=${handle.sessionId.slice(0, 8)}`);
  }
}
