// omp backend: one `omp --mode rpc` child process per chat session.
//
// omp (oh-my-pi) is a fork of pi with a much larger built-in tool surface —
// ast_edit, lsp, debug, browser, computer, github, memory — where pi keeps four
// tools and expects you to add the rest. Both are offered rather than one
// replacing the other: pi is small and predictable, omp is capable and moves
// fast, and which is right depends on the work.
//
// The wire is OmpTransport (see there for why omp's own client cannot be used).
// Session events are the SAME vocabulary as pi's — `message_end` with
// `{text,thinking,toolCall}` parts, `tool_execution_end` with
// `{toolCallId,toolName,result,isError}` — verified against a live child, so
// translatePiEvent is reused unchanged rather than forked.
//
// See docs/pi-modes-design.md and docs/omp-runtime-design.md.

import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs';
import type {
  AgentRuntime, RuntimeHandle, RuntimeImage, RuntimeSession, RuntimeUsage, SyncItem,
} from './types';
import { translatePiEvent } from './pi-events';
import { singleFlight } from './pi-rpc';
import { resolveMode, buildModeArgs } from './pi-modes';
import { providerEnv, visionEnv, readSecret, machineProviderEnv } from './pi-credentials';
import { getPiConfig, resolveDefaultModel } from '../pi-config';
import { OmpTransport, type OmpEvent } from './omp-transport';
import { DASHBOARD_URL, ASST_KEY } from '../config';

/** The hermit tools extension, loaded into every omp child with --extension. */
function hermitExtensionPath(): string {
  return new URL('./hermit-pi-extension.ts', import.meta.url).pathname;
}

/**
 * Where omp lives. Installed with `bun install -g`, so it is not resolvable
 * from this package's node_modules — and deliberately not a dependency, since
 * pulling omp's 36MB (and its Bun requirement) into the gateway's install for a
 * backend most machines will not use is not a trade worth making.
 */
function resolveOmpCli(): string {
  const explicit = process.env.HERMIT_OMP_CLI?.trim();
  const candidates = [
    ...(explicit ? [explicit] : []),
    path.join(os.homedir(), '.bun', 'install', 'global', 'node_modules',
      '@oh-my-pi', 'pi-coding-agent', 'dist', 'cli.js'),
  ];
  const hit = candidates.find((p) => fs.existsSync(p));
  if (!hit) {
    throw new Error(
      'omp is not installed on this machine. Install it with '
      + '`bun install -g @oh-my-pi/pi-coding-agent` (needs Bun >= 1.3.14), '
      + 'or set HERMIT_OMP_CLI to its cli.js.',
    );
  }
  return hit;
}

/** Marker line proving a models.yml is ours to rewrite. */
const GENERATED_MARKER = '# generated by hermit gateway — edits below are overwritten';

/**
 * System prompt used under the Claude subscription, in place of the engine's
 * own. Deliberately carries no harness identity — see where it is passed.
 * Kept in step with ensureCleanSystemPrompt() in pi-credentials.ts, which does
 * the same job for pi by writing ~/.pi/agent/SYSTEM.md.
 */
const CLEAN_SYSTEM_PROMPT = [
  'You are an expert coding assistant. You help users by reading files, executing commands, editing code, and writing new files.',
  '',
  'Guidelines:',
  '- Be concise in your responses',
  '- Show file paths clearly when working with files',
].join('\n');

/**
 * Keep omp's provider config in step with Settings → Pi Runtime.
 *
 * omp resolves providers from `~/.omp/agent/models.yml`, so without this a
 * machine that has omp installed still cannot reach the endpoint the dashboard
 * says it uses — the failure being a 401 at first turn, long after the point
 * where it could be understood. Generating it from piConfig keeps one source of
 * truth instead of two that drift.
 *
 * `apiKey` is written as the NAME of an environment variable, which is what omp
 * expects and what lets the value stay out of the file; boot() injects it.
 *
 * A file without our marker was written by a human and is left alone.
 */
function ensureOmpModelsYaml(cfg: {
  provider?: string; baseUrl?: string; api?: string; models?: string[]; secretKey?: string | null;
}): void {
  const provider = cfg.provider?.trim();
  const baseUrl = cfg.baseUrl?.trim();
  if (!provider || !baseUrl) return;

  const dir = path.join(os.homedir(), '.omp', 'agent');
  const file = path.join(dir, 'models.yml');
  if (fs.existsSync(file)) {
    const existing = fs.readFileSync(file, 'utf8');
    if (!existing.includes(GENERATED_MARKER)) return; // hand-written; not ours
  }

  const q = (s: string) => JSON.stringify(s); // YAML accepts JSON double-quoting
  const models = (cfg.models ?? []).filter(Boolean);
  const lines = [
    GENERATED_MARKER,
    '# Source: the dashboard\'s Settings -> Pi Runtime page (Machine.piConfig).',
    '# apiKey names an environment variable; the gateway injects the value per session.',
    'providers:',
    `  ${provider}:`,
    `    baseUrl: ${q(baseUrl)}`,
    `    api: ${q(cfg.api?.trim() || 'anthropic-messages')}`,
    '    apiKey: HERMIT_PI_API_KEY',
    // LiteLLM-style proxies reject Anthropic's `strict` tool field outright.
    '    disableStrictTools: true',
    ...(models.length
      ? ['    models:', ...models.flatMap((m) => [`      - id: ${q(m)}`, `        name: ${q(m)}`])]
      : []),
    '',
  ];

  const next = lines.join('\n');
  const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (prev === next) return;
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, next);
  console.log(`[omp] wrote ${file} for provider "${provider}"`);
}

type OmpHandle = RuntimeHandle & {
  transport: OmpTransport;
  seen: Set<string>;
  ordinal: number;
  bootId: string;
  /** Mode this child was spawned with; a change means a new child. */
  mode: string | null;
  emit: (item: SyncItem) => void;
  lastTurn: { contextTokens: number; outputTokens: number } | null;
};

const live = new Map<string, OmpHandle>();
const starting = new Map<string, Promise<OmpHandle>>();
const bootFailedUntil = new Map<string, { until: number; error: Error }>();
const BOOT_BACKOFF_MS = 15_000;

function systemItem(sessionId: string, externalId: string, text: string): SyncItem {
  return { sessionId, role: 'system', content: [{ type: 'text', text }], externalId, claudeSessionId: null };
}

function handleOf(h: RuntimeHandle): OmpHandle | null {
  return live.get(h.sessionId) ?? null;
}

/** Same basis as the claude path's contextTokens: what was sent for this turn. */
function contextTokensFrom(u: Record<string, number> | undefined): number | null {
  if (!u) return null;
  const n = (v: unknown) => (typeof v === 'number' ? v : 0);
  const total = n(u.input) + n(u.cacheRead) + n(u.cacheWrite);
  return total > 0 ? total : null;
}

function evict(sessionId: string, reason: string): void {
  const h = live.get(sessionId);
  if (!h) return;
  live.delete(sessionId);
  h.transport.kill();
  console.warn(`[omp] evicted session=${sessionId.slice(0, 8)}: ${reason}`);
  h.emit(systemItem(
    sessionId,
    `${sessionId}:${h.bootId}-exit`,
    `[omp session ended — ${reason}]\nThe next message starts a fresh omp session, which will not carry this conversation's context.`,
  ));
}

export class OmpRpcRuntime implements AgentRuntime {
  readonly kind = 'omp-rpc' as const;

  async ensure(session: RuntimeSession, emit: (item: SyncItem) => void): Promise<RuntimeHandle> {
    const existing = live.get(session.id);
    if (existing) {
      if (!existing.transport.isAlive) {
        evict(session.id, 'child is gone');
      } else {
        const wanted = resolveMode(session.mode)?.name ?? null;
        if (wanted !== existing.mode) {
          evict(session.id, `mode changed ${existing.mode ?? 'none'} → ${wanted ?? 'none'}`);
        } else {
          return existing;
        }
      }
    }

    const cooling = bootFailedUntil.get(session.id);
    if (cooling && Date.now() < cooling.until) throw cooling.error;

    return singleFlight(starting, session.id, () =>
      this.boot(session, emit)
        .then((handle) => {
          live.set(session.id, handle);
          bootFailedUntil.delete(session.id);
          return handle;
        })
        .catch((e: unknown) => {
          const error = e instanceof Error ? e : new Error(String(e));
          if (!cooling) {
            console.error(`[omp] boot failed for session=${session.id.slice(0, 8)}:`, error.message);
            emit(systemItem(
              session.id,
              `${session.id}:boot-failed-${Date.now()}`,
              `[omp could not start]\n${error.message.slice(0, 800)}`,
            ));
          }
          bootFailedUntil.set(session.id, { until: Date.now() + BOOT_BACKOFF_MS, error });
          throw error;
        }),
    );
  }

  private async boot(session: RuntimeSession, emit: (item: SyncItem) => void): Promise<OmpHandle> {
    const mode = resolveMode(session.mode);
    const cfg = await getPiConfig();

    // One auth configuration serves both engines — the same Settings → Pi
    // Runtime page, the same two modes. machineProviderEnv() returns the
    // Claude Code Keychain OAuth token under 'cc-subscription' and the
    // HERMIT_PI_* endpoint values under 'api-key'; only the latter needs a
    // models.yml, because 'anthropic' is a built-in provider on both engines.
    const subscription = cfg.authMode === 'cc-subscription';
    if (!subscription) ensureOmpModelsYaml(cfg);

    const model = session.model ?? mode?.model ?? resolveDefaultModel(cfg);
    // Under the subscription the provider is fixed: the OAuth token only works
    // against Anthropic's own endpoint, whatever the machine's API-key config
    // happens to name.
    const provider = subscription ? 'anthropic' : session.provider ?? cfg.provider;

    // omp resolves a provider from ~/.omp/agent/models.yml rather than from a
    // registerProvider call in an extension — the hack pi needed because it had
    // no way to name a base URL. So `--model provider/id` is the whole wiring,
    // and the hermit extension carries only hermit's tools here.
    const modelArg = model && provider && !model.includes('/') ? `${provider}/${model}` : model;

    // The key for that models.yml entry, which names an env var rather than
    // holding a value. Resolved per boot and handed to the child only.
    const keyEnv: Record<string, string> = {};
    if (!subscription) {
      const secretName = cfg.secretKey?.trim();
      if (secretName) {
        const value = await readSecret(secretName);
        if (value) keyEnv.HERMIT_PI_API_KEY = value;
      }
    }

    const args = [
      '--extension', hermitExtensionPath(),
      ...buildModeArgs(mode, { agentDirectory: session.agentDirectory }),
      ...(modelArg ? ['--model', modelArg] : []),
      // Anthropic's classifier reads the system prompt: a third-party harness
      // identity in it ("operating inside pi", and omp's own equivalent) makes
      // the request fall out of the subscription plan and into extra usage —
      // measured on the pi side, and omp announces itself the same way. So
      // under the subscription the harness identity is replaced outright. Modes
      // still append their own text after it.
      ...(subscription ? ['--system-prompt', CLEAN_SYSTEM_PROMPT] : []),
    ];

    const transport = new OmpTransport({
      cliPath: resolveOmpCli(),
      cwd: session.agentDirectory,
      args,
      env: {
        ...process.env,
        ...(await providerEnv(session.provider)),
        // Shared with pi: returns the Keychain OAuth token under the
        // subscription, or the HERMIT_PI_* endpoint values under api-key.
        ...(await machineProviderEnv()),
        ...keyEnv,
        ...(await visionEnv()),
        HERMIT_DASHBOARD_URL: DASHBOARD_URL,
        HERMIT_KEY: ASST_KEY,
        HERMIT_SESSION_ID: session.id,
        // Tells the shared hermit extension which backend it is inside. It uses
        // this to skip pi's registerProvider call, which would otherwise
        // override omp's models.yml with a credential omp cannot expand.
        HERMIT_RUNTIME: 'omp-rpc',
      } as Record<string, string>,
      onEvent: (ev) => this.onEvent(session.id, ev),
      onExit: ({ code, signal }) => {
        // Only report a death that we did not ask for. stop() removes the
        // handle first, so a hibernate lands here with nothing to evict.
        if (live.has(session.id)) {
          evict(session.id, `child exited (code=${code ?? 'null'} signal=${signal ?? 'null'})`);
        }
      },
    });

    await transport.start();

    const state = await transport.send<{ sessionId?: string }>({ type: 'get_state' }).catch(() => null);

    const handle: OmpHandle = {
      sessionId: session.id,
      externalSessionId: state?.sessionId ?? session.externalSessionId ?? '',
      transport,
      seen: new Set<string>(),
      ordinal: 0,
      bootId: `${state?.sessionId ?? 'omp'}-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`,
      mode: mode?.name ?? null,
      emit,
      lastTurn: null,
    };
    live.set(session.id, handle);
    return handle;
  }

  /** Translate one child frame into chat rows. */
  private onEvent(sessionId: string, ev: OmpEvent): void {
    const h = live.get(sessionId);
    if (!h) return;
    const raw = ev as { type?: string; message?: { role?: string; usage?: Record<string, number> } };

    if (raw.type === 'message_end' && raw.message?.role === 'assistant' && raw.message.usage) {
      const u = raw.message.usage;
      h.lastTurn = {
        contextTokens: contextTokensFrom(u) ?? 0,
        outputTokens: Number(u.output ?? 0),
      };
    }

    // An extension that throws is reported into the chat rather than swallowed:
    // hermit's own tools live in one, and a silently dead `ask` looks to the
    // user like the agent simply ignoring a question.
    if (raw.type === 'extension_error') {
      const e = ev as { extensionPath?: string; error?: string };
      h.emit(systemItem(
        sessionId,
        `${sessionId}:${h.bootId}-extension-error-${h.ordinal++}`,
        `[omp extension error]\n${String(e.extensionPath ?? '')}: ${String(e.error ?? '')}`.slice(0, 800),
      ));
      return;
    }

    // omp's events carry no durable entry id either, so the same per-boot
    // ordinal scheme as the pi path (see PiHandle.bootId for what an unscoped
    // counter did to session history).
    const externalId = `${sessionId}:${h.bootId}-ord-${h.ordinal}`;
    const items = translatePiEvent(ev, externalId);
    if (items.length === 0) return;
    h.ordinal += 1;
    if (h.seen.has(externalId)) return;
    h.seen.add(externalId);
    for (const item of items) {
      h.emit({ ...item, sessionId, claudeSessionId: null });
    }
  }

  async submit(handle: RuntimeHandle, text: string, images: RuntimeImage[]): Promise<boolean> {
    const h = handleOf(handle);
    if (!h) return false;
    // omp takes images as content parts; the gateway already relays uploads to
    // local paths and injects recognised text, so nothing is passed here yet.
    void images;
    const working = await this.isWorking(handle);
    try {
      await h.transport.send({ type: working ? 'steer' : 'prompt', message: text });
    } catch (e) {
      if (!h.transport.isAlive) {
        evict(h.sessionId, 'child died while submitting');
        return false; // leaves the row un-acked; the next tick respawns and redelivers
      }
      throw e;
    }
    return true;
  }

  async isWorking(handle: RuntimeHandle): Promise<boolean> {
    const h = handleOf(handle);
    if (!h) return false;
    try {
      const st = await h.transport.send<{ isStreaming?: boolean; isCompacting?: boolean }>({ type: 'get_state' });
      return Boolean(st?.isStreaming) || Boolean(st?.isCompacting);
    } catch {
      // Not idle: gone. The transport's exit hook has already evicted.
      return false;
    }
  }

  async interrupt(handle: RuntimeHandle): Promise<void> {
    await handleOf(handle)?.transport.send({ type: 'abort' }).catch(() => undefined);
  }

  async compact(handle: RuntimeHandle, instructions?: string): Promise<void> {
    await handleOf(handle)?.transport
      .send({ type: 'compact', ...(instructions ? { customInstructions: instructions } : {}) })
      .catch(() => undefined);
  }

  async usage(handle: RuntimeHandle): Promise<RuntimeUsage | null> {
    const h = handleOf(handle);
    if (!h) return null;
    const stats = await h.transport
      .send<{ tokens?: { input?: number; output?: number; total?: number }; cost?: number }>({ type: 'get_session_stats' })
      .catch(() => null);
    if (!stats?.tokens) return null;
    const input = Number(stats.tokens.input ?? 0);
    const output = Number(stats.tokens.output ?? 0);
    return {
      contextTokens: h.lastTurn?.contextTokens ?? null,
      outputTokens: h.lastTurn?.outputTokens ?? null,
      totalTokens: Number(stats.tokens.total ?? input + output),
      costUsd: typeof stats.cost === 'number' ? stats.cost : null,
    };
  }

  async stop(handle: RuntimeHandle, mode: 'hibernate' | 'kill'): Promise<void> {
    const h = live.get(handle.sessionId);
    if (!h) return;
    // Remove first so the exit hook does not report this as an unexpected death.
    live.delete(handle.sessionId);
    if (mode === 'hibernate') {
      // Closing stdin lets omp drain and write its session file; SIGKILL does not.
      h.transport.end();
      setTimeout(() => { if (h.transport.isAlive) h.transport.kill(); }, 5_000).unref();
    } else {
      h.transport.kill();
    }
  }
}
