// /api/upload — composer image upload endpoint.
//
// Accepts multipart/form-data with fields:
//   sessionId   <string>   ChatSession id (must belong to the auth machine)
//   file        <Blob>     image/{png,jpg,jpeg,gif,webp} or an allowed file type, ≤200 MB
//
// Saves the original at `<UPLOAD_DIR>/<sessionId>/<uuid>.<ext>` and a safe
// sidecar (long-edge ≤2000px) at `<uuid>.safe.<ext>`. Returns the SAFE url
// — the gateway will hand that path to claude via tmux send-keys, and the
// dashboard markdown renderer references it inline. Reading a >2000px
// image wedges the model session (see evolution/lessons.md L4), so callers
// MUST consume the .safe.* path.
//
// `HERMIT_UPLOAD_DIR` overrides the default. Default depends on platform:
//   macOS dev:   /tmp/hermit-ui/uploads
//   Linux prod:  /var/hermit-ui/uploads  (deploy.sh creates with mode 0755
//                                          owned by the next process user)
//
// The matching GET handler that serves the files lives in /api/upload/[...path]
// — added in the next iteration alongside the composer wiring.

import { NextRequest, NextResponse } from 'next/server';
import { mkdir, writeFile, stat, unlink } from 'node:fs/promises';
import { join, extname, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { platform } from 'node:os';
import { prisma } from '@/server/db';
import { resolveKey } from '@/server/auth';
import { makeThumb } from '@/server/image-thumb';
import { THUMB_SUFFIX } from '@/lib/thumb-url';
import { SAFE_FILE_EXT_SET } from '@/components/chat/attach-core';

// Upload size ceiling for ALL file types (image / doc / archive / audio / video
// alike). This route buffers the whole upload in memory before writing it to disk,
// so this is a deliberate cap — 200 MB is comfortable on the deploy box (15 GB RAM,
// ~11 GB free) and there's no proxy-level body limit in front of it.
const MAX_BYTES = 200 * 1024 * 1024;
const SAFE_LONG_EDGE = 2000;
const ALLOWED_MIME = new Set([
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/webp',
]);
const EXT_BY_MIME: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/gif': 'gif',
  'image/webp': 'webp',
};

// Non-image extensions we accept — the SAME set the composer filters with,
// imported rather than copied. This route is the trust boundary; the client
// check is only there to save a useless roundtrip. Archives are allowed (stored
// as-is) — the gateway hands the agent an "extract via Bash" instruction rather
// than Read'ing them.
//
// It used to be a second literal list here with a comment on each copy asking
// the reader to keep the two in step. They were in step, and nothing would have
// noticed if they stopped being.

function uploadRoot(): string {
  const fromEnv = process.env.HERMIT_UPLOAD_DIR;
  if (fromEnv) return fromEnv;
  return platform() === 'linux' ? '/var/hermit-ui/uploads' : '/tmp/hermit-ui/uploads';
}

// Hardened path join: refuse anything that resolves outside the upload root
// after symlink-free path resolution. Defense-in-depth even though sessionId
// is generated by us (cuid).
function safeJoin(root: string, ...parts: string[]): string | null {
  const joined = resolve(root, ...parts);
  const rootResolved = resolve(root);
  if (joined !== rootResolved && !joined.startsWith(rootResolved + sep)) return null;
  return joined;
}

// Sanitize a user filename's extension → short alnum token, else "bin".
function safeExtFromName(name: string): string {
  const e = extname(name).replace(/^\./, '').toLowerCase();
  return /^[a-z0-9]{1,8}$/.test(e) ? e : 'bin';
}

function which(bin: string): string | null {
  const r = spawnSync('which', [bin], { encoding: 'utf8' });
  return r.status === 0 ? r.stdout.trim() : null;
}

interface Dims { width: number; height: number }

function imageDims(filePath: string): Dims | null {
  // sips on macOS, identify on Linux. Both report pixel dimensions; we use
  // whichever is available first.
  if (which('sips')) {
    const r = spawnSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', filePath], { encoding: 'utf8', timeout: 4_000 });
    if (r.status === 0) {
      const w = r.stdout.match(/pixelWidth:\s*(\d+)/);
      const h = r.stdout.match(/pixelHeight:\s*(\d+)/);
      if (w && h) return { width: Number(w[1]), height: Number(h[1]) };
    }
  }
  if (which('identify')) {
    const r = spawnSync('identify', ['-format', '%w %h', filePath], { encoding: 'utf8', timeout: 4_000 });
    if (r.status === 0) {
      const m = r.stdout.trim().match(/^(\d+)\s+(\d+)/);
      if (m) return { width: Number(m[1]), height: Number(m[2]) };
    }
  }
  return null;
}

// Resize so the long edge is ≤ SAFE_LONG_EDGE. Writes to outPath. Returns
// true on success. If neither sips nor convert is available we still want
// the upload to succeed — we just write the original to outPath as-is and
// let the caller flag width/height for any downstream guard.
function resizeSafe(inPath: string, outPath: string): boolean {
  if (which('sips')) {
    const r = spawnSync(
      'sips',
      ['-Z', String(SAFE_LONG_EDGE), inPath, '--out', outPath],
      { encoding: 'utf8', timeout: 12_000 },
    );
    return r.status === 0;
  }
  if (which('convert')) {
    // imagemagick: `>` only resizes if larger.
    const r = spawnSync(
      'convert',
      [inPath, '-resize', `${SAFE_LONG_EDGE}x${SAFE_LONG_EDGE}>`, outPath],
      { encoding: 'utf8', timeout: 12_000 },
    );
    return r.status === 0;
  }
  return false;
}

export async function POST(req: NextRequest) {
  // resolveKey accepts a machine key OR an agent share token; a scoped token can
  // only attach to ITS agent's session (enforced in the session lookup below).
  const scope = await resolveKey(req.headers.get('x-asst-key') ?? '');
  if (!scope) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  const machine = scope.machine;

  let form: FormData;
  try {
    form = await req.formData();
  } catch (e) {
    return NextResponse.json({ error: 'bad form data', detail: String(e) }, { status: 400 });
  }

  const sessionId = (form.get('sessionId') as string | null)?.trim();
  const file = form.get('file');
  if (!sessionId) return NextResponse.json({ error: 'sessionId required' }, { status: 400 });
  if (!(file instanceof Blob)) return NextResponse.json({ error: 'file blob required' }, { status: 400 });
  if (file.size === 0) return NextResponse.json({ error: 'empty file' }, { status: 400 });
  if (file.size > MAX_BYTES) return NextResponse.json({ error: `file too large (>${MAX_BYTES} bytes)` }, { status: 413 });

  const mime = (file.type || '').toLowerCase();
  const isImage = ALLOWED_MIME.has(mime);

  // Confirm the session belongs to this machine (and, for a scoped share key, to
  // its agent) — prevents cross-tenant / cross-agent writes.
  const session = await prisma.chatSession.findFirst({
    where: { id: sessionId, machineId: machine.id, ...(scope.scopedAgent ? { agentName: scope.scopedAgent } : {}) },
    select: { id: true },
  });
  if (!session) return NextResponse.json({ error: 'session not found' }, { status: 404 });

  const root = uploadRoot();
  const dir = safeJoin(root, sessionId);
  if (!dir) return NextResponse.json({ error: 'invalid sessionId' }, { status: 400 });
  await mkdir(dir, { recursive: true });

  const uuid = randomUUID();
  const bytes = Buffer.from(await file.arrayBuffer());

  // ── Images: a ≤2000px ".safe." copy, plus a 640px thumbnail. Reading an
  // oversized image wedges the model session (see evolution/lessons.md L4), so
  // ".safe." is what every url points at.
  //
  // The full-size original used to be kept beside it, reachable as `originalUrl`
  // — which nothing in this repo, the gateway, or the iOS app ever read. On the
  // deploy box that was 4,747 files and 8.4 GB, against 1.7 GB of files anyone
  // could actually reach. It is now scratch: written only as the resizer's
  // input, deleted as soon as the ".safe." copy exists.
  if (isImage) {
    const ext = EXT_BY_MIME[mime];
    const srcPath = join(dir, `${uuid}.src.${ext}`);
    const safePath = join(dir, `${uuid}.safe.${ext}`);
    await writeFile(srcPath, bytes, { mode: 0o644 });
    const resized = resizeSafe(srcPath, safePath);
    if (!resized) {
      // sips/convert absent or failed: byte-for-byte copy so the url resolves.
      await writeFile(safePath, bytes, { mode: 0o644 });
    }
    const dims = imageDims(safePath) ?? imageDims(srcPath);
    await unlink(srcPath).catch(() => {});
    const safeStatRes = await stat(safePath).catch(() => null);
    // A 640px WebP for the 320px chat box. Best-effort: `thumbUrl` is null when
    // the encoder isn't there or the source is a GIF, and the client then keeps
    // pointing at the .safe. url exactly as it used to.
    const thumbable = ext !== 'gif';
    const thumbPath = join(dir, `${uuid}${THUMB_SUFFIX}`);
    const hasThumb = thumbable && makeThumb(safePath, thumbPath);
    return NextResponse.json({
      ok: true,
      kind: 'image',
      url: `/uploads/${sessionId}/${uuid}.safe.${ext}`,
      // Kept in the response shape so an older gateway reading it sees a field
      // rather than a missing key; there is no full-size original any more.
      originalUrl: null,
      thumbUrl: hasThumb ? `/uploads/${sessionId}/${uuid}${THUMB_SUFFIX}` : null,
      mimeType: mime,
      width: dims?.width ?? null,
      height: dims?.height ?? null,
      bytes: safeStatRes?.size ?? bytes.length,
      resized,
    });
  }

  // ── Other files: store as-is (no resize). The gateway relay downloads them
  // onto the Mac and hands claude a `Read <path>` so the agent can consume the
  // contents (text/code/pdf/etc). No ".safe." marker — relay handles non-images.
  const fname = (file as File).name || '';
  // Allowlist check: reject anything not on SAFE_FILE_EXT_SET before writing
  // to disk. Defense-in-depth (the client already filters, but the server is
  // the trust boundary).
  const rawExt = extname(fname).replace(/^\./, '').toLowerCase();
  if (!SAFE_FILE_EXT_SET.has(rawExt)) {
    return NextResponse.json(
      { error: `unsupported file type${rawExt ? ` (.${rawExt})` : ''}` },
      { status: 415 },
    );
  }
  const ext = safeExtFromName(fname);
  const filePath = join(dir, `${uuid}.${ext}`);
  await writeFile(filePath, bytes, { mode: 0o644 });
  return NextResponse.json({
    ok: true,
    kind: 'file',
    url: `/uploads/${sessionId}/${uuid}.${ext}`,
    mimeType: mime || 'application/octet-stream',
    name: fname || `${uuid}.${ext}`,
    width: null,
    height: null,
    bytes: bytes.length,
  });
}
