// /api/upload — composer image upload endpoint.
//
// Accepts multipart/form-data with fields:
//   sessionId   <string>   ChatSession id (must belong to the auth machine)
//   file        <Blob>     image/{png,jpg,jpeg,gif,webp}, ≤25 MB
//
// Saves the original at `<UPLOAD_DIR>/<sessionId>/<uuid>.<ext>` and a safe
// sidecar (long-edge ≤2000px) at `<uuid>.safe.<ext>`. Returns the SAFE url
// — the gateway will hand that path to claude via tmux send-keys, and the
// dashboard markdown renderer references it inline. Reading a >2000px
// image wedges the model session (see evolution/lessons.md L4), so callers
// MUST consume the .safe.* path.
//
// `HERMIT_UPLOAD_DIR` overrides the default. Default depends on platform:
//   macOS dev:   /tmp/hermit-ui/uploads
//   Linux prod:  /var/hermit-ui/uploads  (deploy.sh creates with mode 0755
//                                          owned by the next process user)
//
// The matching GET handler that serves the files lives in /api/upload/[...path]
// — added in the next iteration alongside the composer wiring.

import { NextRequest, NextResponse } from 'next/server';
import { mkdir, writeFile, stat } from 'node:fs/promises';
import { join, extname, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { platform } from 'node:os';
import { prisma } from '@/server/db';
import { resolveMachine } from '../sync/route';

const MAX_BYTES = 25 * 1024 * 1024;
const SAFE_LONG_EDGE = 2000;
const ALLOWED_MIME = new Set([
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/webp',
]);
const EXT_BY_MIME: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/gif': 'gif',
  'image/webp': 'webp',
};

// Non-image extensions we accept. Mirrors `SAFE_FILE_EXTS` on the client.
// Anything outside → 415; keeps loose binaries / executables out. Archives are
// allowed (stored as-is) — the gateway hands the agent an "extract via Bash"
// instruction rather than Read'ing them.
const SAFE_FILE_EXT_SET = new Set<string>([
  'txt','md','markdown','rtf','log','pdf',
  'json','yaml','yml','toml','ini','conf','env','xml','html','svg','csv','tsv','sql',
  'ts','tsx','js','jsx','mjs','cjs','py','rb','php','go','rs',
  'c','cpp','cc','cxx','h','hpp','java','kt','swift','scala','clj','ex','exs',
  'sh','bash','zsh','fish','ps1','dart','lua','r',
  // archives — extracted by the agent via Bash (see image-relay / chat-runner)
  'zip','tar','gz','tgz','bz2','tbz2','xz','txz','7z','rar','zst',
  // office docs — binary; the gateway relay hands the agent a "convert via Bash"
  // instruction (textutil / python+pandas / unzip), never a raw Read.
  'docx','xlsx','pptx','doc','xls','ppt','odt','ods','odp',
]);

function uploadRoot(): string {
  const fromEnv = process.env.HERMIT_UPLOAD_DIR;
  if (fromEnv) return fromEnv;
  return platform() === 'linux' ? '/var/hermit-ui/uploads' : '/tmp/hermit-ui/uploads';
}

// Hardened path join: refuse anything that resolves outside the upload root
// after symlink-free path resolution. Defense-in-depth even though sessionId
// is generated by us (cuid).
function safeJoin(root: string, ...parts: string[]): string | null {
  const joined = resolve(root, ...parts);
  const rootResolved = resolve(root);
  if (joined !== rootResolved && !joined.startsWith(rootResolved + sep)) return null;
  return joined;
}

// Sanitize a user filename's extension → short alnum token, else "bin".
function safeExtFromName(name: string): string {
  const e = extname(name).replace(/^\./, '').toLowerCase();
  return /^[a-z0-9]{1,8}$/.test(e) ? e : 'bin';
}

function which(bin: string): string | null {
  const r = spawnSync('which', [bin], { encoding: 'utf8' });
  return r.status === 0 ? r.stdout.trim() : null;
}

interface Dims { width: number; height: number }

function imageDims(filePath: string): Dims | null {
  // sips on macOS, identify on Linux. Both report pixel dimensions; we use
  // whichever is available first.
  if (which('sips')) {
    const r = spawnSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', filePath], { encoding: 'utf8', timeout: 4_000 });
    if (r.status === 0) {
      const w = r.stdout.match(/pixelWidth:\s*(\d+)/);
      const h = r.stdout.match(/pixelHeight:\s*(\d+)/);
      if (w && h) return { width: Number(w[1]), height: Number(h[1]) };
    }
  }
  if (which('identify')) {
    const r = spawnSync('identify', ['-format', '%w %h', filePath], { encoding: 'utf8', timeout: 4_000 });
    if (r.status === 0) {
      const m = r.stdout.trim().match(/^(\d+)\s+(\d+)/);
      if (m) return { width: Number(m[1]), height: Number(m[2]) };
    }
  }
  return null;
}

// Resize so the long edge is ≤ SAFE_LONG_EDGE. Writes to outPath. Returns
// true on success. If neither sips nor convert is available we still want
// the upload to succeed — we just write the original to outPath as-is and
// let the caller flag width/height for any downstream guard.
function resizeSafe(inPath: string, outPath: string): boolean {
  if (which('sips')) {
    const r = spawnSync(
      'sips',
      ['-Z', String(SAFE_LONG_EDGE), inPath, '--out', outPath],
      { encoding: 'utf8', timeout: 12_000 },
    );
    return r.status === 0;
  }
  if (which('convert')) {
    // imagemagick: `>` only resizes if larger.
    const r = spawnSync(
      'convert',
      [inPath, '-resize', `${SAFE_LONG_EDGE}x${SAFE_LONG_EDGE}>`, outPath],
      { encoding: 'utf8', timeout: 12_000 },
    );
    return r.status === 0;
  }
  return false;
}

export async function POST(req: NextRequest) {
  const machine = await resolveMachine(req);
  if (!machine) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });

  let form: FormData;
  try {
    form = await req.formData();
  } catch (e) {
    return NextResponse.json({ error: 'bad form data', detail: String(e) }, { status: 400 });
  }

  const sessionId = (form.get('sessionId') as string | null)?.trim();
  const file = form.get('file');
  if (!sessionId) return NextResponse.json({ error: 'sessionId required' }, { status: 400 });
  if (!(file instanceof Blob)) return NextResponse.json({ error: 'file blob required' }, { status: 400 });
  if (file.size === 0) return NextResponse.json({ error: 'empty file' }, { status: 400 });
  if (file.size > MAX_BYTES) return NextResponse.json({ error: `file too large (>${MAX_BYTES} bytes)` }, { status: 413 });

  const mime = (file.type || '').toLowerCase();
  const isImage = ALLOWED_MIME.has(mime);

  // Confirm the session belongs to this machine — prevents cross-tenant writes.
  const session = await prisma.chatSession.findFirst({
    where: { id: sessionId, machineId: machine.id },
    select: { id: true },
  });
  if (!session) return NextResponse.json({ error: 'session not found' }, { status: 404 });

  const root = uploadRoot();
  const dir = safeJoin(root, sessionId);
  if (!dir) return NextResponse.json({ error: 'invalid sessionId' }, { status: 400 });
  await mkdir(dir, { recursive: true });

  const uuid = randomUUID();
  const bytes = Buffer.from(await file.arrayBuffer());

  // ── Images: keep the original + a ≤2000px ".safe." sidecar. Both the gateway
  // relay and the inline thumbnail consume the .safe. url; reading an oversized
  // image wedges the model session (see evolution/lessons.md L4). ──
  if (isImage) {
    const ext = EXT_BY_MIME[mime];
    const origPath = join(dir, `${uuid}.${ext}`);
    const safePath = join(dir, `${uuid}.safe.${ext}`);
    await writeFile(origPath, bytes, { mode: 0o644 });
    const resized = resizeSafe(origPath, safePath);
    if (!resized) {
      // sips/convert absent or failed: byte-for-byte copy so the url resolves.
      await writeFile(safePath, bytes, { mode: 0o644 });
    }
    const safeStatRes = await stat(safePath).catch(() => null);
    const dims = imageDims(safePath) ?? imageDims(origPath);
    return NextResponse.json({
      ok: true,
      kind: 'image',
      url: `/uploads/${sessionId}/${uuid}.safe.${ext}`,
      originalUrl: `/uploads/${sessionId}/${uuid}.${ext}`,
      mimeType: mime,
      width: dims?.width ?? null,
      height: dims?.height ?? null,
      bytes: safeStatRes?.size ?? bytes.length,
      resized,
    });
  }

  // ── Other files: store as-is (no resize). The gateway relay downloads them
  // onto the Mac and hands claude a `Read <path>` so the agent can consume the
  // contents (text/code/pdf/etc). No ".safe." marker — relay handles non-images.
  const fname = (file as File).name || '';
  // Allowlist check: reject anything not on SAFE_FILE_EXT_SET before writing
  // to disk. Defense-in-depth (the client already filters, but the server is
  // the trust boundary).
  const rawExt = extname(fname).replace(/^\./, '').toLowerCase();
  if (!SAFE_FILE_EXT_SET.has(rawExt)) {
    return NextResponse.json(
      { error: `unsupported file type${rawExt ? ` (.${rawExt})` : ''}` },
      { status: 415 },
    );
  }
  const ext = safeExtFromName(fname);
  const filePath = join(dir, `${uuid}.${ext}`);
  await writeFile(filePath, bytes, { mode: 0o644 });
  return NextResponse.json({
    ok: true,
    kind: 'file',
    url: `/uploads/${sessionId}/${uuid}.${ext}`,
    mimeType: mime || 'application/octet-stream',
    name: fname || `${uuid}.${ext}`,
    width: null,
    height: null,
    bytes: bytes.length,
  });
}
