#!/usr/bin/env bash
# Holds the Swift port of the chat header's action cluster against the web's own
# answers. No simulator, no key, no network. About three seconds.
#
#     apps/ios/tools/actions-fixture.sh
#
# The table under test (tools/fixtures/actions-cases.json) is generated by
# RUNNING the dashboard's own `headerActions` / `secondaryFolds` / `confirmStep`:
#
#     pnpm --filter @hermit-ui/dashboard gen:actions-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of the JSX.
#
# Built for the host: everything under test is Foundation only.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-actions-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/actions-fixture" \
  tools/actions-fixture/main.swift \
  Hermit/HeaderActionsCore.swift \
  Hermit/WebLabels.swift \
  Hermit/SessionMeta.swift \
  Hermit/SessionStatus.swift \
  Shared/WebContract.swift \
  Hermit/ContentBlock.swift

"$OUT/actions-fixture" "$PWD"
