#!/usr/bin/env bash
# Holds the Swift port of the `+` button's decisions against the web's own
# answers. No simulator, no key, no network. About two seconds.
#
#     apps/ios/tools/attach-fixture.sh
#
# The table under test (tools/fixtures/attach-cases.json) is generated by
# RUNNING the dashboard's own functions:
#
#     pnpm --filter @hermit-ui/dashboard gen:attach-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# Built for the host: everything under test is Foundation only.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-attach-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/attach-fixture" \
  tools/attach-fixture/main.swift \
  Hermit/AttachCore.swift

"$OUT/attach-fixture" "$PWD"
