#!/usr/bin/env bash
# Holds the Swift port of `parseBlock` / `parseBlocks` against the web's own
# answers. No simulator, no key, no network, no database. About four seconds.
#
#     apps/ios/tools/blocks-fixture.sh
#
# The table under test (tools/fixtures/block-cases.json) is generated by RUNNING
# apps/dashboard/src/lib/chat-blocks.ts:
#
#     pnpm --filter @hermit-ui/dashboard gen:blocks-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# Built for the host: `Hermit/ContentBlock.swift` is Foundation only — no UIKit,
# no SwiftUI — which is also why the timeline can be built on top of it without
# dragging a view layer into every decode.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-blocks-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/blocks-fixture" \
  tools/blocks-fixture/main.swift \
  Hermit/ContentBlock.swift

"$OUT/blocks-fixture" "$PWD"
