#!/usr/bin/env bash
# Drive the web -> native request channel against a real page, with no dashboard,
# no machine key and no network:
#
#   apps/ios/tools/bridge-fixture.sh [test-name ...]
#
# Runs tools/bridge-fixture/server.py over loopback — the fixture page, a
# `chat.listSessions` that answers per key, and one 150-message chat session
# behind `chat.listMessages` / `chat.listMessagesBefore` / `/api/chat/stream` —
# points the shell at it, and runs the UI tests that use it (all of them by
# default). Simulator processes run natively on this Mac, so 127.0.0.1 inside the
# simulator is this Mac's loopback — no port forwarding.
#
# Knobs: HERMIT_SIM_DEVICE  HERMIT_SHOT_DIR  HERMIT_FIXTURE_PORT
#        HERMIT_DERIVED_DATA (also stops the cleanup from deleting it)
set -euo pipefail

cd "$(dirname "$0")/.."

DEVICE="${HERMIT_SIM_DEVICE:-iPhone 17}"
SHOT_DIR="${HERMIT_SHOT_DIR:-$PWD/shots}"
DERIVED="${HERMIT_DERIVED_DATA:-${TMPDIR:-/tmp}/hermit-ios-dd}"
OWNS_DERIVED=$([ -n "${HERMIT_DERIVED_DATA:-}" ] && echo 0 || echo 1)
LOG="${TMPDIR:-/tmp}/hermit-fixture-$$.log"
# NOT 49517: that is the dead address the fixture asks the shell to move to, and
# a server answering on it would turn the offline screen this test waits for into
# a page that loads.
PORT="${HERMIT_FIXTURE_PORT:-49518}"

# Every test that drives the fixture, in the order XCTest would pick anyway.
# Naming one on the command line runs just that one.
TESTS=("$@")
[ ${#TESTS[@]} -gt 0 ] || TESTS=(
  testTheKeychainKeepsTheKeyring
  testTheNativeListDrawsTheActiveMachinesSessions
  testTheNativeListRefreshesItselfWhileYouWatch
  testTheWebAppIsTheFrontDoorAndTheListIsBehindIt
  testThePageCanProposeAnotherServer
  testTheNativeTimelineStreamsAndPagesBack
  testTheNativeComposerSendsAndHandsTheBubbleOver
  testTheChatHeaderCarriesItsActions
  testTheNativeQueueStripShowsAndPullsBack
  testTheNativeComposerAttachesAPhoto
  testTheNativeComposerHoldsTheBoxToTalk
  testTheWholeChatScreenOpensFromATappedRow
)

command -v xcodegen >/dev/null || { echo "need xcodegen: brew install xcodegen" >&2; exit 1; }

DEVICE_INFO=$(xcrun simctl list devices available -j | DEVICE="$DEVICE" python3 -c '
import json, os, sys
name = os.environ["DEVICE"]
for runtime, devices in sorted(json.load(sys.stdin)["devices"].items(), reverse=True):
    for d in devices:
        if d.get("name") == name and d.get("isAvailable"):
            print(d["udid"], d.get("state", ""))
            raise SystemExit
')
[ -n "$DEVICE_INFO" ] || { echo "no available simulator named '$DEVICE'" >&2; exit 1; }
UDID=${DEVICE_INFO%% *}
STATE=${DEVICE_INFO#* }
WE_BOOTED=0
[ "$STATE" = "Booted" ] || WE_BOOTED=1

FIXTURE_PID=""
cleanup() {
  pkill -TERM -P $$ 2>/dev/null || true
  [ -n "$FIXTURE_PID" ] && kill "$FIXTURE_PID" 2>/dev/null || true
  xcrun simctl uninstall "$UDID" ai.swaylab.hermit 2>/dev/null || true
  # A booted simulator costs ~3GB of resident memory on this 16GB machine and
  # spills swap files onto the system disk, so it does not get to outlive the
  # run — see the same trap in smoke.sh. Only a device this script booted.
  if [ "$WE_BOOTED" = "1" ]; then
    xcrun simctl shutdown "$UDID" 2>/dev/null || true
    xcrun simctl erase "$UDID" 2>/dev/null || true
  fi
  [ "$OWNS_DERIVED" = "1" ] && rm -rf "$DERIVED"
  rm -f "$LOG"
  return 0
}
trap cleanup EXIT
trap 'exit 143' INT TERM HUP

mkdir -p "$SHOT_DIR"
xcodegen generate >/dev/null

echo "==> serving tools/bridge-fixture on 127.0.0.1:$PORT"
# Its own server, not `python3 -m http.server`: the native session list needs a
# `chat.listSessions` to draw, and that route answers differently per key. stderr
# is deliberately NOT redirected — a traceback inside a request handler is the
# only warning that the fixture, rather than the app, is what broke.
python3 tools/bridge-fixture/server.py "$PORT" >/dev/null &
FIXTURE_PID=$!
# Fail here rather than 30 seconds into a UI test that reports "the fixture page
# never loaded" and cannot say why.
for _ in $(seq 1 20); do
  curl -fs -o /dev/null "http://127.0.0.1:$PORT/" && break   # -S only on the last try below
  sleep 0.25
done
curl -fsS -o /dev/null "http://127.0.0.1:$PORT/" || { echo "the fixture server never came up on $PORT" >&2; exit 1; }

xcrun simctl boot "$UDID" 2>/dev/null || true
xcrun simctl uninstall "$UDID" ai.swaylab.hermit 2>/dev/null || true

# One photo in the library, so the `+` has something to pick. A fresh simulator
# has an EMPTY photo library — the stock sample images stopped shipping years
# ago — and PHPicker with nothing in it is a screen the test cannot get past.
# Written here rather than committed: 96 bytes of PNG generated by the same
# python already in this script is cheaper to read than a binary in git.
PHOTO="${TMPDIR:-/tmp}/hermit-fixture-photo.png"
python3 - "$PHOTO" <<'PYEOF'
import struct, sys, zlib
w = h = 24
rows = b''.join(b'\x00' + bytes([0x2E, 0xA3, 0xC7] * w if y < h // 2 else [0xE8, 0xB3, 0x4A] * w)
                for y in range(h))
def chunk(tag, data):
    body = tag + data
    return struct.pack('>I', len(data)) + body + struct.pack('>I', zlib.crc32(body) & 0xffffffff)
open(sys.argv[1], 'wb').write(
    b'\x89PNG\r\n\x1a\n'
    + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0))
    + chunk(b'IDAT', zlib.compress(rows, 9))
    + chunk(b'IEND', b''))
PYEOF
xcrun simctl addmedia "$UDID" "$PHOTO" 2>/dev/null || echo "==> could not add a photo to the library (the attach test will skip)" >&2

# The microphone, granted from here rather than by tapping the alert. The
# press-and-hold asks for it on RELEASE precisely because an alert raised under a
# held finger swallows the touch and the release never arrives — a test that
# answered that alert would be testing the alert. Granted after the install, and
# it survives the app being replaced.
xcrun simctl privacy "$UDID" grant microphone ai.swaylab.hermit 2>/dev/null \
  || echo "==> could not grant the microphone (the hold test will see the 授权 screen instead)" >&2

common_args=(
  -project Hermit.xcodeproj
  -scheme Hermit
  -sdk iphonesimulator
  -destination "platform=iOS Simulator,id=$UDID"
  -derivedDataPath "$DERIVED"
  # Ad-hoc signed, NOT unsigned. An unsigned app carries no entitlements, and on
  # the simulator that means no keychain access group: every SecItem call comes
  # back -34018 (errSecMissingEntitlement) and the keyring silently has nowhere
  # to live. `-` needs no team and no provisioning profile.
  CODE_SIGN_IDENTITY=-
  CODE_SIGN_STYLE=Manual
  PROVISIONING_PROFILE_SPECIFIER=
  DEVELOPMENT_TEAM=
)

echo "==> building for '$DEVICE' ($UDID)"
set +e
# Backgrounded and waited on: bash defers a trap until a FOREGROUND child exits,
# so a Ctrl-C during the build would otherwise leave the simulator booted.
xcodebuild build-for-testing "${common_args[@]}" > "$LOG" 2>&1 &
wait $!
status=$?
set -e
if [ "$status" -ne 0 ]; then
  echo "==> BUILD FAILED (exit $status)"
  grep -E "error:" "$LOG" | head -20 || true
  exit "$status"
fi

echo "==> running ${TESTS[*]}"
export TEST_RUNNER_HERMIT_BRIDGE_ORIGIN="http://127.0.0.1:$PORT"
export TEST_RUNNER_HERMIT_SHOT_DIR="$SHOT_DIR"
only=()
for t in "${TESTS[@]}"; do only+=(-only-testing:"HermitUITests/SmokeTests/$t"); done
set +e
xcodebuild test-without-building "${common_args[@]}" \
  "${only[@]}" >> "$LOG" 2>&1 &
wait $!
status=$?
set -e
tail -20 "$LOG"
if [ "$status" -ne 0 ]; then
  echo "==> TESTS FAILED (exit $status)"
  echo "--- failures ---"
  grep -E "error:|XCTAssert|Assertion Failure|failed - " "$LOG" | head -20 || true
  exit "$status"
fi
echo "==> screenshots in $SHOT_DIR"
