#!/usr/bin/env bash
# Holds the Swift port of the composer's decisions against the web's own answers.
# No simulator, no key, no network. About three seconds.
#
#     apps/ios/tools/composer-fixture.sh
#
# The table under test (tools/fixtures/composer-cases.json) is generated by
# RUNNING the dashboard's own functions:
#
#     pnpm --filter @hermit-ui/dashboard gen:composer-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# Built for the host: everything under test is Foundation only.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-composer-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/composer-fixture" \
  tools/composer-fixture/main.swift \
  Hermit/ComposerCore.swift \
  Hermit/ContentBlock.swift

"$OUT/composer-fixture" "$PWD"
