#!/usr/bin/env bash
# Holds the Swift port of the session detail panel against the web's own
# answers. No simulator, no key, no network. About four seconds.
#
#     apps/ios/tools/detail-fixture.sh
#
# The table under test (tools/fixtures/detail-cases.json) is generated by
# RUNNING the dashboard's own `detailPickerView` / `detailSwitchPrompt` /
# `detailSavePayload` / `detailSections`:
#
#     pnpm --filter @hermit-ui/dashboard gen:detail-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of the JSX.
#
# Built for the host: everything under test is Foundation only.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-detail-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/detail-fixture" \
  tools/detail-fixture/main.swift \
  Hermit/SessionDetailCore.swift \
  Hermit/WebBackends.swift \
  Hermit/WebLabels.swift \
  Hermit/SessionMeta.swift \
  Hermit/SessionListItem.swift \
  Hermit/SessionStatus.swift \
  Hermit/HermitAPI.swift \
  Hermit/ContentBlock.swift \
  Shared/WebContract.swift

"$OUT/detail-fixture" "$PWD"
