#!/usr/bin/env bash
# Holds the Swift port of `foldRuns` against the web's own answers. No simulator,
# no key, no network, no database. A few seconds.
#
#     apps/ios/tools/fold-fixture.sh
#
# The table under test (tools/fixtures/fold-cases.json) is generated by RUNNING
# apps/dashboard/src/components/chat/fold-runs.ts:
#
#     pnpm --filter @hermit-ui/dashboard gen:fold-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# TZ is pinned because `isSameDay` asks the LOCAL calendar on both sides — the
# generator pinned UTC, and the driver refuses to run in anything else.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-fold-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/fold-fixture" \
  tools/fold-fixture/main.swift \
  Hermit/ContentBlock.swift \
  Hermit/FoldRuns.swift

TZ=UTC "$OUT/fold-fixture" "$PWD"
