#!/usr/bin/env bash
# Holds the Swift port of the chat header's vocabulary against the web's own
# answers. No simulator, no key, no network. About three seconds.
#
#     apps/ios/tools/header-fixture.sh
#
# The table under test (tools/fixtures/header-cases.json) is generated by
# RUNNING the dashboard's own functions:
#
#     pnpm --filter @hermit-ui/dashboard gen:header-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# Built for the host: everything under test is Foundation only.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-header-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/header-fixture" \
  tools/header-fixture/main.swift \
  Hermit/WebLabels.swift \
  Hermit/SessionMeta.swift \
  Hermit/SessionStatus.swift \
  Shared/WebContract.swift

"$OUT/header-fixture" "$PWD"
