#!/usr/bin/env bash
# Holds the Swift port of the mic slot, the press-and-hold gesture and the
# dictation text against the web's own answers. No simulator, no key, no
# network. About three seconds.
#
#     apps/ios/tools/hold-fixture.sh
#
# The table under test (tools/fixtures/hold-cases.json) is generated by RUNNING
# the dashboard's own functions:
#
#     pnpm --filter @hermit-ui/dashboard gen:hold-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# Built for the host: everything under test is Foundation only.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-hold-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/hold-fixture" \
  tools/hold-fixture/main.swift \
  Hermit/HoldCore.swift \
  Hermit/DictationCore.swift

"$OUT/hold-fixture" "$PWD"
