#!/usr/bin/env bash
# Holds the Swift ports of the timeline's data plane against the web's own
# answers: `applyMessagePush` / `foldPushes` (TimelineMerge) and `shedRows` /
# `shouldKeepShed` / `absorbShed` (TimelinePager). No simulator, no key, no
# network, no database. A few seconds.
#
#     apps/ios/tools/merge-fixture.sh
#
# The table under test (tools/fixtures/merge-cases.json) is generated by RUNNING
# apps/dashboard/src/lib/chat-cache/merge-messages.ts and
# apps/dashboard/src/components/chat/use-older-pages.ts:
#
#     pnpm --filter @hermit-ui/dashboard gen:merge-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# No TZ pin, unlike fold-fixture.sh: neither file asks the local calendar
# anything — one parses instants, the other compares ISO strings.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-merge-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/merge-fixture" \
  tools/merge-fixture/main.swift \
  Hermit/ContentBlock.swift \
  Hermit/FoldRuns.swift \
  Hermit/HermitAPI.swift \
  Hermit/TimelineMerge.swift \
  Hermit/TimelinePager.swift

"$OUT/merge-fixture" "$PWD"
