#!/usr/bin/env bash
# Holds the Swift port of the queue strip's decisions against the web's own
# answers. No simulator, no key, no network. About three seconds.
#
#     apps/ios/tools/queue-fixture.sh
#
# The table under test (tools/fixtures/queue-cases.json) is generated by RUNNING
# the dashboard's own functions:
#
#     pnpm --filter @hermit-ui/dashboard gen:queue-fixture
#
# so a disagreement here is always between two implementations, never between an
# implementation and someone's reading of it.
#
# Built for the host: everything under test is Foundation only.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-queue-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/queue-fixture" \
  tools/queue-fixture/main.swift \
  Hermit/QueueCore.swift \
  Hermit/ComposerCore.swift \
  Hermit/ContentBlock.swift

"$OUT/queue-fixture" "$PWD"
