#!/usr/bin/env bash
# Holds the Swift port of `sessionStatusView` against the web's own answers.
# No simulator, no key, no network. About two seconds.
#
#     apps/ios/tools/status-fixture.sh
#
# The table under test (tools/fixtures/status-cases.json) is generated by
# RUNNING apps/dashboard/src/lib/session-status.ts:
#
#     pnpm --filter @hermit-ui/dashboard gen:status-fixture
#
# so a disagreement here is always between two implementations, never between
# an implementation and someone's reading of it. `src/lib/status-fixture.test.ts`
# keeps the table from going stale on the web side.
#
# Built for the host: everything under test is Foundation plus SwiftUI's Color,
# and both exist on macOS. Nothing here touches UIKit.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${TMPDIR:-/tmp}/hermit-status-fixture"
mkdir -p "$OUT"

echo "building…"
swiftc -O \
  -o "$OUT/status-fixture" \
  tools/status-fixture/main.swift \
  Hermit/SessionStatus.swift \
  Shared/StatusPalette.swift \
  Shared/WebContract.swift

"$OUT/status-fixture" "$PWD"
