// The `+` button's pure decisions: what may be attached, how many, what the
// chip under each one reads, and what the caption above the box counts.
//
// Same bargain as `composer-core.ts` and `queue-core.ts` next door, and for the
// same reason: the iOS composer has to reach the SAME answers, and the only
// honest way to check that is to run both implementations over one table
// (`apps/ios/tools/attach-fixture.sh`, generated by
// `scripts/gen-attach-fixture.ts`). A rule that stays inline in `composer.tsx`
// can be read by a porter but never held against them.
//
// The allowlist below was, until this file existed, written out TWICE — once
// here-ish in `composer.tsx` and once in `app/api/upload/route.ts` — with a
// comment on each copy asking the reader to keep them in step. They were in
// step, byte for byte, and there was no test that would have said so. The route
// now imports this one.
//
// No React, no DOM, no `File`: a candidate is described by its name and whether
// the browser called it an image, which is all any of these decisions read.

/**
 * Non-image extensions `/api/upload` accepts. Anything outside this list is
 * rejected before the upload roundtrip (and again on the server) — it keeps
 * loose binaries / executables out, which are gibberish in context and a
 * security concern besides.
 *
 * Archives ARE allowed: stored as-is, the gateway hands the agent an "extract
 * via Bash" instruction instead of Read'ing them. Same for office docs, audio
 * and video — each is converted agent-side rather than read.
 */
export const SAFE_FILE_EXTS = [
  // text & docs
  'txt','md','markdown','rtf','log','pdf',
  // data / config
  'json','yaml','yml','toml','ini','conf','env','xml','html','svg','csv','tsv','sql',
  // source
  'ts','tsx','js','jsx','mjs','cjs','py','rb','php','go','rs',
  'c','cpp','cc','cxx','h','hpp','java','kt','swift','scala','clj','ex','exs',
  'sh','bash','zsh','fish','ps1','dart','lua','r',
  // archives — stored as-is; the agent extracts them via Bash (never Read'd)
  'zip','tar','gz','tgz','bz2','tbz2','xz','txz','7z','rar','zst',
  // office docs — converted agent-side via Bash (textutil / python / unzip)
  'docx','xlsx','pptx','doc','xls','ppt','odt','ods','odp',
  // audio — stored as-is; the agent transcribes / inspects via Bash (whisper / ffmpeg)
  'mp3','m4a','wav','ogg','flac','aac',
  // video — stored as-is; the agent inspects / extracts frames / transcribes via Bash (ffmpeg / ffprobe)
  'mp4','mov','m4v','webm','mkv','avi','mpeg','mpg','3gp','wmv',
] as const;

export const SAFE_FILE_EXT_SET: ReadonlySet<string> = new Set<string>(SAFE_FILE_EXTS);

/** `<input accept>` value: `image/*` + every whitelisted file extension. */
export const FILE_ACCEPT = 'image/*,' + SAFE_FILE_EXTS.map((e) => '.' + e).join(',');

/**
 * Per-message attachment caps — these MUST match `chat.send`'s zod `.max(...)`.
 * The composer enforces them so extras are skipped with a visible notice
 * instead of silently failing the send: `chat.send` rejects the WHOLE message
 * if either is over, so one image too many would sink the text with it.
 */
export const MAX_IMAGES = 20;
export const MAX_FILES = 10;

/**
 * The extension, lowercased, with no dot — `''` when there is no dot at all.
 *
 * Deliberately NOT node's `extname`: this takes the last dot anywhere, so
 * `.bashrc` reads as `bashrc` (and is refused) where `extname` calls a leading
 * dot part of the name and returns `''`. Both refuse the file; only this one
 * can say what it refused.
 */
export function getExt(name: string): string {
  const i = name.lastIndexOf('.');
  return i >= 0 ? name.slice(i + 1).toLowerCase() : '';
}

/** Whether a non-image file may be uploaded at all. Images never come here. */
export function isSafeFileName(name: string): boolean {
  return SAFE_FILE_EXT_SET.has(getExt(name));
}

/** The error a refused file's chip carries. The server's 415 says the same. */
export function unsupportedTypeError(name: string): string {
  const ext = getExt(name);
  return `unsupported file type${ext ? ` (.${ext})` : ''}`;
}

/**
 * What a candidate is called. An empty name means the clipboard handed us an
 * image with no filename, which is the ordinary way a screenshot arrives.
 */
export function attachName(rawName: string, isImage: boolean): string {
  return rawName || (isImage ? 'pasted-image' : 'file');
}

/** One attachment already in the composer, as the cap arithmetic sees it. */
export type SlotUse = { kind: 'uploading' | 'ready' | 'error'; isImage?: boolean };

/**
 * How many of each cap are spoken for. An `error` chip does NOT hold a slot —
 * it is a thing that failed, and refusing the next pick because of it would
 * make a rejected file cost the reader an image.
 */
export function occupiedSlots(existing: readonly SlotUse[]): { images: number; files: number } {
  let images = 0;
  let files = 0;
  for (const a of existing) {
    if (a.kind === 'error') continue;
    if (a.isImage) images += 1;
    else files += 1;
  }
  return { images, files };
}

/**
 * Which of a batch of picked/pasted/dropped files may be added, and what to say
 * about the ones that may not.
 *
 * The caps are applied IN ORDER, so a pick of thirty photos keeps the first
 * twenty rather than an arbitrary twenty; the two budgets are independent, so a
 * pick of thirty photos and one PDF still takes the PDF.
 *
 * Returns INDEXES into `incoming` rather than the items themselves, so a caller
 * holding real `File` objects gets its own objects back.
 */
export function admitFiles(
  incoming: readonly { isImage: boolean }[],
  existing: readonly SlotUse[],
): { accepted: number[]; notice: string | null } {
  const live = occupiedSlots(existing);
  let imgSlots = MAX_IMAGES - live.images;
  let fileSlots = MAX_FILES - live.files;
  const accepted: number[] = [];
  let droppedImg = 0;
  let droppedFile = 0;
  for (let i = 0; i < incoming.length; i++) {
    if (incoming[i].isImage) {
      if (imgSlots > 0) { accepted.push(i); imgSlots -= 1; } else droppedImg += 1;
    } else if (fileSlots > 0) { accepted.push(i); fileSlots -= 1; } else {
      droppedFile += 1;
    }
  }
  if (!droppedImg && !droppedFile) return { accepted, notice: null };
  const parts: string[] = [];
  if (droppedImg) parts.push(`${droppedImg} image${droppedImg > 1 ? 's' : ''} (max ${MAX_IMAGES} per message)`);
  if (droppedFile) parts.push(`${droppedFile} file${droppedFile > 1 ? 's' : ''} (max ${MAX_FILES} per message)`);
  return { accepted, notice: `Skipped ${parts.join(' and ')}.` };
}

/** One half of the caption under the chips. `atCap` is the amber one. */
export type CapSegment = { text: string; atCap: boolean };

/**
 * `3/20 images · 1/10 files` — but only the halves that have anything in them,
 * and only at all once something is attached. A composer with no attachments
 * does not explain a limit nobody is near.
 */
export function capsCaption(images: number, files: number): CapSegment[] {
  const out: CapSegment[] = [];
  if (images > 0) out.push({ text: `${images}/${MAX_IMAGES} images`, atCap: images >= MAX_IMAGES });
  if (files > 0) out.push({ text: `${files}/${MAX_FILES} files`, atCap: files >= MAX_FILES });
  return out;
}

/** The separator between the two halves of the caption. */
export const CAPS_SEPARATOR = ' · ';

/**
 * The sub-label under a finished attachment's filename: real pixel dimensions
 * for an image, a type hint for everything else — never a bogus `?×?`.
 *
 * The dimensions are read client-side as well as server-side precisely so this
 * can be honest on a box with neither `sips` nor `identify` installed.
 */
export function readyLabel(a: {
  isImage: boolean;
  name: string;
  mimeType: string;
  width: number | null;
  height: number | null;
}): string {
  if (a.width && a.height) return `${a.width}×${a.height}`;
  if (a.isImage) return 'image';
  const sub = a.mimeType.split('/')[1];
  if (sub && sub !== 'octet-stream') return sub;
  const ext = a.name.includes('.') ? a.name.split('.').pop()! : '';
  return ext || 'file';
}

/** What the chip's second line says, whatever state the attachment is in. */
export function chipSubLabel(a:
  | { kind: 'uploading' }
  | { kind: 'error'; error: string }
  | { kind: 'ready'; isImage: boolean; name: string; mimeType: string; width: number | null; height: number | null },
): string {
  if (a.kind === 'uploading') return 'uploading…';
  if (a.kind === 'error') return a.error.slice(0, 40);
  return readyLabel(a);
}
