// The composer's pure decisions, and the Stop pill's.
//
// Four small functions that used to live inline in `chat/page.tsx` and
// `composer.tsx`. They are here for the same reason `fold-runs.ts` and
// `timeline-window.ts` are: the iOS timeline has to reach the SAME answers, and
// the only way to check that honestly is to run both implementations over one
// table (`apps/ios/tools/composer-fixture.sh`, generated by
// `scripts/gen-composer-fixture.ts`). A function that stays inline in JSX can be
// read by a porter but never held against them.
//
// No React, no DOM: everything a caller knows is passed in, including `now`.

import { QUEUE_LIMIT } from '@/lib/chat-queue';
import { DELIVERY_GRACE_MS } from '@/lib/session-status';
import { msgText } from '@/components/chat/lib';

// ── Optimistic-row handoff ──────────────────────────────────────────────────

/**
 * An optimistic row (a `pending` bubble or an `optimisticQueue` stub) comes off
 * screen once its REAL row lands in server data. Match by the id `chat.send`
 * returned (`realId`): text matching breaks under outgoing auto-translate, where
 * the optimistic row holds the typed Chinese and the real row is English, so the
 * two never met and the stub lingered / double-counted. Text survives only as a
 * fallback for the window before the send responds, and each real row claims at
 * most ONE optimistic row — two identical texts sent back to back must not
 * dedupe each other.
 */
export function dropLanded<T extends { id: string; realId?: string; content: { type: 'text'; text: string }[] }>(
  optimistic: T[],
  real: ReadonlyArray<{ id: string; content: unknown }>,
): T[] {
  if (optimistic.length === 0) return optimistic;
  const ids = new Set(real.map((m) => m.id));
  const texts = new Map<string, number>();
  for (const m of real) {
    const t = msgText(m.content);
    texts.set(t, (texts.get(t) ?? 0) + 1);
  }
  return optimistic.filter((p) => {
    if (p.realId) return !ids.has(p.realId);
    const t = msgText(p.content);
    const left = texts.get(t) ?? 0;
    if (left === 0) return true;
    texts.set(t, left - 1);
    return false;
  });
}

// ── What the box says, and whether the circle is live ───────────────────────

export type ComposerFace = {
  /** The session is closed. */
  disabled: boolean;
  /** An interaction card upstream is waiting on a click. */
  awaitingInput: boolean;
  /** `queueLen >= QUEUE_LIMIT`. */
  queueFull: boolean;
  /** A turn is running (`turnRunning`, passed to ComposeBar as `inFlight`). */
  working: boolean;
  uploadingCount: number;
  dictating: boolean;
  /** Touch-primary pointer — the hold-to-talk gesture exists only there. */
  touch: boolean;
  /** The Brain is composing in this box, so its ghost text owns the space. */
  brainGhost: boolean;
};

/**
 * The placeholder ladder, top rung first. Order is the whole content: `disabled`
 * outranks `queueFull` because a closed session cannot be queued into either,
 * and `working` sits below both so "↵ to queue next" is only ever offered when
 * queueing would actually work.
 */
export function composerPlaceholder(f: ComposerFace): string {
  if (f.brainGhost) return '';
  if (f.disabled) return 'session is closed';
  if (f.awaitingInput) return '↑ respond above to continue';
  if (f.queueFull) return `queue full (${QUEUE_LIMIT}) · waiting for current turn`;
  if (f.working) return 'working… ↵ to queue next';
  if (f.uploadingCount > 0) return `uploading ${f.uploadingCount}…`;
  // The box is the only place a hands-free run reports from, and it says this
  // for the second or two before the first words land on top of it.
  if (f.dictating) return 'listening…';
  // Only where the gesture exists. On a desktop the box is held by nobody, so
  // promising a hold would be an instruction that does nothing.
  return f.touch ? 'Ask anything · hold to talk' : 'Ask anything';
}

/**
 * Whether the send circle is live. `working` is deliberately NOT in here: a
 * message typed during a running turn is queued, not refused.
 */
export function composerCanSend(a: {
  disabled: boolean;
  awaitingInput: boolean;
  queueFull: boolean;
  uploadingCount: number;
  draft: string;
  /** How many attachments have finished uploading. */
  readyAttachments: number;
}): boolean {
  return !a.disabled
    && !a.awaitingInput
    && !a.queueFull
    && a.uploadingCount === 0
    && (a.draft.trim().length > 0 || a.readyAttachments > 0);
}

// ── Is a turn running? ──────────────────────────────────────────────────────

export type TurnSignals = {
  /** `statusRow.state` — the merged poll + push row — or null when there is none. */
  statusState: string | null;
  /** `statusRow.snapshotAt` in epoch ms, or null. */
  snapshotAt: number | null;
  /** The newest SERVER row's role, or null when the window is empty. */
  lastRole: string | null;
  /** …and that row's `createdAt` in epoch ms, or null. */
  lastAt: number | null;
  /**
   * The newest OPTIMISTIC row's `createdAt` in epoch ms, or null when there is
   * none. Its mere existence means the last message is the user's — the row is
   * one we just wrote.
   */
  optimisticAt: number | null;
  /** The tail assistant row grew within the last ~1.8s (`streamingTailId`). */
  streamingTail: boolean;
  now: number;
};

/**
 * The local, message-shaped half of "a turn is running": the newest row is a
 * user message nobody has answered, or the tail assistant row is still growing.
 *
 * `turnSettled` is the escape hatch that keeps a finished session from looking
 * busy forever. It needs the gateway to have taken a snapshot AFTER the message
 * (plus `DELIVERY_GRACE_MS`, the window in which a snapshot can predate a
 * message it has in fact already picked up) — or ninety seconds to have passed,
 * for the case where no snapshot ever comes.
 */
export function turnInFlight(s: TurnSignals): { waitingAssistant: boolean; inFlight: boolean } {
  const lastMsgIsUser = s.optimisticAt !== null ? true : s.lastRole === 'user';
  const lastMsgTime = s.optimisticAt !== null ? s.optimisticAt : s.lastAt ?? 0;
  const snapTime = s.snapshotAt ?? 0;
  const turnSettled =
    s.statusState === 'idle'
    && (snapTime > lastMsgTime + DELIVERY_GRACE_MS || s.now - lastMsgTime > 90_000);
  const waitingAssistant = lastMsgIsUser && !turnSettled;
  return { waitingAssistant, inFlight: waitingAssistant || s.streamingTail };
}

/**
 * Whether the composer shows its Stop pill — and the `turnRunning` behind it,
 * which Escape uses too.
 *
 * NOT `inFlight` alone. That is a local heuristic and it goes false whenever the
 * agent is busy WITHOUT emitting, which is precisely a long tool call: a session
 * sitting in a multi-minute Bash read "working" in the header while the composer
 * offered no way to stop it. `statusKey === 'working'` is the union —
 * `sessionStatusView` ORs the fast local signal with the gateway's pane-derived
 * state — so this is a strict superset and cannot hide Stop anywhere it used to
 * show. The cost is a stale snapshot leaving Stop up for a few seconds after a
 * turn ends; pressing it then sends Escape to an idle pane, which does nothing.
 * See docs/composer-stop-misfire.md.
 */
export function stopPill(a: { inFlight: boolean; statusKey: string; closed: boolean }): {
  turnRunning: boolean;
  show: boolean;
} {
  const turnRunning = a.inFlight || a.statusKey === 'working';
  return { turnRunning, show: turnRunning && !a.closed };
}
