// The mic slot, and the press-and-hold gesture behind it — every decision in it
// that is arithmetic rather than DOM.
//
// Same bargain as `composer-core.ts` and `queue-core.ts` next door: the iOS
// composer has to reach the SAME answers, and the only honest way to check that
// is to run both implementations over one table
// (`apps/ios/tools/hold-fixture.sh`, generated by `scripts/gen-hold-fixture.ts`).
// Logic that stays inline in `composer.tsx` can be read by a porter but never
// held against them — and this is logic with a lot of surface: five thresholds,
// two hit boxes, a circle's worth of geometry, and a slot whose contents depend
// on six flags.
//
// No React, no DOM. `holdHitBoxes` takes the viewport as numbers rather than
// measuring anything, which is also what makes it checkable.

// ── thresholds ──────────────────────────────────────────────────────────────

/** Hold the empty box this long and the press has become "talking". */
export const HOLD_MS = 260;
/** Travel this far before that and it was a scroll passing through, not a hold. */
export const BAIL_PX = 10;
/** Slide this far sideways, from where the finger went down, to pick 取消 / 编辑. */
export const SLIDE_PX = 64;
/** Below this the finger hasn't gone anywhere, so the pill hit-test stays off. */
export const PILL_MIN_PX = 24;

/** Where the finger is, and therefore what lifting it will do. */
export type HoldZone = 'send' | 'cancel' | 'edit';

/**
 * 'auth' — the mic isn't authorized yet, so this press asks instead of recording
 * (the grant has to be requested from the RELEASE; see composer.tsx).
 * 'listening' — a run is live. 'finishing' — released to send, waiting for the
 * last words (and the whole-passage correction) to land before they go out.
 */
export type HoldPhase = 'auth' | 'listening' | 'finishing';

// ── the gesture ─────────────────────────────────────────────────────────────

/** A rectangle in viewport coordinates. Right and bottom are inclusive edges. */
export interface HoldRect { left: number; top: number; right: number; bottom: number }

/**
 * Has this press stopped being a press? Asked only BEFORE the hold fires: any
 * real travel in the first 260ms means the finger was going somewhere else, and
 * the gesture is handed back rather than starting to record.
 */
export function holdBailed(dx: number, dy: number): boolean {
  return Math.hypot(dx, dy) > BAIL_PX;
}

/**
 * Which exit the finger is currently over.
 *
 * Displacement decides, and landing ON a pill decides too, so a finger that aims
 * at the target it can see is not second-guessed. The pill test is gated on
 * having moved at all (`PILL_MIN_PX`), or a press that started near a corner
 * would read as "cancel" before the finger did anything.
 *
 * Left wins ties: `dx <= -SLIDE_PX` is tested first, and a point inside both
 * rectangles is impossible (they are split either side of the midline).
 */
export function holdZoneAt(p: {
  /** Displacement from where the finger went down. */
  dx: number;
  dy: number;
  /** Where the finger is now, in viewport coordinates. */
  x: number;
  y: number;
  /** The hit boxes, or null while there is nothing to aim at. */
  cancel: HoldRect | null;
  edit: HoldRect | null;
}): HoldZone {
  const travelled = Math.hypot(p.dx, p.dy) > PILL_MIN_PX;
  const onPill = (r: HoldRect | null) =>
    !!r && travelled && p.x >= r.left && p.x <= r.right && p.y >= r.top && p.y <= r.bottom;
  if (p.dx <= -SLIDE_PX || onPill(p.cancel)) return 'cancel';
  if (p.dx >= SLIDE_PX || onPill(p.edit)) return 'edit';
  return 'send';
}

// ── the bottom of the screen ────────────────────────────────────────────────
//
// One circle, centred on the screen's vertical midline, `DROP` px BELOW the
// bottom edge. The send target is that circle filled in; 取消 and 编辑 are a band
// around it, split at the top into two round-ended arcs. Read off a WeChat
// screenshot on a 393pt-wide screen — measurements, not taste. See the header of
// `hold-to-talk.tsx` for how they were taken.

/** How far below the bottom edge the shared centre sits. */
export const DROP = 419;
/** The filled disc — "lift here and it sends". */
export const R_DOME = 540;
/** Outer edge of the 取消 / 编辑 band. */
export const R_OUT = 620;
/** Band thickness, so its inner edge is 558 — 18px of dark between it and the dome. */
export const BAND = 62;
/** Each arc's round end, either side of the midline; the two leave a 31px gap. */
export const CAP = 46.5;
/** Tall enough to contain the band's highest point (~201px). */
export const ZONE_H = 224;
/** Where each label sits along its arc, measured from the midline. */
export const LABEL_D = 114;
/** The band's centreline radius. */
export const R_MID = R_OUT - BAND / 2;

/** Height above the bottom edge of the band's centreline, `d` px off the midline. */
export function midAt(d: number): number {
  return Math.sqrt(R_MID * R_MID - d * d) - DROP;
}

/** How far above the bottom edge the dome's apex sits. */
export const DOME_APEX = R_DOME - DROP;

/**
 * Short on purpose. The enter arrives 260ms into a press that has not shown
 * anything yet, so any transition is delay stacked on delay. Enter is a touch
 * slower than leave so arriving reads as landing rather than snapping.
 */
export const ENTER_MS = 140;
export const LEAVE_MS = 120;

/**
 * The two hit boxes, in viewport coordinates, from the viewport's size.
 *
 * Deliberately plain rectangles over the two arcs, because a rect is what
 * `getBoundingClientRect` can report — and a slide that overshoots into the
 * corner above one should land on it anyway. `bottom-[100px] h-[105px]`, split
 * at the midline with a 15px gutter either side.
 */
export const PILL_BOTTOM = 100;
export const PILL_HEIGHT = 105;
export const PILL_GUTTER = 15;

export function holdHitBoxes(width: number, height: number): { cancel: HoldRect; edit: HoldRect } {
  const top = height - PILL_BOTTOM - PILL_HEIGHT;
  const bottom = height - PILL_BOTTOM;
  return {
    cancel: { left: 0, top, right: width / 2 - PILL_GUTTER, bottom },
    edit: { left: width / 2 + PILL_GUTTER, top, right: width, bottom },
  };
}

// ── what the overlay says ───────────────────────────────────────────────────

/** The label on the lit surface under the thumb. WeChat's dome is blank; ours is not. */
export function holdSurfaceLabel(phase: HoldPhase): string {
  return phase === 'finishing' ? '正在发送' : '松开发送';
}

export const HOLD_CANCEL_LABEL = '取消';
export const HOLD_EDIT_LABEL = '编辑';
export const HOLD_AUTH_LABEL = '需要麦克风权限才能说话';
export const HOLD_AUTH_HINT = '松手 · 允许使用麦克风';

/**
 * Is the transcript being shown as "about to be thrown away"? Only while the run
 * is still live — once the finger has lifted over 取消 there is nothing left to
 * strike through.
 */
export function holdCancelling(zone: HoldZone, phase: HoldPhase): boolean {
  return zone === 'cancel' && phase === 'listening';
}

/**
 * May the blob move? Held still while the finger is over 取消 — a blob still
 * bouncing over the words you are about to throw away reports on nothing. 编辑 is
 * still recording, so it keeps moving.
 */
export function holdBlobMoving(open: boolean, zone: HoldZone, phase: HoldPhase): boolean {
  return open && phase === 'listening' && zone !== 'cancel';
}

/** The elapsed clock under the bubble: `m:ss`, minutes uncapped. */
export function holdClock(seconds: number): string {
  const s = Math.max(0, Math.floor(seconds));
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}

// ── the slot right of the box ───────────────────────────────────────────────

/**
 * What sits between the textarea and the send circle.
 *
 * `mic` while the box is empty (or while a run is live, however much has been
 * dictated into it) and `clear` once there is a draft — and `none` only when
 * there is nothing to say: an empty box on a machine that cannot dictate.
 *
 * The mic is a TOGGLE: the same pixels start the run and end it, and while it is
 * listening it is LIT rather than swapped for another glyph. That matters enough
 * to be a returned flag rather than a caller's guess — the button you pressed is
 * the button you press again.
 */
export type MicSlot =
  | { slot: 'none' }
  | { slot: 'clear' }
  | { slot: 'mic'; listening: boolean; spinner: boolean; disabled: boolean };

export function micSlot(p: {
  /** A dictation run is live. */
  dictating: boolean;
  draftLength: number;
  /** Is there a dictation handler at all? (`onDictate` on the web.) */
  canDictate: boolean;
  disabled: boolean;
  awaitingInput: boolean;
  /** The permission ask is in flight — the button spins and refuses taps. */
  micArming: boolean;
}): MicSlot {
  if ((p.dictating || p.draftLength === 0) && p.canDictate && !p.disabled && !p.awaitingInput) {
    return { slot: 'mic', listening: p.dictating, spinner: p.micArming, disabled: p.micArming };
  }
  if (p.draftLength > 0 && !p.disabled) return { slot: 'clear' };
  return { slot: 'none' };
}

/** What the mic button announces to a screen reader. */
export function micSlotLabel(dictating: boolean): string {
  return dictating ? '结束听写' : '语音输入';
}

/**
 * Should the transparent press layer be over the textarea right now?
 *
 * A long press on a real text field belongs to the platform — iOS answers it
 * with the magnifier and a Paste callout — so the hold is taken by a plain layer
 * that has no such behaviour, and only while the box is EMPTY and UNFOCUSED. The
 * moment there is text or a caret the layer is gone. It also stays for the
 * duration of a gesture already in flight, so lifting still reaches the handler
 * that started it.
 *
 * Touch only. On a desktop, click-and-hold on an input is idle fidgeting.
 */
export function holdPressLayer(p: {
  touch: boolean;
  canDictate: boolean;
  disabled: boolean;
  awaitingInput: boolean;
  dictating: boolean;
  draftLength: number;
  focused: boolean;
  /** A hold is already live — keep the layer regardless of everything above. */
  gestureLive: boolean;
}): boolean {
  const idle =
    p.touch && p.canDictate && !p.disabled && !p.awaitingInput &&
    !p.dictating && p.draftLength === 0 && !p.focused;
  return idle || p.gestureLive;
}
