// The waiting-dispatch queue's pure decisions.
//
// Same bargain as `composer-core.ts` next door, and for the same reason: the
// iOS timeline has to reach the SAME answers, and the only honest way to check
// that is to run both implementations over one table
// (`apps/ios/tools/queue-fixture.sh`, generated by
// `scripts/gen-queue-fixture.ts`). Logic that stays inline in `chat/page.tsx`
// can be read by a porter but never held against them.
//
// What the queue IS: user messages `chat.send` has written and the gateway has
// not picked up yet (`deliveredAt: null`, `externalId: null` — see
// `lib/chat-queue.ts`). They run in order after the turn that is in flight.
// Everything here decides which of them the strip above the composer shows, and
// nothing here talks to a server.
//
// No React, no DOM.

import { QUEUE_LIMIT } from '@/lib/chat-queue';
import { dropLanded } from '@/components/chat/composer-core';

/** A queued message as the server hands it over (`chat.queue` selects both). */
export type QueueRow = { id: string; content: unknown };

/**
 * A message this client has sent during a running turn and has not seen come
 * back yet. Identical in shape to the composer's optimistic bubble, because it
 * IS one: the same send puts a row in the timeline and a line in this strip.
 */
export type QueueStub = { id: string; realId?: string; content: { type: 'text'; text: string }[] };

/** `2_000` — the strip's poll, in ms, and `null` for "stop polling". */
export const QUEUE_POLL_MS = 2_000;

/** `{n} 条排队中 · 等当前任务完成后依次执行`. */
export function queueSummary(n: number): string {
  return `${n} 条排队中 · 等当前任务完成后依次执行`;
}

/** The button that empties the strip. */
export const QUEUE_CLEAR_LABEL = '清空队列';

/**
 * The one line a queued message shows.
 *
 * `preview` is the prose already resolved by the caller — the web resolves an
 * auto-translated send back to what was actually typed (`originalFor`), which
 * is a browser-only store, so that step stays at the call site and this decides
 * only what an EMPTY preview reads as. Empty means the message is attachments
 * and nothing else, which is a real send and must not render as a blank row.
 */
export function queueItemLabel(preview: string): string {
  return preview || '（附件）';
}

/** `queueLen >= QUEUE_LIMIT` — the rung `composerPlaceholder` and `composerCanSend` read. */
export function queueIsFull(queueLen: number): boolean {
  return queueLen >= QUEUE_LIMIT;
}

/**
 * Which messages the strip shows.
 *
 * Three inputs beyond the server's own list, and each one exists because of a
 * flicker that shipped:
 *
 *   · `starters` — a message sent while NOTHING was running is the imminent
 *     ACTIVE turn, not a queue item, yet it sits in `chat.queue` for the ~2s
 *     until the gateway picks it up. Without this it flashes through the strip
 *     on the way to being answered.
 *   · `cancelled` — a row the reader has just pulled, hidden before the
 *     `dequeue` round-trip answers. A stale in-flight poll would otherwise
 *     flash it back.
 *   · `optimistic` — a message sent while a turn IS running is a queue item,
 *     but the real row only surfaces on the next poll. These show instantly.
 *
 * The optimistic stubs are retired against the RAW server list, not the
 * filtered one: a stub whose real row landed and is being hidden as a starter
 * has still landed, and matching against the filtered list would leave it
 * standing forever.
 */
export function queueDisplay<R extends QueueRow, S extends QueueStub>(
  server: readonly R[],
  hidden: { starters: ReadonlySet<string>; cancelled: ReadonlySet<string> },
  optimistic: readonly S[],
): Array<R | S> {
  const real = server.filter((m) => !hidden.starters.has(m.id) && !hidden.cancelled.has(m.id));
  return [...real, ...dropLanded([...optimistic], server)];
}

/**
 * Both id sets above, kept bounded.
 *
 * An id is KEPT while its row is still in the queue and dropped once the row
 * has left — which reads backwards for a moment and is the whole point: a
 * starter that is still undelivered must stay hidden, and an id whose row is
 * gone can never come back, so remembering it is what would grow without bound
 * across a long session.
 *
 * Returns the survivors in the input's own order so a caller can compare
 * lengths and skip a re-render.
 */
export function pruneToLive(ids: Iterable<string>, live: readonly string[]): string[] {
  const alive = new Set(live);
  return [...ids].filter((id) => alive.has(id));
}

/**
 * How often to ask for the queue — `null` for not at all.
 *
 * Poll while it MATTERS and not otherwise: the gateway drains the queue as
 * turns end (so poll while something is in flight) and the reader can pull a
 * row (so poll while the strip is not empty). Idle and empty, there is nothing
 * that can change it.
 *
 * The count is the SERVER's, not the strip's: an optimistic stub with no real
 * row behind it yet is precisely the state where the next poll matters most.
 */
export function queuePollMs(inFlight: boolean, serverCount: number): number | null {
  return inFlight || serverCount > 0 ? QUEUE_POLL_MS : null;
}

/**
 * Where a ✕ on a queued line goes.
 *
 * `'local'` — the line is a stub this client made up; there is no row to
 * delete, so it just goes away. `'server'` — a real queued row, which takes a
 * `dequeue` mutation and can come BACK if the server says `removed: false`
 * (the gateway got there first, so the message is now history, not rubbish).
 *
 * Decided by membership in the optimistic list rather than by the shape of the
 * id. The web mints `pending-<clock>-<random>` and could sniff the prefix; iOS
 * uses the send's own idempotency key, which looks nothing like that. Asking
 * the list is the same answer on both and depends on no naming convention.
 */
export function queueCancelTarget(id: string, optimisticIds: Iterable<string>): 'local' | 'server' {
  for (const o of optimisticIds) if (o === id) return 'local';
  return 'server';
}
