/**
 * What a chat message's `content` actually is — the one definition, for both
 * implementations.
 *
 * `ChatMessage.content` is an opaque JSON column, and until now every reader
 * invented its own idea of what was in it: the router validated writes against a
 * loose union ending in `.passthrough()`, `components/chat/lib.ts` typed a block
 * as an all-optional bag of `any`, and the digest / cap / search projections each
 * re-shape-checked by hand. That is affordable while there is one renderer. It is
 * not affordable with two: the iOS timeline (M4) has to decode the same bytes,
 * and a Swift `enum` cannot be written against "an all-optional bag of any".
 *
 * ## The union is TOTAL, by construction
 *
 * 541k rows written over a year by four producers (the gateway's Claude SDK
 * relay, `send-user-file`, the MCP stub, and the dashboard's own composer) are
 * already in the column. A schema that can REJECT one of them is a schema that
 * makes history unrenderable, so this one cannot: anything that matches no known
 * variant is an `unknown` block carrying its original `type` string and its
 * original object, not an error and not a dropped block.
 *
 * That is the same discipline `Shared/SessionCard.swift` already applies to a
 * Live Activity phase it has never heard of, and it is what M4 needs in order to
 * draw an unrecognised block as a grey card naming its type instead of a blank.
 *
 * ## Two schemas, on purpose
 *
 * `WireContentBlock` validates a write and hands back the ORIGINAL object. It is
 * what an input boundary wants: a producer sending a block type newer than this
 * deploy must still be able to store it verbatim, keys and all.
 *
 * `parseBlocks()` is the reader's view: the same data as a tagged union a
 * renderer can switch over, with the unknown case made explicit. Nothing round
 * trips through it back into the database.
 *
 * `apps/ios/Hermit/ContentBlock.swift` is the Swift half and mirrors the second
 * one exactly; `apps/ios/tools/blocks-fixture.sh` drives both over
 * `apps/ios/tools/fixtures/block-cases.json`, which is generated by running the
 * functions below (`pnpm --filter @hermit-ui/dashboard gen:blocks-fixture`).
 */
import { z } from 'zod';

/** Marks a block whose body was left behind on the server (server/message-digest.ts). */
export const DIGEST_FLAG = '__d';

// ---------------------------------------------------------------------------
// The wire schema — validation only, output === input
// ---------------------------------------------------------------------------

/**
 * Where an image or file's bytes are.
 *
 * Deliberately loose about `type`. `send-user-file` and the composer both write
 * `{type:'url', url, media_type}`, the Claude SDK relay writes
 * `{type:'base64', media_type, data}`, and `capMessageContent` rewrites a big
 * nested one to `{...src, data:'', elidedKB}`. Rows predating any of that carry
 * a bare `{url}` or `{data}` with no `type` at all, and the renderer has always
 * keyed off which FIELD is present rather than off that discriminator.
 */
export const MediaSource = z
  .object({
    type: z.string().optional(),
    url: z.string().optional(),
    media_type: z.string().optional(),
    data: z.string().optional(),
    elidedKB: z.number().optional(),
  })
  .passthrough();

const textBlock = z.object({ type: z.literal('text'), text: z.string() });

const thinkingBlock = z
  .object({
    type: z.literal('thinking'),
    thinking: z.string().optional(),
    // Written by the digest in place of the body it dropped.
    chars: z.number().optional(),
  })
  .passthrough();

const toolUseBlock = z
  .object({
    type: z.literal('tool_use'),
    id: z.string(),
    name: z.string(),
    // Per-tool and unconstrained by anything in this repo — Read's `file_path`,
    // Bash's `command`, a skill's whole argument object.
    input: z.unknown(),
  })
  .passthrough();

const toolResultBlock = z
  .object({
    type: z.literal('tool_result'),
    tool_use_id: z.string(),
    // A string, or an array of nested blocks, or (after the digest) the clipped
    // first line of either.
    content: z.unknown(),
    is_error: z.boolean().optional(),
  })
  .passthrough();

const imageBlock = z
  .object({
    type: z.literal('image'),
    source: MediaSource,
    // Non-Anthropic, written by the composer so the timeline can size the
    // thumbnail before the bytes arrive.
    width: z.number().nullish(),
    height: z.number().nullish(),
  })
  .passthrough();

const fileBlock = z
  .object({
    type: z.literal('file'),
    source: MediaSource,
    name: z.string().optional(),
  })
  .passthrough();

const interactionBlock = z
  .object({
    type: z.literal('interaction'),
    interactionId: z.string().optional(),
    kind: z.string().optional(),
    payload: z.unknown(),
    status: z.string().optional(),
    decision: z.unknown(),
    answeredBy: z.string().nullish(),
  })
  .passthrough();

/** Any object with a `type` string — the branch that makes the union total. */
const anyBlock = z.object({ type: z.string() }).passthrough();

/**
 * One content block as it goes INTO the database.
 *
 * Order matters: `anyBlock` matches everything, so it has to be last, and a
 * known type whose payload is malformed (a `text` block whose `text` is a
 * number, say) falls through to it rather than being rejected. Same outcome as
 * the union this replaces, now written down instead of implied.
 */
export const WireContentBlock = z.union([
  textBlock,
  thinkingBlock,
  toolUseBlock,
  toolResultBlock,
  imageBlock,
  fileBlock,
  interactionBlock,
  anyBlock,
]);

export type WireContentBlock = z.infer<typeof WireContentBlock>;

// ---------------------------------------------------------------------------
// The reader's view — a tagged union a renderer can switch over
// ---------------------------------------------------------------------------

export type Json = null | boolean | number | string | Json[] | { [k: string]: Json };

export type MediaSourceView = {
  kind: 'url' | 'base64' | 'none';
  url: string | null;
  mediaType: string | null;
  /** Present only for base64; `capMessageContent` blanks it and sets `elidedKB`. */
  data: string | null;
  elidedKB: number | null;
};

export type ContentBlock =
  | { type: 'text'; text: string }
  | { type: 'thinking'; thinking: string; chars: number; digested: boolean }
  | { type: 'tool_use'; id: string; name: string; input: Json; digested: boolean }
  | {
      type: 'tool_result';
      toolUseId: string;
      content: Json;
      isError: boolean;
      digested: boolean;
    }
  | { type: 'image'; source: MediaSourceView; width: number | null; height: number | null }
  | { type: 'file'; source: MediaSourceView; name: string | null }
  | {
      type: 'interaction';
      interactionId: string | null;
      kind: 'permission' | 'question';
      payload: Json;
      status: 'pending' | 'resolved';
      decision: Json;
      answeredBy: string | null;
    }
  /** No known variant matched. `blockType` is what the producer called it. */
  | { type: 'unknown'; blockType: string; raw: Json };

const str = (v: unknown): string | null => (typeof v === 'string' ? v : null);
const num = (v: unknown): number | null => (typeof v === 'number' && Number.isFinite(v) ? v : null);

/** JSON that survived `JSON.parse` is already `Json`; this only narrows the type. */
function asJson(v: unknown): Json {
  return (v ?? null) as Json;
}

function sourceView(v: unknown): MediaSourceView {
  const o = (v && typeof v === 'object' ? v : {}) as Record<string, unknown>;
  const url = str(o.url);
  const data = str(o.data);
  // By which field is present, not by `type` — see MediaSource above. A blanked
  // `data:''` with an `elidedKB` beside it is still base64, just elided.
  const kind: MediaSourceView['kind'] =
    url !== null ? 'url' : data !== null || num(o.elidedKB) !== null ? 'base64' : 'none';
  return {
    kind,
    url,
    mediaType: str(o.media_type),
    data,
    elidedKB: num(o.elidedKB),
  };
}

function digested(o: Record<string, unknown>): boolean {
  return o[DIGEST_FLAG] === 1 || o[DIGEST_FLAG] === true;
}

/**
 * One block, as a renderer sees it. Never throws and never returns null: a block
 * this build does not understand comes back as `unknown` with its own type name.
 */
export function parseBlock(raw: unknown): ContentBlock {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return { type: 'unknown', blockType: '', raw: asJson(raw) };
  }
  const o = raw as Record<string, unknown>;
  const t = str(o.type) ?? '';

  switch (t) {
    case 'text': {
      // Absent is an EMPTY text block, not an unknown one — `isHarnessTerminator`
      // and the search projection both already skip a `text` block with nothing
      // in it, and reclassifying it would change what they see. A `text` that is
      // present but not a string is a different thing and does fall through.
      if (o.text !== undefined && o.text !== null && typeof o.text !== 'string') break;
      return { type: 'text', text: str(o.text) ?? '' };
    }
    case 'thinking': {
      // The digest replaces the body with a length; a pre-digest block has the
      // body and no count. Both answer "how long was the reasoning" the same way,
      // which is the only thing the collapsed capsule asks.
      const body = str(o.thinking) ?? str(o.text) ?? '';
      const chars = num(o.chars) ?? body.length;
      return { type: 'thinking', thinking: body, chars, digested: digested(o) };
    }
    case 'tool_use': {
      const id = str(o.id);
      const name = str(o.name);
      if (id === null || name === null) break;
      return { type: 'tool_use', id, name, input: asJson(o.input), digested: digested(o) };
    }
    case 'tool_result': {
      const toolUseId = str(o.tool_use_id);
      if (toolUseId === null) break;
      return {
        type: 'tool_result',
        toolUseId,
        content: asJson(o.content),
        isError: o.is_error === true,
        digested: digested(o),
      };
    }
    case 'image': {
      if (o.source === undefined) break;
      return {
        type: 'image',
        source: sourceView(o.source),
        width: num(o.width),
        height: num(o.height),
      };
    }
    case 'file': {
      if (o.source === undefined) break;
      return { type: 'file', source: sourceView(o.source), name: str(o.name) };
    }
    case 'interaction': {
      // Both defaults are the card's own (`components/chat/interaction-card.tsx`):
      // a block with neither field is a pending question, and a `status` that is
      // anything other than the literal 'pending' has been answered.
      const kind = str(o.kind) === 'permission' ? 'permission' : 'question';
      const status = (str(o.status) ?? 'pending') === 'pending' ? 'pending' : 'resolved';
      return {
        type: 'interaction',
        interactionId: str(o.interactionId),
        kind,
        payload: asJson(o.payload),
        status,
        decision: asJson(o.decision),
        answeredBy: str(o.answeredBy),
      };
    }
  }

  return { type: 'unknown', blockType: t, raw: asJson(raw) };
}

/**
 * A message's whole `content` column as blocks.
 *
 * A plain string is the shape the oldest rows use, and `msgText` / the search
 * projection both still handle it — one text block, so every caller downstream
 * has exactly one case to write.
 */
export function parseBlocks(content: unknown): ContentBlock[] {
  if (typeof content === 'string') return content ? [{ type: 'text', text: content }] : [];
  if (!Array.isArray(content)) return [];
  return content.map(parseBlock);
}

/**
 * The prose of a block, if it has any — what a reader would call "what was said".
 *
 * Only `text`. Callers that also want the interaction cards ask for those
 * separately; joining them here is what would let a search match run across a
 * block boundary (see server/chat-text.ts).
 */
export function blockText(b: ContentBlock): string {
  return b.type === 'text' ? b.text : '';
}
