#!/usr/bin/env node
// gen-chat-md.mjs — give every agent on this machine a CHAT.md.
//
// CHAT.md is what the gateway injects into a PURE-CHAT session's system prompt,
// in place of the operating files the normal startup reads. Without one such a
// session still works, but answers as nobody in particular — wrong language,
// wrong length, no idea what it is for.
//
// Measured before this existed: a pure-chat session with no brief spent SIX
// Read calls and seven turns reading its own operating files before answering
// "hello", because the bootstrap instruction is a `cat` of six files and the
// mode had just removed the shell that runs it. With a brief: one turn, zero
// calls, 58% less context.
//
// Usage:
//   gen-chat-md.mjs --root /Users/mac/claudeclaw            # dry run
//   gen-chat-md.mjs --root /Users/mac/claudeclaw --apply
//   gen-chat-md.mjs --root ... --apply --force              # overwrite existing
//
// An existing CHAT.md is NEVER overwritten without --force: the generated one is
// a floor, and an agent that has since written a better brief by hand (or had
// one written for it) must keep it.

import fs from 'node:fs';
import path from 'node:path';

const args = process.argv.slice(2);
const root = args[args.indexOf('--root') + 1];
const apply = args.includes('--apply');
const force = args.includes('--force');
if (!root || !fs.existsSync(root)) {
  console.error('usage: gen-chat-md.mjs --root <AGENTS_ROOT> [--apply] [--force]');
  process.exit(1);
}

// Everything below the identity is fleet-wide: these agents share a dashboard, a
// memory layout and a house style, so only the identity itself varies. Keep it
// SHORT — it is paid on every turn of every pure-chat session, and anything that
// only matters when you can act does not belong here.
const COMMON = `## How to answer

- Please remove all mannered prose — the most important rule here, it outranks
  the rest of this list.
- Conclusion first. A decision the user has to make opens the reply, never closes it.
- Three to six lines is the default, not a length to fill.
- Cut: process narration, anything the user just told you repeated back, caveats
  on a result that is fine, the same point made twice.
- Never coin a term and then use it as established vocabulary — the user cannot
  look it up and quietly stops following. Say the thing in full. Gloss a real
  term once, the first time it appears.
- Have opinions. Disagree when you disagree. No "great question", no filler.
- Numbers carry units and a baseline, not a bare figure.
- Every sentence should read as if a person wrote it naturally.

## What you can and cannot do here

This session is READ-ONLY: no shell, no writing or editing files, no sub-agents,
no scheduling. You can still record things — \`memory_write\` appends to
\`memory/\` or \`MEMORY.md\` and cannot overwrite what is already there.

Offer a choice with \`mcp__hermit__ask\`, never \`AskUserQuestion\` — the latter
draws a modal the user cannot see, and the turn hangs forever. Send files with
\`mcp__hermit__attach_file\` / \`attach_image\`: the user cannot see this
machine's disk, so a local path hands them nothing. A file or a question is the
LAST thing in a reply, never buried mid-paragraph.

## Memory

Retrospective questions — the user asking about 以前 / 之前 / 上次 / 记不记得 —
get searched before they get answered:
\`grep -i <keyword> memory/notes/INDEX.md\`. Grep it, never read it whole. Then
read the one note you need.

## When this brief is not enough

You have Read, Grep and Glob. Read ONE file rather than sweeping — each one is a
round trip the user waits through. The full versions are \`AGENTS.md\` (the
rules), \`evolution/lessons.md\` (failure root-causes) and \`MEMORY.md\`
(long-term index); open one only when the answer genuinely turns on it.
`;

const HEADER = `# CHAT.md — the pure-chat brief

The gateway injects this into a pure-chat session's system prompt, instead of the
operating files the normal startup reads. Keep it SHORT: it is paid on every turn
of every pure-chat session.

Generated by \`scripts/gen-chat-md.mjs\` from IDENTITY.md. Edit it freely — the
generator never overwrites an existing CHAT.md, and a brief written by hand for
this particular agent will always beat the generated floor.

## Who you are
`;

const rows = [];
for (const name of fs.readdirSync(root).sort()) {
  const dir = path.join(root, name);
  let st;
  try { st = fs.statSync(dir); } catch { continue; }
  if (!st.isDirectory()) continue;
  const idFile = path.join(dir, 'IDENTITY.md');
  if (!fs.existsSync(idFile)) continue;          // not an agent

  const out = path.join(dir, 'CHAT.md');
  if (fs.existsSync(out) && !force) { rows.push([name, 'skip', 'CHAT.md exists']); continue; }

  // The identity goes in verbatim. Extracting "just the important bits" would
  // need a judgement this script cannot make, and IDENTITY.md is small enough
  // (a few KB) that the whole thing is cheaper than getting it wrong.
  const identity = fs.readFileSync(idFile, 'utf8').trim()
    .replace(/^#\s*IDENTITY\.md.*$/im, '')       // its own title duplicates ours
    .trim();

  const body = `${HEADER}\n${identity}\n\n${COMMON}`;
  const bytes = Buffer.byteLength(body);
  if (apply) fs.writeFileSync(out, body);
  rows.push([name, apply ? 'write' : 'would', `${bytes} bytes${bytes > 6000 ? '  ← large, consider trimming by hand' : ''}`]);
}

for (const [n, verb, note] of rows) console.log(`${verb.padEnd(6)} ${n.padEnd(24)} ${note}`);
const w = rows.filter((r) => r[1] !== 'skip').length;
console.log(`\n${rows.length} agents · ${w} ${apply ? 'written' : 'to write'} · ${rows.length - w} skipped`);
if (!apply && w) console.log('dry run — re-run with --apply');
