// What a chat message's `content` is, on this side.
//
// The Swift half of `apps/dashboard/src/lib/chat-blocks.ts`; read that file
// first, it carries the reasoning. The short version:
//
//   · `ChatMessage.content` is an opaque JSON column written by four different
//     producers over a year, and 541k rows of it already exist.
//   · So decoding CANNOT fail. A block this build does not recognise becomes
//     `.unknown(type:raw:)`, keeping the producer's own type string — which is
//     exactly what M4 needs in order to draw it as a grey card naming its type
//     rather than as a blank. Same discipline as `SessionPhase.init(_:)`.
//   · The variants and their normalisation are the web's, verbatim.
//     `tools/blocks-fixture.sh` drives both sides over one table generated by
//     RUNNING the TypeScript, so a disagreement is always between two
//     implementations, never between an implementation and someone's reading.
import Foundation

// MARK: - Free-form JSON

/// A tool's `input`, a tool_result's `content`, an interaction's `payload`:
/// three fields nothing in this repo constrains, because they belong to the
/// tool / the SDK / the hook that produced them.
///
/// Kept as parsed JSON rather than as `Data`, so the timeline can pull one key
/// out of a tool call (`file_path`, `command`) without re-parsing, and so
/// equality means what a reader expects.
indirect enum JSONValue: Equatable, Hashable {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])
}

extension JSONValue: Codable {
    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null; return }
        if let b = try? c.decode(Bool.self) { self = .bool(b); return }
        if let d = try? c.decode(Double.self) { self = .number(d); return }
        if let s = try? c.decode(String.self) { self = .string(s); return }
        if let a = try? c.decode([JSONValue].self) { self = .array(a); return }
        if let o = try? c.decode([String: JSONValue].self) { self = .object(o); return }
        throw DecodingError.dataCorruptedError(in: c, debugDescription: "not JSON")
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .null: try c.encodeNil()
        case .bool(let b): try c.encode(b)
        case .number(let d): try c.encode(d)
        case .string(let s): try c.encode(s)
        case .array(let a): try c.encode(a)
        case .object(let o): try c.encode(o)
        }
    }
}

extension JSONValue {
    /// The string at `key`, if this is an object and that key holds a string.
    /// The one accessor the timeline actually needs (`input.question`,
    /// `payload.tool`), spelled once instead of at each call site.
    func string(_ key: String) -> String? {
        guard case .object(let o) = self, case .string(let s)? = o[key] else { return nil }
        return s
    }

    var asString: String? { if case .string(let s) = self { return s }; return nil }
    var asDouble: Double? { if case .number(let d) = self { return d }; return nil }
    var isNull: Bool { self == .null }
}

// MARK: - Where an image or a file's bytes are

/// Normalised `source`, by which FIELD is present rather than by the `type`
/// discriminator — pre-2026 rows carry a bare `{url}` or `{data}` with no type
/// at all, and the web renderer has always keyed off the field. See the note on
/// `MediaSource` in `chat-blocks.ts`.
struct MediaSourceView: Equatable {
    enum Kind: String, Equatable { case url, base64, none }

    var kind: Kind
    var url: String?
    var mediaType: String?
    /// Base64 bytes. `capMessageContent` blanks these and sets `elidedKB` when
    /// they were nested inside a tool_result, which the timeline never draws.
    var data: String?
    var elidedKB: Double?

    init(_ v: JSONValue?) {
        let url = v?.string("url")
        let data = v?.string("data")
        var elided: Double?
        if case .object(let o)? = v, case .number(let n)? = o["elidedKB"] { elided = n }
        self.url = url
        self.data = data
        self.elidedKB = elided
        self.mediaType = v?.string("media_type")
        self.kind = url != nil ? .url : (data != nil || elided != nil ? .base64 : .none)
    }
}

// MARK: - The blocks

struct TextBlock: Equatable {
    var text: String
}

struct ThinkingBlock: Equatable {
    var thinking: String
    /// How long the reasoning was. The digest drops the body and leaves this
    /// behind; a pre-digest block has the body and no count, and both answer the
    /// collapsed capsule's only question ("💭 thinking · N chars") the same way.
    var chars: Int
    var digested: Bool
}

struct ToolUseBlock: Equatable {
    var id: String
    var name: String
    var input: JSONValue
    var digested: Bool
}

struct ToolResultBlock: Equatable {
    var toolUseId: String
    var content: JSONValue
    var isError: Bool
    var digested: Bool
}

struct MediaBlock: Equatable {
    var source: MediaSourceView
    /// Images only: written by the composer so a thumbnail can be sized before
    /// the bytes arrive.
    var width: Double?
    var height: Double?
    /// Files only: the chip's label.
    var name: String?
}

struct InteractionBlock: Equatable {
    enum Kind: String, Equatable { case permission, question }
    enum Status: String, Equatable { case pending, resolved }

    var interactionId: String?
    var kind: Kind
    var payload: JSONValue
    var status: Status
    var decision: JSONValue
    var answeredBy: String?
}

/// One content block, as a renderer sees it.
enum ContentBlock: Equatable {
    case text(TextBlock)
    case thinking(ThinkingBlock)
    case toolUse(ToolUseBlock)
    case toolResult(ToolResultBlock)
    case image(MediaBlock)
    case file(MediaBlock)
    case interaction(InteractionBlock)
    /// No known variant matched. `type` is what the producer called it — the
    /// grey card's label — and `raw` is the block untouched.
    case unknown(type: String, raw: JSONValue)

    /// The tag, spelled the way the web spells it. Used by the fixture driver and
    /// by anything that logs a block without rendering it.
    var kind: String {
        switch self {
        case .text: return "text"
        case .thinking: return "thinking"
        case .toolUse: return "tool_use"
        case .toolResult: return "tool_result"
        case .image: return "image"
        case .file: return "file"
        case .interaction: return "interaction"
        case .unknown: return "unknown"
        }
    }

    /// The prose of this block, if it has any. Only `text` — joining anything
    /// else in is what would let a search match run across a block boundary
    /// (`server/chat-text.ts`).
    var text: String {
        if case .text(let b) = self { return b.text }
        return ""
    }
}

// MARK: - Decoding

extension ContentBlock {
    /// The `__d` flag `server/message-digest.ts` stamps on a block whose body it
    /// left on the server.
    static let digestFlag = "__d"

    private static func digested(_ o: [String: JSONValue]) -> Bool {
        switch o[ContentBlock.digestFlag] {
        case .number(let n): return n == 1
        case .bool(let b): return b
        default: return false
        }
    }

    /// One block. Never fails: anything unrecognised is `.unknown`.
    ///
    /// The `break`s mirror `parseBlock`'s: a block that names a known type but
    /// is missing the field that type is FOR (a `tool_use` with no `id`, an
    /// `image` with no `source`) is not that type — it falls through and is
    /// drawn as the grey card, which is honest, rather than as a half-rendered
    /// tool call.
    static func parse(_ value: JSONValue) -> ContentBlock {
        guard case .object(let o) = value else { return .unknown(type: "", raw: value) }
        let type = o["type"]?.asString ?? ""

        switch type {
        case "text":
            // Absent is an EMPTY text block; present-but-not-a-string is not one.
            switch o["text"] {
            case .some(.string(let s)): return .text(TextBlock(text: s))
            case .none, .some(.null): return .text(TextBlock(text: ""))
            default: break
            }
        case "thinking":
            let body = o["thinking"]?.asString ?? o["text"]?.asString ?? ""
            let chars = o["chars"]?.asDouble.map { Int($0) } ?? body.count
            return .thinking(ThinkingBlock(thinking: body, chars: chars, digested: digested(o)))
        case "tool_use":
            guard let id = o["id"]?.asString, let name = o["name"]?.asString else { break }
            return .toolUse(ToolUseBlock(id: id, name: name,
                                         input: o["input"] ?? .null, digested: digested(o)))
        case "tool_result":
            guard let toolUseId = o["tool_use_id"]?.asString else { break }
            return .toolResult(ToolResultBlock(toolUseId: toolUseId,
                                               content: o["content"] ?? .null,
                                               isError: o["is_error"] == .bool(true),
                                               digested: digested(o)))
        case "image":
            guard let source = o["source"] else { break }
            return .image(MediaBlock(source: MediaSourceView(source),
                                     width: o["width"]?.asDouble, height: o["height"]?.asDouble,
                                     name: nil))
        case "file":
            guard let source = o["source"] else { break }
            return .file(MediaBlock(source: MediaSourceView(source), width: nil, height: nil,
                                    name: o["name"]?.asString))
        case "interaction":
            // Both defaults are the web card's own: a block with neither field is
            // a pending question, and any `status` other than the literal
            // "pending" has been answered.
            let kind = InteractionBlock.Kind(rawValue: o["kind"]?.asString ?? "") ?? .question
            let status: InteractionBlock.Status = (o["status"]?.asString ?? "pending") == "pending"
                ? .pending : .resolved
            return .interaction(InteractionBlock(
                interactionId: o["interactionId"]?.asString,
                kind: kind,
                payload: o["payload"] ?? .null,
                status: status,
                decision: o["decision"] ?? .null,
                answeredBy: o["answeredBy"]?.asString
            ))
        default:
            break
        }

        return .unknown(type: type, raw: value)
    }

    /// A whole `content` column.
    ///
    /// A bare string is the shape the oldest rows use; one text block, so every
    /// caller downstream has exactly one case to write.
    static func parseAll(_ value: JSONValue) -> [ContentBlock] {
        switch value {
        case .string(let s): return s.isEmpty ? [] : [.text(TextBlock(text: s))]
        case .array(let items): return items.map(ContentBlock.parse)
        default: return []
        }
    }

    /// From raw bytes off the wire. Content that is not JSON at all is no blocks,
    /// not a thrown error — the row still has a timestamp and a role to draw.
    static func parseAll(json data: Data) -> [ContentBlock] {
        guard let v = try? JSONDecoder().decode(JSONValue.self, from: data) else { return [] }
        return parseAll(v)
    }
}
