// Folding a turn's machinery into one row — the Swift half of
// `apps/dashboard/src/components/chat/fold-runs.ts`. Read that file first; it
// carries the reasoning (why a run is keyed by the row BELOW it, why the unit is
// the block and not the message, why an empty message still gets a row).
//
// Two things about this port are deliberate and easy to get wrong:
//
//  1. **It folds over the RAW blocks, not over `ContentBlock`.** The web's
//     `isMachineryBlock` / `stepFor` look at the wire `type` string and nothing
//     else, while `ContentBlock.parse` is stricter: a `tool_use` with no `id`
//     becomes `.unknown`, on purpose, so the timeline draws an honest grey card
//     instead of a half-rendered tool chip. Folding on the parsed case would
//     therefore leave that block VISIBLE on the phone and FOLDED on the web —
//     the same session rendered two different ways. So classification here is
//     the web's, verbatim, and `FoldedMessage.blocks` carries the parsed blocks
//     for the renderer alongside the raw ones the fold actually decided on.
//  2. **JavaScript truthiness is reproduced, not cleaned up.** `is_error: "0"`
//     counts as an error on the web (non-empty string), and `__d: 0` does not
//     mark a step digested. `jsTruthy` exists so those answers match rather than
//     being quietly improved here.
//
// Foundation only, like `ContentBlock.swift` — the timeline can be built on top
// of this without dragging a view layer into every fold.
//
// Held against the web by `apps/ios/tools/fold-fixture.sh`, over a table
// generated by RUNNING the TypeScript.
import Foundation

// MARK: - Input

/// One row of `ChatMessage`, as the fold needs it.
///
/// `createdAt` stays the string the wire gave us: the fold only ever asks
/// whether two of them fall on the same local day, and the rows it emits hand
/// the value straight back for the timeline to format.
struct FoldInput: Equatable {
    var id: String
    var role: String
    var content: JSONValue
    var createdAt: String
    var authoredBy: String?

    init(id: String, role: String, content: JSONValue, createdAt: String, authoredBy: String? = nil) {
        self.id = id
        self.role = role
        self.content = content
        self.createdAt = createdAt
        self.authoredBy = authoredBy
    }
}

// MARK: - Output

/// One tool call inside a run.
struct FoldToolCall: Equatable {
    var id: String
    var name: String
    var input: JSONValue
    /// Input arrived digested — the full arguments need a fetch.
    var digested: Bool
}

enum RunStep: Equatable {
    case call(FoldToolCall)
    /// The raw `tool_result` block. `parsed` is the renderable view of it.
    case result(block: JSONValue, digested: Bool)
    case think(text: String, chars: Int)

    /// The renderable view of a `result` step's block.
    var parsed: ContentBlock? {
        if case .result(let block, _) = self { return ContentBlock.parse(block) }
        return nil
    }
}

/// A row a person can read. `blocks` is machinery-free — the machinery has been
/// lifted into the runs on either side.
struct FoldedMessage: Equatable {
    var key: String
    /// Every message id folded into this row.
    var ids: [String]
    var role: String
    var authoredBy: String?
    var blocks: [ContentBlock]
    /// The same blocks before `ContentBlock.parse` ran. The fold decided on
    /// these, so a disagreement about a row is always readable here.
    var rawBlocks: [JSONValue]
    var createdAt: String
    /// Source message id — what streaming-tail / typewriter decisions key on.
    var msgId: String
}

struct FoldedRun: Equatable {
    /// Identity, and it is NOT the message that opened the run — see the long
    /// note on `FoldedRun.key` in `fold-runs.ts`. A run is named after the row
    /// that FOLLOWS it, so nothing arriving above or below can change it.
    var key: String
    var ids: [String]
    var steps: [RunStep]
    var from: String
    var to: String
}

/// Claude Code ended the turn with no reply — its own marker row.
struct FoldedEnd: Equatable {
    var key: String
    var ids: [String]
    var createdAt: String
}

enum FoldedRow: Equatable {
    case msg(FoldedMessage)
    case run(FoldedRun)
    case end(FoldedEnd)

    var kind: String {
        switch self {
        case .msg: return "msg"
        case .run: return "run"
        case .end: return "end"
        }
    }

    var key: String {
        switch self {
        case .msg(let m): return m.key
        case .run(let r): return r.key
        case .end(let e): return e.key
        }
    }

    var ids: [String] {
        switch self {
        case .msg(let m): return m.ids
        case .run(let r): return r.ids
        case .end(let e): return e.ids
        }
    }
}

/// What the COLLAPSED capsule shows.
struct RunSummary: Equatable {
    /// Distinct tool names, in first-call order.
    var names: [String]
    var calls: Int
    var errors: Int
    var thinkChars: Int
    /// The most recent call — what "currently doing" reads off while running.
    var last: FoldToolCall?
    /// Some step arrived digested; expanding it needs a fetch.
    var digested: Bool
}

// MARK: - The fold

enum FoldRuns {
    /// Key of the run still being written — the only one with no row after it.
    /// A constant rather than a derived id: whatever it were derived from would
    /// be the thing that keeps moving while the turn runs.
    static let openRunKey = "r-open"

    static let machinery: Set<String> = ["tool_use", "tool_result", "thinking"]

    /// The three names the harness gives the one tool call that IS a question.
    static let askToolNames: Set<String> = ["mcp__hermit__ask", "hermit/ask", "ask"]

    // MARK: Block classification

    /// `sink-deliverables.ts`'s `isAskToolUse`. The timeline swaps this call for
    /// the interaction card at its call site, so folding it away would swallow a
    /// question waiting on an answer.
    static func isAskToolUse(_ block: JSONValue) -> Bool {
        guard case .object(let o) = block, o["type"]?.asString == "tool_use",
              let name = o["name"]?.asString, askToolNames.contains(name) else { return false }
        return o["input"]?.string("question") != nil
    }

    /// True for a block the reader has no reason to see inline.
    static func isMachineryBlock(_ block: JSONValue) -> Bool {
        guard case .object(let o) = block, let type = o["type"]?.asString else { return false }
        guard machinery.contains(type) else { return false }
        if type == "tool_use" && isAskToolUse(block) { return false }
        return true
    }

    /// `content` as a block list. A bare non-empty string is one prose block;
    /// anything else that is not an array contributes nothing.
    static func blocks(of content: JSONValue) -> [JSONValue] {
        switch content {
        case .array(let items): return items
        case .string(let s):
            guard !s.isEmpty else { return [] }
            return [.object(["type": .string("text"), "text": .string(s)])]
        default: return []
        }
    }

    /// One machinery block as a run step. `nil` for a thinking block of zero
    /// length — it has nothing to show and nothing to count.
    ///
    /// Only ever called on a block `isMachineryBlock` accepted, so the object
    /// and its `type` are known to be there.
    static func step(for block: JSONValue) -> RunStep? {
        guard case .object(let o) = block else { return nil }
        let digested = jsTruthy(o[ContentBlock.digestFlag])
        let type = o["type"]?.asString ?? ""

        if type == "tool_use" {
            return .call(FoldToolCall(id: jsString(o["id"], default: ""),
                                      name: jsString(o["name"], default: "?"),
                                      input: nullish(o["input"]) ? .object([:]) : o["input"]!,
                                      digested: digested))
        }
        if type == "tool_result" {
            return .result(block: block, digested: digested)
        }
        let text = jsString(nullish(o["thinking"]) ? o["text"] : o["thinking"], default: "")
        // A digested thinking block carries its length in place of its body.
        // `text.length` in JS counts UTF-16 units, which is what the count on
        // the wire was measured in.
        var chars = text.utf16.count
        if case .number(let n)? = o["chars"] { chars = Int(n) }
        if chars == 0 { return nil }
        return .think(text: text, chars: chars)
    }

    // MARK: Seams

    /// Does this message leave no run open, whatever came before it?
    ///
    /// The only state the fold carries between messages is the open run, so a
    /// message that closes one on its own is a point where folding the two
    /// halves separately gives exactly the rows folding the whole gives.
    static func closesRunUnconditionally(_ m: FoldInput) -> Bool {
        if isHarnessTerminator(m.content) { return true }
        let bs = blocks(of: m.content)
        if bs.isEmpty { return true }
        // Mirrors the block loop below: a machinery block flushes any pending
        // visible blocks into a row and opens a run; visible blocks accumulate.
        var pending = 0
        for b in bs {
            if isMachineryBlock(b) { pending = 0 } else { pending += 1 }
        }
        return pending > 0
    }

    /// The largest index at or below `at` that is safe to fold up to. Zero means
    /// there is no seam — the whole list folds as one, which is correct, just
    /// not incremental.
    static func safeSplitIndex(_ messages: [FoldInput], at: Int) -> Int {
        let upper = min(at, messages.count)
        guard upper > 0 else { return 0 }
        var i = upper
        while i > 0 {
            if closesRunUnconditionally(messages[i - 1]) { return i }
            i -= 1
        }
        return 0
    }

    // MARK: The fold itself

    /// Fold a chronologically-ordered message list into timeline rows.
    ///
    /// Runs never span a day boundary — the timeline draws a date divider there,
    /// and a capsule straddling one would have to be either above or below its
    /// own label.
    static func fold(_ messages: [FoldInput]) -> [FoldedRow] {
        var out: [FoldedRow] = []
        /// Index into `out` of the open run, if any.
        var runAt: Int?
        var prevDay: String?
        var prevDate: Date?

        for m in messages {
            let date = parseDate(m.createdAt)
            // `if (prevDay && …)` on the web: an empty timestamp string is
            // falsy there and skips the check, so it skips it here too.
            if let p = prevDay, !p.isEmpty, !isSameDay(prevDate, date) { runAt = nil }
            prevDay = m.createdAt
            prevDate = date

            if isHarnessTerminator(m.content) {
                runAt = nil
                out.append(.end(FoldedEnd(key: m.id, ids: [m.id], createdAt: m.createdAt)))
                continue
            }

            let bs = blocks(of: m.content)
            var buf: [JSONValue] = []
            var part = 0
            // A message of `[tool_use, text, tool_use]` opens TWO runs, and two
            // rows sharing a key would collide in the windowing map.
            var runPart = 0

            func pushMsg(_ visible: [JSONValue]) {
                runAt = nil
                out.append(.msg(FoldedMessage(
                    key: part == 0 ? m.id : "\(m.id)#\(part)",
                    ids: [m.id],
                    role: m.role,
                    authoredBy: m.authoredBy,
                    blocks: visible.map(ContentBlock.parse),
                    rawBlocks: visible,
                    createdAt: m.createdAt,
                    msgId: m.id
                )))
                part += 1
            }

            for b in bs {
                if isMachineryBlock(b) {
                    if !buf.isEmpty {
                        pushMsg(buf)
                        buf = []
                    }
                    guard let s = step(for: b) else { continue }
                    if runAt == nil {
                        let key = runPart == 0 ? "r-\(m.id)" : "r-\(m.id)#\(runPart)"
                        runPart += 1
                        out.append(.run(FoldedRun(key: key, ids: [], steps: [],
                                                  from: m.createdAt, to: m.createdAt)))
                        runAt = out.count - 1
                    }
                    guard let at = runAt, case .run(var r) = out[at] else { continue }
                    r.steps.append(s)
                    r.to = m.createdAt
                    if r.ids.last != m.id { r.ids.append(m.id) }
                    out[at] = .run(r)
                } else {
                    buf.append(b)
                }
            }

            if !buf.isEmpty {
                pushMsg(buf)
            } else if bs.isEmpty && part == 0 {
                // An all-machinery message contributes no row of its own. An
                // EMPTY one still does — dropping a row silently is how a turn
                // boundary goes missing.
                pushMsg([])
            }
        }

        // Second pass: name each run after the row below it. It has to be a
        // second pass because the follower is not known when the run opens, and
        // runs are never adjacent — a run is closed by the very row that ends
        // it — so no two runs can claim the same name.
        for i in out.indices {
            guard case .run(var r) = out[i] else { continue }
            r.key = i + 1 < out.count ? "r>\(out[i + 1].key)" : openRunKey
            out[i] = .run(r)
        }

        return out
    }

    // MARK: Capsule summary

    static func summarize(_ steps: [RunStep]) -> RunSummary {
        var names: [String] = []
        var calls = 0
        var errors = 0
        var thinkChars = 0
        var last: FoldToolCall?
        var digested = false
        for s in steps {
            switch s {
            case .call(let c):
                calls += 1
                last = c
                if !names.contains(c.name) { names.append(c.name) }
                if c.digested { digested = true }
            case .result(let block, let d):
                // The web reads `is_error` off the raw block and tests it for
                // truthiness, so `is_error: "false"` — a non-empty string —
                // counts. `ContentBlock.isError` is stricter on purpose; this is
                // not the place to fix that difference.
                if case .object(let o) = block, jsTruthy(o["is_error"]) { errors += 1 }
                if d { digested = true }
            case .think(let text, let chars):
                thinkChars += chars
                if text.isEmpty && chars > 0 { digested = true }
            }
        }
        return RunSummary(names: names, calls: calls, errors: errors,
                          thinkChars: thinkChars, last: last, digested: digested)
    }

    // MARK: Harness terminator

    /// `lib.ts`'s `isHarnessTerminator`. Claude Code writes "No response
    /// requested." as the visible text of a turn the model exited without
    /// producing output. Accepts accompanying thinking / empty blocks; bails on
    /// anything else.
    static func isHarnessTerminator(_ content: JSONValue) -> Bool {
        guard case .array(let items) = content, !items.isEmpty else { return false }
        var sawTerminator = false
        for b in items {
            guard case .object(let o) = b else { return false }
            let type = o["type"]?.asString
            if type == "thinking" { continue }
            if type == "text" {
                let text = jsString(o["text"], default: "").trimmingCharacters(in: .whitespacesAndNewlines)
                if text.isEmpty { continue }
                if isNoResponseRequested(text) {
                    sawTerminator = true
                    continue
                }
                return false
            }
            return false
        }
        return sawTerminator
    }

    /// `/^no response requested\.?$/i`, without pulling in NSRegularExpression.
    private static func isNoResponseRequested(_ s: String) -> Bool {
        let lower = s.lowercased()
        return lower == "no response requested" || lower == "no response requested."
    }

    // MARK: Dates

    /// Two timestamps on the same day, in the device's own calendar — the same
    /// question `getFullYear/getMonth/getDate` answers in the browser. An
    /// unparseable timestamp is never the same day as anything, which matches
    /// `Invalid Date`'s NaN comparisons and simply closes the run.
    static func isSameDay(_ a: Date?, _ b: Date?) -> Bool {
        guard let a, let b else { return false }
        let cal = Calendar.current
        return cal.isDate(a, inSameDayAs: b)
    }

    private static let isoFractional: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()

    private static let isoPlain: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()

    static func parseDate(_ s: String) -> Date? {
        isoFractional.date(from: s) ?? isoPlain.date(from: s)
    }

    // MARK: JavaScript coercions

    /// `x === null || x === undefined` — what `??` tests.
    static func nullish(_ v: JSONValue?) -> Bool {
        v == nil || v! == .null
    }

    /// JavaScript truthiness. Only used where the web tests a raw field for it.
    static func jsTruthy(_ v: JSONValue?) -> Bool {
        switch v {
        case nil, .some(.null): return false
        case .some(.bool(let b)): return b
        case .some(.number(let n)): return n != 0 && !n.isNaN
        case .some(.string(let s)): return !s.isEmpty
        case .some(.array), .some(.object): return true
        }
    }

    /// `String(v ?? fallback)`.
    static func jsString(_ v: JSONValue?, default fallback: String) -> String {
        guard let v, v != .null else { return fallback }
        return jsString(v)
    }

    /// `String(v)` for a value that is neither null nor undefined.
    static func jsString(_ v: JSONValue) -> String {
        switch v {
        case .null: return "null"
        case .bool(let b): return b ? "true" : "false"
        case .number(let n): return jsNumberString(n)
        case .string(let s): return s
        // `Array.prototype.toString` is `join(',')`, and join renders null and
        // undefined as the empty string.
        case .array(let a): return a.map { $0 == .null ? "" : jsString($0) }.joined(separator: ",")
        case .object: return "[object Object]"
        }
    }

    /// Integral doubles print without a decimal point in JS, and this is the
    /// only place a number reaches a string in the fold.
    private static func jsNumberString(_ n: Double) -> String {
        if n.isNaN { return "NaN" }
        if n.isInfinite { return n > 0 ? "Infinity" : "-Infinity" }
        if n == n.rounded() && abs(n) < 1e15 { return String(Int64(n)) }
        return String(n)
    }
}
