import Foundation

/// How a session's runtime state renders — ported line for line from
/// `apps/dashboard/src/lib/session-status.ts`.
///
/// That file opens with sway's colour spec and is the web app's single source of
/// truth: the chat header, the sidebar dot and the agent sheet all call
/// `sessionStatusView` so they cannot drift apart. A phone that decided for
/// itself when a session is "working" would be exactly that drift, one platform
/// further out — and the failure is invisible, because both answers look
/// plausible on their own screen.
///
/// So this is a PORT, not a re-derivation. The order of the checks, the labels,
/// the Tailwind class strings and the falsy-string quirks are all the original's,
/// and `apps/ios/tools/status-fixture.sh` runs both implementations over the
/// same table (`tools/fixtures/status-cases.json`, generated by running the real
/// TypeScript) to prove it. When the web changes, regenerate the table: the
/// fixture goes red, not the phone.
///
/// Clocks are in **milliseconds since 1970**, as Doubles, because that is what
/// the original uses everywhere. Converting to `TimeInterval` seconds would have
/// put a unit conversion inside the one thing being compared byte for byte
/// against the original; the conversion lives at the edges instead (`ms(_:)`).

// MARK: - The row this reads

/// What a session row has to carry for the status view to judge it.
///
/// Mirrors `SessionRuntimeLike`. Every field is optional for the same reason it
/// is there: the two doors a row can come through — `chat.listSessions` and
/// `chat.getSession` / the status frame — carry different subsets, and a field
/// the caller does not have must read as "cannot say", never as "no".
struct SessionRuntime {
    /// Is a process running this session RIGHT NOW? `false` means asleep, not
    /// broken: the next message resumes it with the conversation intact.
    var alive: Bool?
    var state: String?
    /// When the gateway last reported. `state` is only evidence while this is
    /// recent — nothing else clears a 'working' left behind by a gateway that
    /// died mid-turn.
    var snapshotAt: Date?
    /// The opaque activity blob. Only backends with a typed event stream fill it
    /// in, so absent means "this backend cannot say", not "idle".
    var activity: SessionActivity?
    /// The one fact out of `activity` that the 5s sidebar poll carries.
    var backgroundBusy: Bool?
    /// The one LINE of it — `background · 1h 28m` — likewise precomputed.
    var backgroundNote: String?
    var lastMessageAt: Date?
    var closedAt: Date?
    var restartRequestedAt: Date?

    init(alive: Bool? = nil, state: String? = nil, snapshotAt: Date? = nil,
         activity: SessionActivity? = nil, backgroundBusy: Bool? = nil,
         backgroundNote: String? = nil, lastMessageAt: Date? = nil,
         closedAt: Date? = nil, restartRequestedAt: Date? = nil) {
        self.alive = alive
        self.state = state
        self.snapshotAt = snapshotAt
        self.activity = activity
        self.backgroundBusy = backgroundBusy
        self.backgroundNote = backgroundNote
        self.lastMessageAt = lastMessageAt
        self.closedAt = closedAt
        self.restartRequestedAt = restartRequestedAt
    }
}

/// What a session is doing right now, as the gateway's runtime reports it.
///
/// Mirrors `SessionActivity` in `apps/dashboard/src/lib/session-status.ts` field
/// for field. It arrives through an opaque JSON column, so every field is
/// optional there and every field is optional here — a gateway older or newer
/// than this app must not make the frame undecodable.
struct SessionActivity: Decodable, Equatable {
    var kind: String?
    var label: String?
    var detail: String?
    var elapsedSec: Double?
    var attempt: Int?
    var maxRetries: Int?
    var retryInSec: Double?
    var backgroundCount: Int?
    /// What each background task IS, oldest first. A gateway older than
    /// 2026-09-02 sends only the count, which is why an absent list means
    /// "cannot say" and not "none".
    var backgroundTasks: [BackgroundTask]?

    struct BackgroundTask: Decodable, Equatable {
        var id: String?
        var description: String?
        var elapsedSec: Double?
        var kind: String?
        var command: String?
        var outputTail: String?
    }
}

/// One background task, after `backgroundTaskList` has filled in its defaults.
/// Mirrors `BackgroundTaskView`.
struct BackgroundTaskView: Equatable {
    var id: String
    var description: String
    /// Whole seconds; 0 when the gateway did not say.
    var elapsedSec: Double
    var kind: String?
    var command: String?
    var outputTail: String?
}

/// The verdict. Mirrors `StatusView`.
/// The four fields a pushed status frame is allowed to speak for.
///
/// `LiveStatusFrame` in `lib/session-status.ts`. Deliberately not
/// `SessionStatusFrame` from `HermitStream` — that one is a wire format with a
/// decoder, this is the argument `merge` takes, and keeping them apart is what
/// lets the merge be tested without a socket.
struct LiveStatusFrame: Equatable {
    var state: String?
    var alive: Bool
    var activity: SessionActivity?
    var snapshotAt: Date?

    init(state: String?, alive: Bool, activity: SessionActivity?, snapshotAt: Date?) {
        self.state = state
        self.alive = alive
        self.activity = activity
        self.snapshotAt = snapshotAt
    }
}

struct StatusView: Equatable {
    enum Key: String {
        case needsYou = "needs-you"
        case working, unread, ready, starting, restarting, down, stale, asleep
    }

    var key: Key
    var label: String
    /// The Tailwind class, verbatim — `bg-amber-400`, `bg-amber-400/50`.
    ///
    /// Kept as the web's string rather than resolved to a `Color` here for two
    /// reasons: the fixture can then compare this field byte for byte against
    /// what the browser computes, and the one place that turns a class into a
    /// colour stays `StatusPalette.dot`, which reads the generated palette.
    var dot: String
    var pulse: Bool
    /// Longer qualification for a long-press or a tooltip — the command, the
    /// task, the retry.
    var detail: String?
}

/// Options the caller knows and the row does not. Mirrors the `opts` bag.
struct StatusOptions {
    /// Working as the BROWSER sees it — an open timeline reading its own stream.
    /// Faster than the snapshot and still true when the gateway is the quiet one.
    var liveWorking: Bool = false
    /// The agent finished work nobody has read.
    var unread: Bool = false
    /// The turn is parked on a permission prompt or a question. Only a view with
    /// the session's messages loaded can see this.
    var needsYou: Bool = false
    /// Epoch ms. `nil` = now.
    var now: Double?
    /// Epoch ms of the last answer we actually GOT from the dashboard. `nil` =
    /// not supplied, which falls back to `now` — the wall-clock behaviour.
    var observedAt: Double?
    /// Epoch ms when the current run of contact began.
    var reachableSince: Double?

    init(liveWorking: Bool = false, unread: Bool = false, needsYou: Bool = false,
         now: Double? = nil, observedAt: Double? = nil, reachableSince: Double? = nil) {
        self.liveWorking = liveWorking
        self.unread = unread
        self.needsYou = needsYou
        self.now = now
        self.observedAt = observedAt
        self.reachableSince = reachableSince
    }
}

// MARK: - The port

enum SessionStatus {

    /// How long the gateway's `state` stays believable after it last spoke.
    /// SNAPSHOT_STALE_MS, from the generated contract.
    static var snapshotStaleMs: Double { WebContract.snapshotStaleMs }

    /// When a background task stops counting as part of the answer.
    /// BACKGROUND_RESIDENT_MS, shared with the push gate on the web for a
    /// specific reason: the dot and the notification must call a task resident
    /// at the SAME moment, or a phone rings about work the sidebar still shows
    /// as running.
    static var backgroundResidentMs: Double { WebContract.backgroundResidentMs }

    /// Epoch milliseconds, the unit the whole file works in.
    static func ms(_ date: Date?) -> Double? {
        guard let date else { return nil }
        let t = date.timeIntervalSince1970 * 1000
        return t.isFinite ? t : nil
    }

    /// `47s`, `3m 20s`, `1h 28m` — short enough to sit in a header chip.
    ///
    /// Takes a Double rather than an Int because the original takes a JS number
    /// and one caller passes `elapsedSec` through unrounded (`activityLabel`,
    /// the `tool` branch), so a gateway reporting 12.5 seconds prints `12.5s` in
    /// the browser and has to print it here too.
    static func shortDuration(_ sec: Double) -> String {
        if sec < 60 { return "\(jsNumber(sec))s" }
        if sec < 3600 {
            let m = (sec / 60).rounded(.down)
            let s = sec.truncatingRemainder(dividingBy: 60)
            // `s ? … : …` in the original: 0 is falsy, so a whole number of
            // minutes drops the seconds half entirely.
            return s != 0 ? "\(jsNumber(m))m \(jsNumber(s))s" : "\(jsNumber(m))m"
        }
        let h = (sec / 3600).rounded(.down)
        let m = (sec.truncatingRemainder(dividingBy: 3600) / 60).rounded(.down)
        return m != 0 ? "\(jsNumber(h))h \(jsNumber(m))m" : "\(jsNumber(h))h"
    }

    /// A number the way `${n}` writes it in JavaScript: no trailing `.0`.
    ///
    /// `"\(12.0)"` in Swift is `12.0`; the browser prints `12`. These strings go
    /// on screen beside the browser's, and the fixture compares them character
    /// for character.
    static func jsNumber(_ n: Double) -> String {
        if n == n.rounded() && abs(n) < 1e15 { return String(Int64(n)) }
        return "\(n)"
    }

    /// Did this session start work that has outlived the turn that started it?
    ///
    /// Shape-reading only, no judgement: `activity` is an opaque JSON column, so
    /// a payload from a newer gateway reads as "cannot say", never as "no".
    static func backgroundOutstanding(_ a: SessionActivity?) -> Bool {
        guard let n = a?.backgroundCount else { return false }
        return n > 0
    }

    /// The background tasks a snapshot named, oldest first.
    ///
    /// An empty list does NOT mean there is no background work — a gateway from
    /// before this field existed reports a count and nothing else. Ask
    /// `backgroundOutstanding` for the yes/no.
    ///
    /// One difference from the original that cannot bite: TypeScript skips
    /// entries that are not objects, and the index it numbers a nameless task
    /// with (`bg-2`) counts those skipped entries. Swift has already refused the
    /// whole array by then — a malformed element fails `SessionActivity`'s
    /// decode — so there is nothing to skip and the indices cannot diverge.
    static func backgroundTaskList(_ a: SessionActivity?) -> [BackgroundTaskView] {
        guard let list = a?.backgroundTasks else { return [] }
        return list.enumerated().map { i, t in
            let trimmed = t.description?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            let elapsed = (t.elapsedSec ?? 0) > 0 ? (t.elapsedSec ?? 0).rounded(.down) : 0
            let id = (t.id?.isEmpty == false) ? t.id! : "bg-\(i)"
            return BackgroundTaskView(
                id: id,
                description: trimmed.isEmpty ? "background task" : trimmed,
                elapsedSec: elapsed,
                kind: opt(t.kind), command: opt(t.command), outputTail: opt(t.outputTail)
            )
        }
    }

    /// `s.trim() ? s.trim() : undefined` — a blank string is not a value.
    private static func opt(_ v: String?) -> String? {
        let t = v?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return t.isEmpty ? nil : t
    }

    /// `background · 1h 28m` / `background ×3 · 12m` — the chip text for a
    /// session whose only remaining work is outside the turn.
    ///
    /// The age is the load-bearing half: "background" alone reads the same at
    /// three seconds and at three hours.
    static func backgroundSummary(_ a: SessionActivity?) -> String? {
        guard backgroundOutstanding(a) else { return nil }
        let n = a?.backgroundCount ?? 0
        // Only when background work is ALL that is left. A session with a
        // foreground tool running has background tasks too, and calling that row
        // "background" would name the sideshow.
        if a?.kind != "background" { return "working +\(n) bg" }
        let oldest = backgroundTaskList(a).first
        let count = n > 1 ? " ×\(n)" : ""
        let age = (oldest?.elapsedSec ?? 0) > 0 ? " · \(shortDuration(oldest!.elapsedSec))" : ""
        return "background\(count)\(age)"
    }

    /// The same question as `backgroundOutstanding`, asked of a whole row.
    ///
    /// An OR, because neither source may answer "no" on behalf of a payload it
    /// does not carry: the sidebar row has only the boolean, the chat header has
    /// only the blob, and a row with neither means the backend cannot say.
    static func backgroundStillRunning(_ s: SessionRuntime, now: Double) -> Bool {
        if s.backgroundBusy != true && !backgroundOutstanding(s.activity) { return false }
        // Since the AGENT's last word, not since the task started: the question
        // is whether a reply is still coming, and half an hour of silence is the
        // evidence that one is not.
        if let last = ms(s.lastMessageAt), now - last >= backgroundResidentMs { return false }
        return true
    }

    /// The working label, sharpened by whatever the backend could tell us.
    ///
    /// Falls back to a plain `working` whenever the payload is missing or
    /// malformed — this is a JSON column, so nothing in it is guaranteed.
    static func activityLabel(_ raw: SessionActivity?) -> (label: String, detail: String?)? {
        guard let a = raw else { return nil }
        let bg = (a.backgroundCount ?? 0) > 0 ? " +\(a.backgroundCount!) bg" : ""

        switch a.kind {
        case "retrying":
            let wait = (a.retryInSec ?? 0) > 0 ? ", \(jsNumber(a.retryInSec!))s" : ""
            // `a.attempt && a.maxRetries` — 0 is falsy on both, so a gateway
            // that sent zeros gets the bare word rather than "retrying 0/0".
            let n = (a.attempt ?? 0) != 0 && (a.maxRetries ?? 0) != 0
                ? " \(a.attempt!)/\(a.maxRetries!)" : ""
            return ("retrying\(n)\(wait)", a.detail ?? "the API asked us to back off")
        case "compacting":
            return ("compacting\(bg)", a.detail)
        case "subagent":
            return (nonEmpty(a.label, "subagent") + bg, a.detail)
        case "tool":
            let t = (a.elapsedSec ?? 0) > 0 ? " · \(shortDuration(a.elapsedSec!))" : ""
            return (nonEmpty(a.label, "tool") + t + bg, a.detail)
        case "background":
            // Not `background\(bg)`: this branch IS the background one, so the
            // "+1 bg" suffix the other branches carry said the same word twice.
            let tasks = backgroundTaskList(a)
            let detail = tasks.isEmpty
                ? a.detail
                : tasks.map { "\($0.description)\($0.elapsedSec != 0 ? " · \(shortDuration($0.elapsedSec))" : "")" }
                       .joined(separator: "\n")
            return (backgroundSummary(a) ?? "background", detail)
        case "thinking":
            return ("thinking\(bg)", a.detail)
        default:
            return nil
        }
    }

    /// `a.label || 'tool'` — an EMPTY string is falsy in JavaScript, so a
    /// gateway that sent `label: ""` gets the fallback, not a blank chip.
    private static func nonEmpty(_ v: String?, _ fallback: String) -> String {
        (v?.isEmpty == false) ? v! : fallback
    }

    /// How long the gateway has been silent about this session — counting only
    /// time this client could actually see the dashboard.
    ///
    /// The distinction is the whole point. `now - snapshotAt` also grows when
    /// WE are the thing that stopped asking (a backgrounded app, a dropped
    /// connection), and charging that to the gateway is what made a session
    /// mid-long-task flicker grey every time a tool finished.
    static func snapshotSilenceMs(_ snapshotAt: Date?, _ opts: StatusOptions = StatusOptions()) -> Double? {
        guard let snap = ms(snapshotAt) else { return nil }
        // `opts.observedAt === undefined ? (opts.now ?? Date.now()) : opts.observedAt`
        let observedAt = opts.observedAt ?? opts.now ?? (Date().timeIntervalSince1970 * 1000)
        // `if (!observedAt)` — 0 means we have never had an answer, which is no
        // basis to judge anything: null, not stale.
        if observedAt == 0 { return nil }
        let silentSince = max(snap, opts.reachableSince ?? 0)
        // Clamped at 0: our clock and the dashboard's are independent.
        return max(0, observedAt - silentSince)
    }

    /// Fold a pushed status frame into the polled session row.
    ///
    /// `mergeLiveStatus` in `lib/session-status.ts`. Both describe the same row;
    /// the frame is just earlier, and `snapshotAt` decides which one is later —
    /// the GATEWAY's clock on both sides, never this device's.
    ///
    /// Three details that are the whole function:
    ///
    ///   · a frame equal in time to the row LOSES. The poll has already caught
    ///     up, and the row carries every field where the frame carries four.
    ///   · a missing `snapshotAt` counts as zero on either side, so a frame that
    ///     cannot say when it was taken never displaces a row that can.
    ///   · it replaces exactly `state`, `alive`, `activity` and `snapshotAt`.
    ///     `closedAt` and `restartRequestedAt` stay as the row has them even
    ///     though the wire frame carries both — a push must not be able to
    ///     contradict a field it is not the authority on.
    static func merge(_ s: SessionRuntime?, _ live: LiveStatusFrame?) -> SessionRuntime? {
        guard var row = s, let live else { return s }
        let rowAt = ms(row.snapshotAt) ?? 0
        let liveAt = ms(live.snapshotAt) ?? 0
        if liveAt <= rowAt { return row }
        row.state = live.state
        row.alive = live.alive
        row.activity = live.activity
        row.snapshotAt = live.snapshotAt
        return row
    }

    /// Resting states: the session is fine and nothing is happening. What keeps
    /// a list of idle sessions from being a column of the word "asleep".
    static func isRestingState(_ key: StatusView.Key) -> Bool {
        key == .ready || key == .asleep
    }

    /// The verdict. Mirrors `sessionStatusView`; the ORDER of these checks is
    /// the contract, not the individual branches.
    static func view(_ s: SessionRuntime?, _ opts: StatusOptions = StatusOptions()) -> StatusView {
        // amber — blocked ON YOU. Outranks working: the turn is not advancing,
        // it is parked until you answer.
        if opts.needsYou {
            return StatusView(key: .needsYou, label: "needs you", dot: "bg-amber-400", pulse: true)
        }

        // A backend that can say WHAT it is doing gets to say it here.
        // `parked` = nothing in the foreground, but background work outstanding:
        // the same state key, a dimmed and unpulsed dot, because the pulse means
        // "moving" and this is not moving.
        func working(parked: Bool = false) -> StatusView {
            let a = activityLabel(s?.activity)
            // The sidebar row has no `activity` blob — chat.listSessions strips
            // it — so `backgroundNote` is the one line of it the poll carries,
            // used only as a FALLBACK so a caller with the real thing keeps the
            // richer label.
            let label = a?.label ?? s?.backgroundNote ?? "working"
            return StatusView(
                key: .working, label: label,
                dot: parked ? "bg-amber-400/50" : "bg-amber-400",
                pulse: !parked, detail: a?.detail
            )
        }

        // yellow — working, as the CLIENT sees it. Above everything else: this
        // is a timeline reading its own stream, faster than the snapshot and
        // still true when the gateway is the thing that has gone quiet.
        if opts.liveWorking { return working() }
        // grey — down / not active.
        guard let s else {
            return StatusView(key: .down, label: "—", dot: "bg-zinc-400", pulse: false)
        }
        // Closed outranks a server 'working': the gateway only polls sessions
        // with closedAt = null, so one archived mid-turn keeps the state it died
        // on and would pulse amber forever for a conversation that is over.
        if s.closedAt != nil {
            return StatusView(key: .down, label: "closed", dot: "bg-zinc-400", pulse: false)
        }
        // grey — the gateway has stopped reporting, so `state` is a memory.
        // Ranked above it deliberately: everything below this line reads `state`
        // or `alive`, and neither is evidence once it is this old.
        if let age = snapshotSilenceMs(s.snapshotAt, opts), age > snapshotStaleMs {
            return StatusView(
                key: .stale, label: "stale", dot: "bg-zinc-400", pulse: false,
                detail: "the gateway has not reported on this session recently — this is the last state it saw"
            )
        }
        // yellow — working, as the gateway last observed it.
        if s.state == "working" { return working() }
        // yellow — the turn ended, the work it started did not. A backgrounded
        // Bash or subagent lands the CLI in `idle` within a millisecond of
        // firing; falling through from here reached 'unread', whose whole
        // meaning is "the agent FINISHED work you have not read".
        if s.state == "idle",
           backgroundStillRunning(s, now: opts.now ?? (Date().timeIntervalSince1970 * 1000)) {
            return working(parked: true)
        }
        // sky — recycling. Outranks the `alive` check below, since `alive` flips
        // false mid-restart and we want "restarting", not "exited".
        if s.restartRequestedAt != nil {
            return StatusView(key: .restarting, label: "restarting", dot: "bg-sky-400", pulse: true)
        }
        // sky — pane up but claude still booting (no transcript yet).
        if s.state == "starting" {
            return StatusView(key: .starting, label: "starting", dot: "bg-sky-400", pulse: true)
        }
        // Unread outranks asleep: "the agent finished something you have not
        // read" is the fact worth a colour, whether or not a process is still up.
        if opts.unread {
            return StatusView(key: .unread, label: "unread", dot: "bg-rose-500", pulse: false)
        }
        // dim green — nothing is running, and nothing is wrong: the next message
        // resumes the conversation with its history intact.
        if s.alive == false {
            return StatusView(
                key: .asleep, label: "asleep", dot: "bg-emerald-500/30", pulse: false,
                detail: "nothing is running — your next message wakes it with the conversation intact"
            )
        }
        return StatusView(key: .ready, label: "ready", dot: "bg-emerald-500", pulse: false)
    }
}
