//  SyncPlan.swift
//
//  A port of apps/dashboard/src/lib/chat-cache/sync-plan.ts, rule for rule.
//
//  The web keeps a full copy of the machine's prose in the browser so search is
//  local and instant; the phone wants exactly the same thing, and the rules that
//  decide what one sync pass has to do are the fiddly part. They are also pure,
//  so they can be shared as a TABLE rather than as prose:
//
//      apps/ios/tools/fixtures/sync-plan-cases.json
//
//  is generated by running the REAL TypeScript function over 22 inputs
//  (`pnpm --filter @hermit-ui/dashboard gen:sync-plan-fixture`), and
//  `tools/cache-fixture.sh` runs this implementation over the same table. Change
//  the rules on the web and the fixture goes stale, which is a red test there
//  and a red fixture run here.
//
//  Three of this function's answers are decided by JavaScript rather than by
//  anything the TypeScript says out loud, and each one is a way a port goes
//  quietly wrong. They are called out at the line that reproduces them.
//
//  NO CREDENTIALS: nothing here touches the network or the Keychain. It takes
//  what the server said and what the cache holds, and returns a plan.

import Foundation

/// One row of `chat.syncProbe`: how far along the server is for one session.
struct ProbeRow: Codable, Equatable {
    let sessionId: String
    let agentName: String
    let title: String?
    let preview: String?
    /// `MAX(ChatMessage.updatedAt)` in epoch milliseconds.
    ///
    /// `Int`, not `Int32`: a real watermark passed 2^31 in 1994. The fixture
    /// carries one (`a watermark past 2^31`) so a narrowed type fails there
    /// rather than in a year's worth of missing messages.
    let watermark: Int
    let count: Int
}

/// Per-session sync bookkeeping, as of the last COMPLETED pass. Mirrors one
/// `chat.syncProbe` row once that session is fully cached locally, which is why
/// it is the same shape as `ProbeRow` — a finished fetch copies one across.
struct CachedSession: Codable, Equatable {
    let sessionId: String
    let agentName: String
    let title: String?
    let preview: String?
    let watermark: Int
    let count: Int

    init(sessionId: String, agentName: String, title: String?, preview: String?, watermark: Int, count: Int) {
        self.sessionId = sessionId
        self.agentName = agentName
        self.title = title
        self.preview = preview
        self.watermark = watermark
        self.count = count
    }

    init(_ probe: ProbeRow) {
        self.init(
            sessionId: probe.sessionId,
            agentName: probe.agentName,
            title: probe.title,
            preview: probe.preview,
            watermark: probe.watermark,
            count: probe.count
        )
    }
}

/// What one sync pass has to do.
struct SyncPlan: Equatable {
    /// One session to pull, and from where.
    struct Fetch: Equatable {
        /// The SERVER's row, not the cached one — so a renamed session or a
        /// fresh preview reaches the writer even when only metadata moved.
        let probe: ProbeRow
        /// Watermark to fetch from; `0` means the whole history.
        let since: Int
        /// Wipe what is cached for this session before writing the answer.
        let reset: Bool
    }

    /// Sessions the server no longer reports — deleted upstream.
    var drop: [String] = []
    /// Sessions to pull, newest activity first.
    var fetch: [Fetch] = []
    /// Already level with the server.
    var upToDate: [ProbeRow] = []
}

/// Decide what a sync pass has to do.
///
///   · not cached                → full fetch from 0
///   · cached count > server's   → a row was DELETED (dequeue / clearQueue); the
///                                 watermark can't see that and a delta fetch
///                                 can't repair it, so wipe and refetch
///   · watermark or count moved  → delta fetch from the cached watermark
///   · otherwise                 → nothing to do
func planSync(probe: [ProbeRow], cached: [CachedSession]) -> SyncPlan {
    // JS BEHAVIOUR #1 — `drop` comes out in the order `cached` was iterated,
    // because the original walks a Map built from it and a Map iterates in
    // insertion order. A Swift Dictionary has NO order, so the ids are kept in a
    // parallel array. `Map.set` on a key that is already present keeps its
    // ORIGINAL position, so a re-inserted id does not move to the back.
    var localOrder: [String] = []
    var local: [String: CachedSession] = [:]
    for c in cached {
        // JS BEHAVIOUR #2 — a duplicated id in `cached` keeps the LAST value.
        // `set` overwrites; it does not ignore. Fixture: `duplicated id in the cache`.
        if local.updateValue(c, forKey: c.sessionId) == nil { localOrder.append(c.sessionId) }
    }
    var live = Set<String>()
    for p in probe { live.insert(p.sessionId) }

    var plan = SyncPlan()
    for id in localOrder where !live.contains(id) { plan.drop.append(id) }

    // Newest first: what the user is likely to search for is what they were just
    // talking about, so a cold start should make that searchable first.
    //
    // JS BEHAVIOUR #3 — `Array.prototype.sort` has been stable since ES2019, so
    // rows with EQUAL watermarks come out in probe order. Swift's `sorted(by:)`
    // is documented as not stable, so the index is carried into the comparison
    // and breaks ties itself. Fixtures: `equal watermarks keep probe order`,
    // `ties inside a sorted run keep probe order`.
    let ordered = probe.enumerated()
        .sorted { a, b in
            a.element.watermark == b.element.watermark
                ? a.offset < b.offset
                : a.element.watermark > b.element.watermark
        }
        .map(\.element)

    for p in ordered {
        let l = local[p.sessionId]
        if let l, l.watermark == p.watermark, l.count == p.count {
            plan.upToDate.append(p)
            continue
        }
        // Only a SHRUNKEN count forces a wipe. A watermark that moved backwards
        // (a clock step, rows restored from a backup) does not, which leaves
        // `since` ahead of the server — reproduced deliberately, fixture
        // `watermark moved BACKWARD`. Whether it is right is a question for the
        // web; a port that "fixed" it here would just be a second answer.
        let reset = l != nil && l!.count > p.count
        plan.fetch.append(.init(probe: p, since: (l == nil || reset) ? 0 : l!.watermark, reset: reset))
    }
    return plan
}
